import Foundation
import Observation

/// What the store may answer and when the network is asked. Relay's four.
public enum FetchPolicy: Sendable {
    /// Render from the store when it has everything and nothing is stale;
    /// otherwise fetch.
    case storeOrNetwork
    /// Render what the store has at once, and always fetch.
    case storeAndNetwork
    /// Show loading until this handle's own response arrives.
    case networkOnly
    /// Never fetch; fail when the store cannot answer.
    case storeOnly

    /// The policy an operation runs under unless it names one: the store
    /// answers when it can, and the network when it cannot or the data is
    /// stale, as Relay's queries do by default.
    public static let `default`: FetchPolicy = .storeOrNetwork
}

/// An operation value: the variables of one operation, `Hashable` by them.
/// The compiler generates one struct per operation, conforming to the
/// protocol of its kind: `Query`, `Mutation` or `Subscription`.
public protocol Operation: Hashable, Sendable {
    associatedtype Data: Lens
    static var name: String { get }
    /// What a request carries of the operation: its text, or the id it was
    /// registered under, as the build decided.
    static var document: Document { get }
    /// The kind of operation, which a request says.
    static var kind: Request.Kind { get }
    @_spi(Generated) static var plan: Plan { get }
    /// `@throwOnFieldError`: an uncaught field error fails the operation.
    @_spi(Generated) static var throwsOnFieldError: Bool { get }
    /// Whether a `@required` field at the root can null the whole result.
    @_spi(Generated) static var bubbles: Bool { get }
    /// Whether the response may arrive in parts (`@defer`).
    @_spi(Generated) static var hasDeferred: Bool { get }
    /// The `onError` value `baton.json` names, sent with every request.
    @_spi(Generated) static var errorBehavior: ErrorBehavior? { get }
    /// `@cacheExpiration(seconds:)`: how old the operation's data may be
    /// before it reads as stale. None takes the store's default.
    @_spi(Generated) static var cacheExpiration: Duration? { get }
    var variables: Variables { get }
}

/// How an operation value stands to a handle. Unresolved: outside any
/// view, a value a navigation path carries or a parent constructs, which
/// reads as loading. Resolved: a view's storage made the handle the value
/// reads through. Not injected: a view outside every
/// `.environment(\.baton, ...)` asked, and there is no environment to make
/// a handle in, so the value reads as failed with
/// `EnvironmentError.notInjected`; nothing is fetched, and no store stands
/// in. The absence of an environment is not a session.
@_spi(Generated)
public enum Resolution<Handle: Sendable>: Sendable {
    case unresolved
    case notInjected
    case resolved(Handle)

    /// The handle, when the value is resolved to one.
    public var handle: Handle? {
        if case .resolved(let handle) = self { return handle }
        return nil
    }
}

/// A query value: inside a view it resolves to a handle through `@Query`,
/// and reads its phase and data through it. The resolution is the
/// mechanism's, set by the view's wrapper and declared by generated code.
public protocol Query: Operation {
    @_spi(Generated) var resolution: Resolution<OperationHandle<Self>> { get set }
}

extension Query {
    public static var kind: Request.Kind { .query }

    /// A library built for distribution takes no SPI requirement without a
    /// default; generated code declares the property, so this traps.
    @_spi(Generated) public var resolution: Resolution<OperationHandle<Self>> {
        get { fatalError("\(Self.self) has no resolution: an operation value is generated by batonc, which declares it") }
        set { fatalError("\(Self.self) has no resolution: an operation value is generated by batonc, which declares it") }
    }
}

/// A mutation value: called as an action through `@Mutation`, or committed
/// with `Environment.mutate`.
public protocol Mutation: Operation {}

extension Mutation {
    public static var kind: Request.Kind { .mutation }
}

/// A subscription value: inside a view it resolves to a handle through
/// `@Subscription`, which holds the stream of events open.
public protocol Subscription: Operation {
    @_spi(Generated) var resolution: Resolution<SubscriptionHandle<Self>> { get set }
}

extension Subscription {
    public static var kind: Request.Kind { .subscription }

    @_spi(Generated) public var resolution: Resolution<SubscriptionHandle<Self>> {
        get { fatalError("\(Self.self) has no resolution: an operation value is generated by batonc, which declares it") }
        set { fatalError("\(Self.self) has no resolution: an operation value is generated by batonc, which declares it") }
    }
}

extension Operation {
    /// The operation's text, when the build left it in the artifact; nil
    /// under `persistConfig`, where only the id ships.
    public static var text: String? {
        if case .text(let text) = document { return text }
        return nil
    }
}

extension Operation {
    /// A trap: every generated operation declares its plan, and a library
    /// built for distribution takes no SPI requirement without a default.
    @_spi(Generated) public static var plan: Plan {
        fatalError("\(Self.self) has no plan: an operation is generated by batonc, which declares it")
    }

    @_spi(Generated) public static var throwsOnFieldError: Bool { false }
    @_spi(Generated) public static var bubbles: Bool { false }
    @_spi(Generated) public static var hasDeferred: Bool { false }
    @_spi(Generated) public static var errorBehavior: ErrorBehavior? { nil }
    @_spi(Generated) public static var cacheExpiration: Duration? { nil }
}

/// The state of a resolved operation. Always synchronously readable.
public enum Phase<Data> {
    case loading
    case ready(Data)
    case failed(any Error)
}

/// The last fetch of a handle, as a value read beside the phase: idle, in
/// flight, or failed with its failure and when it failed. Not a phase: the
/// phase is what the data deserves and the fetch is what the network did,
/// so a fetch that fails behind data is read here while the phase stays
/// ready. The handle's next response replaces it.
public enum Fetch: Sendable {
    case idle
    case inFlight
    case failed(Failure, at: ContinuousClock.Instant)

    /// The failure, when the last fetch failed.
    public var failure: Failure? {
        if case .failed(let failure, _) = self { return failure }
        return nil
    }
}

/// A `storeOnly` operation whose data the store does not have.
public struct MissingDataError: Error, CustomStringConvertible, Sendable, LocalizedError {
    public let operationName: String
    public var description: String { "\(operationName): the store does not have this data and the policy forbids fetching" }
    public var errorDescription: String? { description }
}

extension Query {
    /// Loading until resolved inside a view; failed with
    /// `EnvironmentError.notInjected` in a view outside every environment.
    @MainActor public var phase: Phase<Data> {
        switch resolution {
        case .unresolved: .loading
        case .notInjected: .failed(EnvironmentError.notInjected)
        case .resolved(let handle): handle.phase
        }
    }

    /// Whether a fetch is running while earlier data stays visible.
    @MainActor public var isRefreshing: Bool { resolution.handle?.isRefreshing ?? false }

    /// The last fetch: idle, in flight, or failed with its failure and when.
    /// Idle where no environment could make one.
    @MainActor public var fetch: Fetch { resolution.handle?.fetch ?? .idle }

    /// Whether the data predates an invalidation or the cache expiration.
    @MainActor public var isStale: Bool { resolution.handle?.isStale ?? false }

    /// Fetches again and commits; the data stays visible meanwhile, and a
    /// failure is thrown here rather than shown in place of it. Outside
    /// every environment it throws `EnvironmentError.notInjected`.
    @MainActor public func refetch() async throws {
        switch resolution {
        case .unresolved: return
        case .notInjected: throw EnvironmentError.notInjected
        case .resolved(let handle): try await handle.refetch()
        }
    }

    /// After a failure, fetches again. A failure on field errors or a
    /// `@required` null keeps its data visible meanwhile, as a refetch does;
    /// any other shows loading.
    @MainActor public func retry() { resolution.handle?.retry() }
}

/// The in-flight state behind a mutation action, observable by the view.
@MainActor
@Observable
package final class MutationState {
    package internal(set) var inFlight = 0
    package init() {}
}

/// A mutation as a callable value, after SwiftUI's `dismiss` and `openURL`.
/// The compiler generates `callAsFunction` with one labelled parameter per
/// variable plus `optimistic:`; this is what it calls.
public struct MutationAction<Op: Mutation>: Sendable {
    let environment: Environment?
    let state: MutationState

    /// Whether a commit is running.
    @MainActor public var isInFlight: Bool { state.inFlight > 0 }

    /// Commits the mutation. An optimistic response, the payload its
    /// generated builder renders, shows at once as a layer that rebases
    /// under every commit until the server answers; on failure it is
    /// reverted and the error rethrown.
    @MainActor
    public func commit(_ operation: Op, optimistic: Payload? = nil) async throws -> Op.Data {
        // No environment, no session: an action outside every environment
        // says so rather than commit into a store that stands in.
        guard let environment else { throw EnvironmentError.notInjected }
        state.inFlight += 1
        defer { state.inFlight -= 1 }
        return try await environment.mutate(operation, optimistic: optimistic)
    }
}
