import Foundation
import Observation

/// What the store may answer and when the network is asked. Relay's four.
public enum FetchPolicy: Sendable {
    /// Render from the store when it has everything and nothing is stale;
    /// otherwise fetch.
    case storeOrNetwork
    /// Render what the store has at once, and always fetch.
    case storeAndNetwork
    /// Show loading until this handle's own response arrives.
    case networkOnly
    /// Never fetch; fail when the store cannot answer.
    case storeOnly

    /// The policy an operation runs under unless it names one: the store
    /// answers when it can, and the network when it cannot or the data is
    /// stale, as Relay's queries do by default.
    public static let `default`: FetchPolicy = .storeOrNetwork
}

/// An operation value: the variables of one operation, `Hashable` by them.
/// The compiler generates one struct per operation, conforming to the
/// protocol of its kind: `Query`, `Mutation` or `Subscription`.
public protocol Operation: Hashable, Sendable {
    associatedtype Data: Lens
    static var name: String { get }
    /// What a request carries of the operation: its text, or the id it was
    /// registered under, as the build decided.
    static var document: Document { get }
    /// The kind of operation, which a request says.
    static var kind: Request.Kind { get }
    @_spi(Generated) static var plan: Plan { get }
    /// `@throwOnFieldError`: an uncaught field error fails the operation.
    @_spi(Generated) static var throwsOnFieldError: Bool { get }
    /// Whether a `@required` field at the root can null the whole result.
    @_spi(Generated) static var bubbles: Bool { get }
    /// Whether the response may arrive in parts (`@defer`).
    @_spi(Generated) static var hasDeferred: Bool { get }
    /// The `onError` value `baton.json` names, sent with every request.
    @_spi(Generated) static var errorBehavior: ErrorBehavior? { get }
    /// `@cacheExpiration(seconds:)`: how old the operation's data may be
    /// before it reads as stale. None takes the store's default.
    @_spi(Generated) static var cacheExpiration: Duration? { get }
    var variables: Variables { get }
}

/// A query value: inside a view it resolves to a handle through `@Query`,
/// and reads its phase and data through it.
public protocol Query: Operation {
    var resolution: OperationHandle<Self>? { get set }
}

extension Query {
    public static var kind: Request.Kind { .query }
}

/// A mutation value: called as an action through `@Mutation`, or committed
/// with `Environment.mutate`.
public protocol Mutation: Operation {}

extension Mutation {
    public static var kind: Request.Kind { .mutation }
}

/// A subscription value: inside a view it resolves to a handle through
/// `@Subscription`, which holds the stream of events open.
public protocol Subscription: Operation {
    var resolution: SubscriptionHandle<Self>? { get set }
}

extension Subscription {
    public static var kind: Request.Kind { .subscription }
}

extension Operation {
    /// The operation's text, when the build left it in the artifact; nil
    /// under `persistConfig`, where only the id ships.
    public static var text: String? {
        if case .text(let text) = document { return text }
        return nil
    }
}

extension Operation {
    /// A trap: every generated operation declares its plan, and a library
    /// built for distribution takes no SPI requirement without a default.
    @_spi(Generated) public static var plan: Plan {
        fatalError("\(Self.self) has no plan: an operation is generated by batonc, which declares it")
    }

    @_spi(Generated) public static var throwsOnFieldError: Bool { false }
    @_spi(Generated) public static var bubbles: Bool { false }
    @_spi(Generated) public static var hasDeferred: Bool { false }
    @_spi(Generated) public static var errorBehavior: ErrorBehavior? { nil }
    @_spi(Generated) public static var cacheExpiration: Duration? { nil }
}

/// The state of a resolved operation. Always synchronously readable.
public enum Phase<Data> {
    case loading
    case ready(Data)
    case failed(any Error)
}

/// The last fetch of a handle, as a value read beside the phase: idle, in
/// flight, or failed with its failure and when it failed. Not a phase: the
/// phase is what the data deserves and the fetch is what the network did,
/// so a fetch that fails behind data is read here while the phase stays
/// ready. The handle's next response replaces it.
public enum Fetch: Sendable {
    case idle
    case inFlight
    case failed(Failure, at: ContinuousClock.Instant)

    /// The failure, when the last fetch failed.
    public var failure: Failure? {
        if case .failed(let failure, _) = self { return failure }
        return nil
    }
}

/// A `storeOnly` operation whose data the store does not have.
public struct MissingDataError: Error, CustomStringConvertible, Sendable, LocalizedError {
    public let operationName: String
    public var description: String { "\(operationName): the store does not have this data and the policy forbids fetching" }
    public var errorDescription: String? { description }
}

extension Query {
    /// Loading until resolved inside a view.
    @MainActor public var phase: Phase<Data> { resolution?.phase ?? .loading }

    /// Whether a fetch is running while earlier data stays visible.
    @MainActor public var isRefreshing: Bool { resolution?.isRefreshing ?? false }

    /// The last fetch: idle, in flight, or failed with its failure and when.
    @MainActor public var fetch: Fetch { resolution?.fetch ?? .idle }

    /// Whether the data predates an invalidation or the cache expiration.
    @MainActor public var isStale: Bool { resolution?.isStale ?? false }

    /// Fetches again and commits; the data stays visible meanwhile, and a
    /// failure is thrown here rather than shown in place of it.
    @MainActor public func refetch() async throws { try await resolution?.refetch() }

    /// After a failure, fetches again. A failure on field errors or a
    /// `@required` null keeps its data visible meanwhile, as a refetch does;
    /// any other shows loading.
    @MainActor public func retry() { resolution?.retry() }
}

/// Type-erased view of a handle, for the environment's bookkeeping.
@MainActor
protocol AnyOperationHandle: AnyObject {
    /// The operation's name and variables, as the image names it.
    var key: String { get }
    /// The handle's root among the store's.
    var root: Store.Root { get }
    var retainCount: Int { get }
    /// One holder fewer: a retention ended, of a holder whose policy allowed
    /// the network or not.
    func release(allowingNetwork: Bool)
    func refetchIfStale()
    /// Fetches again when the data is stale or the last fetch failed, if a
    /// holder allows the network.
    func revalidate()
    /// Fetches again for a heal, unless a fetch is in flight.
    func fetchForHeal()
    /// The environment ended: what the handle shows says so, and nothing is
    /// fetched again.
    func end()
    /// Settles the phase again after a commit changed a field error or a
    /// null, for policies that read them.
    func reevaluate()
    func cancel()
    /// The environment went inactive: a stream closes while its handle stays
    /// retained; a query reads nothing of it.
    func park()
    /// The environment is active again: a parked stream opens again.
    func resume()
}

/// The live side of an operation value: its phase, its fetch, its data, and
/// its place among the store's roots. Created by the environment, shared by
/// equal operation values.
@MainActor
@Observable
public final class OperationHandle<Op: Query>: AnyOperationHandle {
    public let operation: Op
    public private(set) var phase: Phase<Op.Data> = .loading
    /// The last fetch, as a value: idle, in flight, or failed with its
    /// failure and when it failed. A fetch that fails behind data leaves the
    /// phase as it was and is read here, by every view of the handle.
    public private(set) var fetch: Fetch = .idle
    /// When the store last committed the operation's response, in this launch
    /// or, from the image, an earlier one: the root's age.
    public var fetchTime: ContinuousClock.Instant? { root.fetchTime }
    /// The environment that made the handle. A view may release its handle
    /// after the environment is gone, which then does nothing.
    @ObservationIgnored private(set) weak var environment: Environment?
    @ObservationIgnored private let store: Store
    /// The operation's name and variables, as the image names it.
    @ObservationIgnored let key: String
    /// The handle's root among the store's: what keeps its records alive.
    @ObservationIgnored let root: Store.Root
    /// The fetch in flight; its value is the failure it ended with.
    @ObservationIgnored private var task: Task<(any Error)?, Never>?
    @ObservationIgnored var resolved: ResolvedSelection { root.resolved }
    /// The scope every lens of the handle reads in.
    @ObservationIgnored private let owner: Owner
    /// Set by a `preload` that fetched: the first attach finds the fetch
    /// made, or on the way.
    @ObservationIgnored var preloaded = false
    /// The policy of the last attach, which the retention it makes keeps.
    @ObservationIgnored private var lastPolicy: FetchPolicy = .default
    /// The field errors of the last fetch that no field in the store holds,
    /// which `@throwOnFieldError` counts until the next fetch.
    @ObservationIgnored private var unplaced: [FieldError] = []

    init(operation: Op, key: String, environment: Environment) {
        self.operation = operation
        self.key = key
        self.environment = environment
        store = environment.store
        root = environment.store.root(key, resolved: Op.plan.resolve(operation.variables, in: environment.store.keys), record: environment.store.root)
        owner = Owner(variables: operation.variables, store: environment.store, environment: environment, root: root)
    }

    /// How many hold the handle's root; for the tests.
    package var retainCount: Int { root.holders }

    /// Moves to the next phase. Ready after ready is no change: both carry a
    /// lens over the same root, so a fetch that changed nothing re-runs no
    /// body that reads the phase. Nor is a failure on the same field errors,
    /// or the same `@required` path, after another.
    private func settle(_ next: Phase<Op.Data>) {
        switch (phase, next) {
        case (.ready, .ready):
            return
        case let (.failed(old as FieldErrors), .failed(new as FieldErrors)) where old.errors == new.errors:
            return
        case let (.failed(old as RequiredFieldError), .failed(new as RequiredFieldError)) where old.path == new.path:
            return
        default:
            phase = next
        }
    }

    /// Whether a fetch is in flight.
    var isFetching: Bool { task != nil }

    /// Whether a fetch is running while earlier data stays visible: data
    /// present and a fetch in flight. Nothing refreshes behind loading, nor
    /// behind a failure with no data in the store.
    public var isRefreshing: Bool {
        guard case .inFlight = fetch else { return false }
        return showsData
    }

    /// Whether the phase shows data: ready, or failed on field errors or a
    /// `@required` null, whose data is in the store and ages as ready data
    /// does.
    private var showsData: Bool {
        switch phase {
        case .ready, .failed(is FieldErrors), .failed(is RequiredFieldError): true
        case .loading, .failed: false
        }
    }

    private var anchor: Anchor {
        Anchor(record: store.root, owner: owner)
    }

    private var data: Op.Data { Op.Data(anchor: anchor) }

    /// The phase the store's data deserves: ready, unless the operation's
    /// policies say otherwise. `@throwOnFieldError` fails on an uncaught field
    /// error in the operation's own selection, as Relay's reader of the
    /// operation does (a spread's fragment weighs its own), or on one the
    /// last response carried that no field holds; a root whose `@required`
    /// fields bubble fails, because there is no null data. The fetch and
    /// every later commit settle the phase by this one reading.
    private func evaluate() -> Phase<Op.Data> {
        if Op.throwsOnFieldError {
            let errors = unplaced + Op.Data.fieldErrors(anchor)
            if !errors.isEmpty { return .failed(FieldErrors(errors)) }
        }
        if Op.bubbles, let path = Op.Data.missingRequiredField(anchor) {
            return .failed(RequiredFieldError(bubbledToRootOf: Op.name, path: path))
        }
        return .ready(data)
    }

    /// Whether the store holds every field the operation selects. For the
    /// tests, until the handle derives its phase.
    package var isComplete: Bool { store.check(resolved) != .miss }

    /// Whether the data predates `Environment.invalidate()` or is older than
    /// the operation's expiration, `@cacheExpiration(seconds:)` in its
    /// document, or the store's default when it states none. A handle that
    /// is loading, or failed with no data behind the failure, has nothing to
    /// go stale; one failed on field errors or a `@required` null has its
    /// data in the store, and it ages as ready data does.
    public var isStale: Bool {
        guard showsData else { return false }
        if root.fetchEpoch < store.invalidationEpoch { return true }
        guard let expiration = Op.cacheExpiration ?? store.cacheExpiration else { return false }
        // Data with no known age is stale wherever an expiration applies: the
        // rule hydration has, in memory too.
        guard let fetchTime = root.fetchTime else { return true }
        return fetchTime + expiration < .now
    }

    /// Applies a policy on attach: renders what the store allows, fetches
    /// when the policy asks for it.
    func apply(_ policy: FetchPolicy) {
        lastPolicy = policy
        // A preload's fetch is the first attach's: in flight, or done with
        // data that is still fresh, it is not made again. A parked handle
        // saw no commit since that fetch, so its phase is settled here.
        if preloaded {
            preloaded = false
            if task != nil { return }
            if case .ready = phase, !isStale {
                reevaluate()
                return
            }
        }
        if policy == .networkOnly {
            // What the store holds is not asked; a handle no one shows yet
            // waits for its own response, which may be a refetch in flight:
            // nothing shows behind it.
            if retainCount == 0 { phase = .loading }
            fetchUnlessInFlight()
            return
        }
        let answer = store.check(resolved)
        let complete = answer != .miss
        // The deferred parts the store holds half are cleared and fetched;
        // the initial part renders meanwhile.
        let partial = complete && Op.hasDeferred && !store.deferredPartsHold(resolved)
        if complete { store.takeAge(root, hydrated: answer == .image) }
        if complete {
            switch phase {
            case .loading:
                phase = evaluate()
            // A parked handle saw no commit: what it failed on may be gone,
            // and a field error or a null may have come.
            case .ready, .failed(is FieldErrors), .failed(is RequiredFieldError):
                settle(evaluate())
            default:
                break
            }
        }
        switch policy {
        case .storeOnly:
            if !complete, case .loading = phase {
                phase = .failed(MissingDataError(operationName: Op.name))
            }
        case .storeOrNetwork:
            // An error the last response carried with no field to hold it
            // is in no record a commit could clear; only a fetch clears it.
            let failsUnplaced = Op.throwsOnFieldError && !unplaced.isEmpty
            if !complete || partial || isStale || failsUnplaced { fetchUnlessInFlight() }
        case .storeAndNetwork, .networkOnly:
            fetchUnlessInFlight()
        }
    }

    /// Starts a fetch unless one is in flight.
    func fetchUnlessInFlight() {
        guard task == nil else { return }
        start()
    }

    private func start() {
        task?.cancel()
        guard let current = environment, !current.ended else {
            // Nothing can fetch for a handle whose environment is gone or
            // ended: it keeps the data it shows and says why it cannot load
            // more.
            task = nil
            fetch = .failed(.environment(.gone), at: .now)
            if case .loading = phase {
                phase = .failed(EnvironmentError.gone)
            }
            return
        }
        fetch = .inFlight
        task = Task { [weak self] in
            guard let self, let environment else { return nil }
            var failure: (any Error)?
            do {
                let committed = try await environment.fetch(operation, resolved: resolved) { [weak self] firstPart in
                    // A deferred response renders its first part at once, by
                    // the errors that part carried with no field to hold
                    // them; it is fetched, and fresh, once the stream
                    // completes.
                    guard let self, !Task.isCancelled else { return }
                    unplaced = firstPart.unplaced
                    settle(evaluate())
                }
                if !Task.isCancelled { unplaced = committed.unplaced }
            } catch {
                failure = error
            }
            // A cancelled fetch was superseded or evicted. The handle's state
            // belongs to whoever cancelled it, however the fetch ended.
            guard !Task.isCancelled else { return nil }
            task = nil
            switch failure {
            case nil:
                fetch = .idle
                settle(evaluate())
                // A response whose field errors fail the operation fails its
                // refetch the same way.
                if case .failed(let error) = phase { return error }
            case is CancellationError:
                // The transport cancelled its own work: nothing to show.
                fetch = .idle
                return nil
            case let error?:
                // The fetch records its failure and when, for every view of
                // the handle; `refetch()` throws the error as well. Data
                // behind the failure stays visible, and so does a failure the
                // data is in the store for, which a later commit or attach
                // can still settle by that data; with nothing to show, the
                // phase fails.
                fetch = .failed(Failure(error), at: .now)
                if !showsData { phase = .failed(error) }
            }
            return failure
        }
    }

    /// Fetches again and waits for the result; the data stays visible
    /// meanwhile, and a failure is thrown rather than shown in its place. A
    /// refetch that a later fetch superseded returns without one.
    public func refetch() async throws {
        start()
        if let failure = await task?.value { throw failure }
    }

    /// Waits for an in-flight fetch, if any. For the tests and the benchmarks,
    /// until the fetch is a value a reader awaits.
    package func settle() async {
        _ = await task?.value
    }

    /// After a failure, fetches again. A failure on field errors or a
    /// `@required` null stays in place, its data visible, and the fetch
    /// refreshes behind it as `refetch()` does: a fetch that fails at the
    /// transport leaves it for a later commit or attach to settle. Any other
    /// failure shows loading meanwhile.
    public func retry() {
        if case .failed = phase, !showsData { phase = .loading }
        start()
    }

    /// Keeps the operation's records alive until the retention ends. `@Query`
    /// holds one for a view's lifetime; a model or a view controller holds
    /// one in a property and lets it go with itself.
    public func retain() -> Retention {
        let allowsNetwork = lastPolicy != .storeOnly
        store.retain(root, allowingNetwork: allowsNetwork)
        environment?.didRetain(self)
        return Retention(self, allowsNetwork: allowsNetwork)
    }

    /// A retention ended. At no holder the root enters the release buffer,
    /// and the handles of the roots it pushes out go with their fetches.
    func release(allowingNetwork: Bool) {
        let evicted = store.release(root, allowingNetwork: allowingNetwork)
        environment?.evict(evicted)
    }

    /// A fetch the runtime starts asks whether a holder allows the network: a
    /// `storeOnly` holder is fetched for by neither an invalidation nor a
    /// revalidation nor a heal.
    func refetchIfStale() {
        if isStale, root.allowsNetwork { fetchUnlessInFlight() }
    }

    func revalidate() {
        guard root.allowsNetwork else { return }
        if isStale { fetchUnlessInFlight() }
        if case .failed = fetch { fetchUnlessInFlight() }
    }

    func fetchForHeal() {
        if root.allowsNetwork { fetchUnlessInFlight() }
    }

    /// A query reads nothing of the environment's activity.
    func park() {}
    func resume() {}

    func reevaluate() {
        guard Op.throwsOnFieldError || Op.bubbles else { return }
        switch phase {
        case .loading:
            return
        case .failed(let error) where !(error is FieldErrors || error is RequiredFieldError):
            return
        default:
            settle(evaluate())
        }
    }

    func cancel() {
        task?.cancel()
        task = nil
        fetch = .idle
    }

    /// The environment ended: the fetch in flight is cancelled, the phase
    /// says gone to its observers, and the records the data read are the
    /// store's to clear.
    func end() {
        cancel()
        fetch = .failed(.environment(.gone), at: .now)
        phase = .failed(EnvironmentError.gone)
    }
}

/// The in-flight state behind a mutation action, observable by the view.
@MainActor
@Observable
package final class MutationState {
    package internal(set) var inFlight = 0
    package init() {}
}

/// A mutation as a callable value, after SwiftUI's `dismiss` and `openURL`.
/// The compiler generates `callAsFunction` with one labelled parameter per
/// variable plus `optimistic:`; this is what it calls.
public struct MutationAction<Op: Mutation>: Sendable {
    let environment: Environment?
    let state: MutationState

    /// Whether a commit is running.
    @MainActor public var isInFlight: Bool { state.inFlight > 0 }

    /// Commits the mutation. An optimistic response shows at once as a layer
    /// that rebases under every commit until the server answers; on failure
    /// it is reverted and the error rethrown.
    @MainActor
    public func commit(_ operation: Op, optimistic: Variable? = nil) async throws -> Op.Data {
        let environment = Environment.resolve(environment)
        state.inFlight += 1
        defer { state.inFlight -= 1 }
        return try await environment.mutate(operation, optimistic: optimistic)
    }
}
// MARK: Subscriptions

/// The stream a subscription handle holds, as a value read beside its
/// events: not started, or parked while the environment is inactive;
/// connecting until the first event; open; waiting to reconnect after a
/// failure, until the instant it tries again; or ended, by the server's
/// completion or by the environment's end. Not a phase: a subscription has
/// no data of its own to wait for, so it has no loading.
public enum Stream: Sendable {
    case idle
    case connecting
    case open
    /// A failure ended the stream, in `error`, and the handle opens it again
    /// at the instant, by its fixed backoff.
    case waiting(until: ContinuousClock.Instant)
    /// The server completed the stream (`nil`), or a failure ended it for
    /// good: the handle was not retained, or the environment ended.
    case ended(Failure?)

    /// Whether the stream is connecting or open.
    public var isActive: Bool {
        switch self {
        case .connecting, .open: true
        case .idle, .waiting, .ended: false
        }
    }
}

/// The backoff before a failed stream is opened again: a step that doubles
/// from one second to thirty, jittered to between half and the whole of it,
/// reset by an event. Fixed: no server has shown constants of its own to be
/// needed, and a settings bag is refused. The base is a package knob for
/// tests alone.
@MainActor
package enum SubscriptionBackoff {
    package static var base: Duration = .seconds(1)
    static let cap: Duration = .seconds(30)

    static func delay(_ attempt: Int) -> Duration {
        let step = min(base * (1 << min(attempt, 10)), cap)
        return step / 2 + step / 2 * Double.random(in: 0...1)
    }
}

/// The live side of a subscription value: the stream it holds open, how many
/// events arrived, the latest event's data, and the error that ended it.
/// Each event is normalized with the operation's plan at the subscription root
/// and committed, so its entities merge and its edge directives apply.
@MainActor
@Observable
public final class SubscriptionHandle<Op: Subscription>: AnyOperationHandle {
    public let operation: Op
    /// How many events have been committed.
    public private(set) var events = 0
    /// The latest event, as a lens over the subscription root.
    public private(set) var latest: Op.Data?
    /// The error of the last event, cleared by the next good one, or the
    /// error that ended the stream.
    public private(set) var error: (any Error)?
    /// The stream, as a value: idle, connecting, open, waiting to reconnect,
    /// or ended.
    public private(set) var stream: Stream = .idle
    /// Whether the stream is connecting or open.
    public var isActive: Bool { stream.isActive }
    /// How many times the stream was opened again after it had been open or
    /// had failed: after a failure's backoff, or after the environment was
    /// inactive. Events may have been missed across each; an owner that
    /// observes the count refetches its baseline.
    public private(set) var resumptions = 0
    /// Whether the environment's inactivity closed the stream while the
    /// handle stayed retained, so activity opens it again.
    @ObservationIgnored private var parked = false
    /// The environment that made the handle; releasing the handle after it
    /// is gone does nothing.
    @ObservationIgnored private(set) weak var environment: Environment?
    @ObservationIgnored private let store: Store
    @ObservationIgnored private var task: Task<Void, Never>?
    /// The operation's name and variables, as the image names it.
    @ObservationIgnored let key: String
    /// The handle's root among the store's, while retained.
    @ObservationIgnored let root: Store.Root
    @ObservationIgnored var resolved: ResolvedSelection { root.resolved }
    /// The scope every event's lens reads in.
    @ObservationIgnored private let owner: Owner

    init(operation: Op, key: String, environment: Environment) {
        self.operation = operation
        self.key = key
        self.environment = environment
        store = environment.store
        root = environment.store.root(key, resolved: Op.plan.resolve(operation.variables, in: environment.store.keys), record: environment.store.subscriptionRoot)
        owner = Owner(variables: operation.variables, store: environment.store, environment: environment)
    }

    /// How many hold the stream open; for the tests.
    package var retainCount: Int { root.holders }

    /// Opens the stream unless it is open, or its environment is gone.
    func start() {
        guard task == nil, let current = environment, !current.ended else { return }
        // Retained while the environment is inactive: the stream waits parked
        // for activity, as one closed by inactivity does.
        guard current.isActive else {
            parked = true
            stream = .idle
            return
        }
        parked = false
        stream = .connecting
        error = nil
        task = Task { [weak self] in
            guard let self, let environment else { return }
            var attempt = 0
            while true {
                // How the stream ended, written once the task is known not
                // to have been replaced: the stream a newer one replaced
                // leaves the newer one's state be.
                var ending: Stream = .ended(nil)
                var failed = false
                do {
                    for try await payload in environment.subscribe(operation) {
                        guard !Task.isCancelled else { return }
                        do {
                            // The door checks the task's cancellation before
                            // the commit: a stream commits until its task ends.
                            _ = try await environment.commit(payload, plan: resolved, root: root)
                            events += 1
                            latest = Op.Data(anchor: Anchor(record: store.subscriptionRoot, owner: owner))
                            error = nil
                            stream = .open
                            attempt = 0
                        } catch let failure as GraphQLErrors {
                            // An event with errors and no data is one bad event;
                            // the stream goes on. The ingest runs to its end
                            // whoever cancelled the task meanwhile.
                            guard !Task.isCancelled else { return }
                            error = failure
                        } catch is CancellationError {
                            return
                        }
                    }
                } catch is CancellationError {
                    // A transport that cancelled its own work ended the
                    // stream, with nothing to show; a cancellation of this
                    // task returns below.
                } catch {
                    guard !Task.isCancelled else { return }
                    self.error = error
                    ending = .ended(Failure(error))
                    failed = true
                }
                guard !Task.isCancelled else { return }
                // A failure while the handle is retained is a wait, not an
                // end: the stream is opened again by the backoff. The server's
                // completion ends it, and so does a request error, the
                // server's refusal of the operation as written, which a retry
                // would only repeat.
                let refused = if case .ended(.request?) = ending { true } else { false }
                guard failed, !refused, retainCount > 0, !environment.ended else {
                    task = nil
                    stream = ending
                    return
                }
                // Failed while the environment is inactive: parked, so that
                // activity opens the stream again rather than the backoff.
                guard environment.isActive else {
                    task = nil
                    parked = true
                    stream = .idle
                    return
                }
                let delay = SubscriptionBackoff.delay(attempt)
                attempt += 1
                stream = .waiting(until: .now + delay)
                do {
                    try await Task.sleep(for: delay)
                } catch {
                    // Cancelled by a release, a park, a retry or the end,
                    // which set the state.
                    return
                }
                // A cancellation that came after the sleep ended but before
                // this task resumed is the canceller's to state: a retry's
                // newer task or the environment's end is left be.
                guard !Task.isCancelled else { return }
                guard retainCount > 0 else {
                    task = nil
                    stream = .idle
                    return
                }
                resumptions += 1
                stream = .connecting
                error = nil
            }
        }
    }

    /// The environment went inactive: the stream closes while the handle
    /// stays retained, and activity opens it again.
    func park() {
        guard task != nil else { return }
        task?.cancel()
        task = nil
        parked = true
        stream = .idle
    }

    /// The environment is active again: a stream parked by its inactivity is
    /// opened again, counted as a resumption.
    func resume() {
        guard parked, retainCount > 0, task == nil else { return }
        resumptions += 1
        start()
    }

    /// Opens the stream again after it ended, by an error or the server's
    /// completion, while the handle is retained.
    public func retry() {
        guard retainCount > 0 else { return }
        cancel()
        start()
    }

    /// Keeps the stream open and the latest event's records alive until the
    /// retention ends.
    public func retain() -> Retention {
        store.retain(root, allowingNetwork: true)
        environment?.didRetain(self)
        start()
        return Retention(self, allowsNetwork: true)
    }

    /// A retention ended. At no holder the stream closes and the root leaves
    /// at once; nothing is buffered.
    func release(allowingNetwork: Bool) {
        _ = store.release(root, allowingNetwork: allowingNetwork, buffering: false)
        guard root.holders == 0 else { return }
        cancel()
        environment?.didEnd(self)
    }

    func refetchIfStale() {}

    func revalidate() {}

    func fetchForHeal() {}

    func reevaluate() {}

    /// The environment ended: the stream closes and says so.
    func end() {
        cancel()
        error = EnvironmentError.gone
        stream = .ended(.environment(.gone))
    }

    func cancel() {
        task?.cancel()
        task = nil
        stream = .idle
    }
}

/// A subscription value, resolved inside a view through `@Subscription`.
extension Subscription {
    /// The live side, which the storage that resolved the value holds.
    @MainActor public var subscription: SubscriptionHandle<Self>? { resolution }
}
