query TestProfileQuery(
  $id: ID!
) {
  character(id: $id) {
    ...TestProfile_character
    ...TestStrict_character
    ...TestAppearances_character @defer(label: "TestProfileQuery$defer$TestAppearances_character")
    id
  }
}

fragment TestAppearances_character on Character {
  episode {
    name
    air_date
    id
  }
}

fragment TestProfile_character on Character {
  name
  origin {
    name
    id
  }
  status
  image
  location {
    name
    dimension
    id
  }
  gender
}

fragment TestStrict_character on Character {
  species
  type
}
