//! The Swift emitter: lens types, operation values, plan tables, mutation
//! actions with their optimistic builders, connection lenses with their
//! pagination, and the shared file of interned types and slots. Everything
//! here reads the plan IR only.
//!
//! Output per host file `X.swift` is `X.baton.swift`; the per-target
//! `Baton.baton.swift` carries `Types` and `Slots`.

use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;

use crate::pipeline::{
    ArgumentValuePlan, ConnectionPlan, ConstantPlan, FragmentPlan, HandlePlan, LookupPlan,
    OperationPlan, Plan, RefetchPlan, SelectionPlan, TypeKind, VariablePlan,
};

/// Generated Swift, grouped by the source file that declared the documents.
pub struct Output {
    pub files: BTreeMap<String, String>,
    pub shared: String,
}

/// A slot the generated code refers to: a parent type and a storage key.
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct SlotRef {
    type_name: String,
    storage_key: String,
}

impl SlotRef {
    fn is_dynamic(&self) -> bool {
        self.storage_key.contains('$')
    }

    /// `Character_name`, or `Query_characters_1a2b3c` when the key has arguments.
    fn identifier(&self) -> String {
        let field = self
            .storage_key
            .split('(')
            .next()
            .unwrap_or(&self.storage_key);
        if field == self.storage_key {
            format!("{}_{}", self.type_name, field)
        } else {
            let digest = format!("{:x}", md5::compute(self.storage_key.as_bytes()));
            format!("{}_{}_{}", self.type_name, field, &digest[..6])
        }
    }

    /// The Swift expression that yields the slot.
    fn expression(&self) -> String {
        if self.is_dynamic() {
            format!("Slots.{}(anchor.variables)", self.identifier())
        } else {
            format!("Slots.{}", self.identifier())
        }
    }
}

struct Emitter {
    slots: BTreeSet<SlotRef>,
    types: BTreeSet<String>,
    /// Every fragment's `@argumentDefinitions`, for binding spreads.
    fragment_arguments: BTreeMap<String, Vec<VariablePlan>>,
}

/// What the lenses of one document share: the fragment's `@refetchable` data,
/// reached from a nested connection lens through the fragment's name.
#[derive(Clone, Copy)]
struct Context<'a> {
    owner: &'a str,
    refetch: Option<&'a RefetchPlan>,
    arguments: &'a [VariablePlan],
}

/// A nested lens type still to be written: name, GraphQL type, abstractness,
/// selections, and the connection it reads when the field is one.
struct Nested {
    name: String,
    type_name: String,
    is_abstract: bool,
    selections: Vec<SelectionPlan>,
    connection: Option<ConnectionPlan>,
}

pub fn emit(plan: &Plan) -> Output {
    let mut emitter = Emitter {
        slots: BTreeSet::new(),
        types: BTreeSet::new(),
        fragment_arguments: plan
            .fragments
            .iter()
            .map(|fragment| (fragment.name.clone(), fragment.arguments.clone()))
            .collect(),
    };
    let mut files: BTreeMap<String, String> = BTreeMap::new();
    for fragment in &plan.fragments {
        let text = emitter.fragment(fragment);
        files
            .entry(fragment.source.clone())
            .or_default()
            .push_str(&text);
    }
    for operation in &plan.operations {
        let text = emitter.operation(operation);
        files
            .entry(operation.source.clone())
            .or_default()
            .push_str(&text);
    }
    for text in files.values_mut() {
        *text = format!("{HEADER}\n{text}");
    }
    Output {
        shared: emitter.shared(),
        files,
    }
}

const HEADER: &str = "// Generated by batonc. Do not edit.\nimport Baton\n";

impl Emitter {
    fn shared(&self) -> String {
        let mut output = String::new();
        output.push_str(HEADER);
        output.push('\n');
        output
            .push_str("/// Interned schema types used by this module's documents.\nenum Types {\n");
        for type_name in &self.types {
            let _ = writeln!(
                output,
                "    static let {type_name} = Baton.Registry.type(\"{type_name}\")"
            );
        }
        output.push_str(
            "}\n\n/// Interned storage keys used by this module's documents.\nenum Slots {\n",
        );
        for slot in &self.slots {
            if slot.is_dynamic() {
                let _ = writeln!(
                    output,
                    "    static func {}(_ variables: Baton.Variables) -> Baton.Slot {{\n        Baton.Registry.slot(Types.{}, {})\n    }}",
                    slot.identifier(),
                    slot.type_name,
                    dynamic_key_expression(&slot.storage_key, "variables")
                );
            } else {
                let _ = writeln!(
                    output,
                    "    static let {} = Baton.Registry.slot(Types.{}, {})",
                    slot.identifier(),
                    slot.type_name,
                    swift_literal(&slot.storage_key)
                );
            }
        }
        output.push_str("}\n");
        output
    }

    fn fragment(&mut self, fragment: &FragmentPlan) -> String {
        let mut output = String::new();
        let _ = writeln!(
            output,
            "/// Lens for `fragment {} on {}`.",
            fragment.name, fragment.type_condition
        );
        let context = Context {
            owner: &fragment.name,
            refetch: fragment.refetch.as_ref(),
            arguments: &fragment.arguments,
        };
        self.lens_struct(
            &mut output,
            &fragment.name,
            &fragment.type_condition,
            fragment.type_is_abstract,
            &fragment.reader,
            "",
            context,
            None,
            true,
        );
        output.push('\n');
        output
    }

    fn operation(&mut self, operation: &OperationPlan) -> String {
        let mut output = String::new();
        let _ = writeln!(
            output,
            "/// Operation value for `{} {}`.",
            operation.kind, operation.name
        );
        let _ = writeln!(
            output,
            "public struct {}: Baton.Operation {{",
            operation.name
        );
        for variable in &operation.variables {
            let _ = writeln!(
                output,
                "    public var {}: {}",
                variable.name,
                variable_type(variable)
            );
        }
        let _ = writeln!(
            output,
            "    public var resolution: Baton.OperationHandle<Self>? = nil\n"
        );
        let parameters = parameter_list(&operation.variables);
        let _ = writeln!(output, "    public init({parameters}) {{");
        for variable in &operation.variables {
            let _ = writeln!(output, "        self.{0} = {0}", variable.name);
        }
        output.push_str("    }\n\n");
        let _ = writeln!(
            output,
            "    public static let name = \"{}\"",
            operation.name
        );
        let _ = writeln!(
            output,
            "    public static let kind = Baton.OperationKind.{}",
            operation.kind
        );
        let _ = writeln!(
            output,
            "    public static let persistedID = \"{}\"",
            operation.id
        );
        let _ = writeln!(
            output,
            "    public static let text = #\"\"\"\n{}\n\"\"\"#\n",
            operation.text.trim_end()
        );
        output.push_str("    public var variables: Baton.Variables {\n        Baton.Variables([");
        if operation.variables.is_empty() {
            output.push(':');
        } else {
            let entries: Vec<String> = operation
                .variables
                .iter()
                .map(|variable| format!("\"{0}\": Baton.Variable({0})", variable.name))
                .collect();
            output.push_str(&entries.join(", "));
        }
        output.push_str("])\n    }\n\n");
        output.push_str("    public static func == (lhs: Self, rhs: Self) -> Bool {\n");
        if operation.variables.is_empty() {
            output.push_str("        true\n");
        } else {
            let comparisons: Vec<String> = operation
                .variables
                .iter()
                .map(|variable| format!("lhs.{0} == rhs.{0}", variable.name))
                .collect();
            let _ = writeln!(output, "        {}", comparisons.join(" && "));
        }
        output.push_str("    }\n\n    public func hash(into hasher: inout Hasher) {\n");
        for variable in &operation.variables {
            let _ = writeln!(output, "        hasher.combine({})", variable.name);
        }
        output.push_str("    }\n\n");

        // The normalization plan, as static data.
        self.types.insert(operation.root_type.clone());
        output.push_str("    public static let plan = Baton.Plan(root: ");
        self.selection_plan(
            &mut output,
            &operation.root_type,
            false,
            false,
            &operation.normalization,
            2,
        );
        output.push_str(")\n\n");

        // The root lens.
        let context = Context {
            owner: &operation.name,
            refetch: None,
            arguments: &operation.variables,
        };
        self.lens_struct(
            &mut output,
            "Data",
            &operation.root_type,
            false,
            &operation.reader,
            "    ",
            context,
            None,
            false,
        );

        if operation.kind == "mutation" {
            output.push('\n');
            output.push_str("    public typealias Action = Baton.MutationAction<Self>\n\n");
            self.optimistic_builder(
                &mut output,
                "OptimisticResponse",
                &operation.normalization,
                "    ",
            );
        }
        output.push_str("}\n\n");

        if operation.kind == "mutation" {
            let parameters = parameter_list(&operation.variables);
            let separator = if operation.variables.is_empty() {
                ""
            } else {
                ", "
            };
            let arguments: Vec<String> = operation
                .variables
                .iter()
                .map(|variable| format!("{0}: {0}", variable.name))
                .collect();
            let _ = writeln!(
                output,
                "extension Baton.MutationAction where Op == {name} {{\n    /// Commits the mutation; the optimistic response, if any, shows at once and rebases until the server answers.\n    @MainActor @discardableResult\n    public func callAsFunction({parameters}{separator}optimistic: {name}.OptimisticResponse? = nil) async throws -> {name}.Data {{\n        try await commit({name}({args}), optimistic: optimistic?.variable)\n    }}\n}}\n",
                name = operation.name,
                args = arguments.join(", ")
            );
        }
        output
    }

    /// Writes a lens struct for a selection set on `type_name`. A fragment root
    /// with `@refetchable` gets `refetch()`; a connection field's lens gets the
    /// connection state and, inside a refetchable fragment, `loadNext`.
    #[allow(clippy::too_many_arguments)]
    fn lens_struct(
        &mut self,
        output: &mut String,
        name: &str,
        type_name: &str,
        type_is_abstract: bool,
        selections: &[SelectionPlan],
        indent: &str,
        context: Context<'_>,
        connection: Option<&ConnectionPlan>,
        is_fragment_root: bool,
    ) {
        self.types.insert(type_name.to_string());
        let _ = writeln!(output, "{indent}public struct {name}: Baton.Lens {{");
        let _ = writeln!(output, "{indent}    public let anchor: Baton.Anchor");
        let _ = writeln!(
            output,
            "{indent}    public init(anchor: Baton.Anchor) {{ self.anchor = anchor }}"
        );
        let _ = writeln!(
            output,
            "{indent}    public static let typeName = \"{type_name}\""
        );
        let inner = format!("{indent}    ");
        let mut nested: Vec<Nested> = Vec::new();
        let mut spread_names = spread_accessor_names(selections, type_name);
        self.accessors(
            output,
            type_name,
            type_is_abstract,
            selections,
            &inner,
            &mut nested,
            &mut spread_names,
        );
        if is_fragment_root && let Some(refetch) = context.refetch {
            self.refetch_members(output, refetch, context, &inner);
        }
        if let Some(connection) = connection {
            self.connection_members(output, connection, type_name, selections, context, &inner);
        }
        for child in nested {
            output.push('\n');
            self.lens_struct(
                output,
                &child.name,
                &child.type_name,
                child.is_abstract,
                &child.selections,
                &inner,
                context,
                child.connection.as_ref(),
                false,
            );
        }
        let _ = writeln!(output, "{indent}}}");
    }

    /// The `@refetchable` surface of a fragment lens: the descriptor of its
    /// query and `refetch()`.
    fn refetch_members(
        &mut self,
        output: &mut String,
        refetch: &RefetchPlan,
        context: Context<'_>,
        indent: &str,
    ) {
        let option = |value: &Option<String>| match value {
            Some(name) => swift_literal(name),
            None => "nil".to_string(),
        };
        let pagination = refetch.connection.as_ref();
        let _ = writeln!(
            output,
            "{indent}/// How the fragment is fetched again: `{}` with the lens's variables.",
            refetch.operation
        );
        let _ = writeln!(
            output,
            "{indent}public static let refetchable = Baton.Refetch(variables: [{}], identifier: {}, first: {}, after: {}, last: {}, before: {})",
            refetch
                .variables
                .iter()
                .map(|name| swift_literal(name))
                .collect::<Vec<_>>()
                .join(", "),
            option(&refetch.identifier),
            option(&pagination.and_then(|p| p.first.clone())),
            option(&pagination.and_then(|p| p.after.clone())),
            option(&pagination.and_then(|p| p.last.clone())),
            option(&pagination.and_then(|p| p.before.clone())),
        );
        let _ = writeln!(
            output,
            "{indent}/// Fetches the fragment again through `{}` with its current variables; the records update in place.",
            refetch.operation
        );
        let _ = writeln!(
            output,
            "{indent}@MainActor public func refetch() async throws {{ try await anchor.refetch({}.self, {}.refetchable) }}",
            refetch.operation, context.owner
        );
    }

    /// The connection surface of a lens over a `@connection` field: Relay's
    /// state read from the store, `nodes`, and pagination when the fragment is
    /// refetchable.
    fn connection_members(
        &mut self,
        output: &mut String,
        connection: &ConnectionPlan,
        type_name: &str,
        selections: &[SelectionPlan],
        context: Context<'_>,
        indent: &str,
    ) {
        self.types.insert(connection.edge_type.clone());
        self.types.insert(connection.page_info_type.clone());
        let _ = writeln!(
            output,
            "{indent}/// The connection's slots: edges, nodes, cursors and the page info, for the store's merge and the state below."
        );
        let _ = writeln!(
            output,
            "{indent}public static let connection = Baton.ConnectionSlots(connection: Types.{type_name}, edge: Types.{}, pageInfo: Types.{})",
            connection.edge_type, connection.page_info_type
        );
        if let Some((edges, node)) = edge_node_properties(selections) {
            let _ = writeln!(
                output,
                "{indent}/// The edges' nodes, in order, without nulls."
            );
            let _ = writeln!(
                output,
                "{indent}@MainActor public var nodes: [{edges}.{node}] {{ anchor.nodes(Self.connection).map({edges}.{node}.init(anchor:)) }}",
                edges = capitalize(&edges),
                node = capitalize(&node)
            );
        }
        let _ = writeln!(
            output,
            "{indent}/// Whether the server has edges after the last one, from the merged `pageInfo`."
        );
        let _ = writeln!(
            output,
            "{indent}@MainActor public var hasNext: Bool {{ anchor.hasNext(Self.connection) }}"
        );
        let _ = writeln!(
            output,
            "{indent}@MainActor public var hasPrevious: Bool {{ anchor.hasPrevious(Self.connection) }}"
        );
        let _ = writeln!(
            output,
            "{indent}@MainActor public var isLoadingNext: Bool {{ anchor.isLoadingNext(Self.connection) }}"
        );
        let _ = writeln!(
            output,
            "{indent}@MainActor public var isLoadingPrevious: Bool {{ anchor.isLoadingPrevious(Self.connection) }}"
        );
        let _ = writeln!(
            output,
            "{indent}/// Relay's connection id, for the `connections` argument of the edge directives."
        );
        let _ = writeln!(
            output,
            "{indent}@MainActor public var connectionID: String {{ anchor.record.key }}"
        );

        let Some(refetch) = context.refetch else {
            return;
        };
        let Some(pagination) = refetch.connection.as_ref() else {
            return;
        };
        let default_count = |variable: &Option<String>| -> String {
            variable
                .as_ref()
                .and_then(|name| context.arguments.iter().find(|a| &a.name == name))
                .and_then(|definition| match &definition.default_value {
                    Some(ConstantPlan::Int(count)) => Some(format!(" = {count}")),
                    _ => None,
                })
                .unwrap_or_default()
        };
        if pagination.first.is_some() && pagination.after.is_some() {
            let _ = writeln!(
                output,
                "{indent}/// Fetches the next `count` edges through `{}` and appends them; a no-op while loading or at the end.",
                refetch.operation
            );
            let _ = writeln!(
                output,
                "{indent}@MainActor public func loadNext(_ count: Int{}) async throws {{ try await anchor.loadNext({}.self, Self.connection, {}.refetchable, count: count) }}",
                default_count(&pagination.first),
                refetch.operation,
                context.owner
            );
        }
        if pagination.last.is_some() && pagination.before.is_some() {
            let _ = writeln!(
                output,
                "{indent}/// Fetches the previous `count` edges through `{}` and prepends them; a no-op while loading or at the start.",
                refetch.operation
            );
            let _ = writeln!(
                output,
                "{indent}@MainActor public func loadPrevious(_ count: Int{}) async throws {{ try await anchor.loadPrevious({}.self, Self.connection, {}.refetchable, count: count) }}",
                default_count(&pagination.last),
                refetch.operation,
                context.owner
            );
        }
    }

    #[allow(clippy::too_many_arguments)]
    fn accessors(
        &mut self,
        output: &mut String,
        type_name: &str,
        type_is_abstract: bool,
        selections: &[SelectionPlan],
        indent: &str,
        nested: &mut Vec<Nested>,
        spread_names: &mut BTreeMap<String, String>,
    ) {
        for selection in selections {
            match selection {
                SelectionPlan::Scalar {
                    name,
                    alias,
                    base_kind,
                    non_null,
                    list,
                    storage_key,
                    ..
                } => {
                    if name == "__typename" {
                        continue;
                    }
                    let argument = self.read_argument(type_name, type_is_abstract, storage_key);
                    let property = alias.clone().unwrap_or_else(|| name.clone());
                    let (reader, swift_type) = scalar_reader(*base_kind, *list);
                    if *non_null {
                        let _ = writeln!(
                            output,
                            "{indent}@MainActor public var {}: {} {{ anchor.required{}({argument}) }}",
                            escape(&property),
                            swift_type,
                            capitalize(reader)
                        );
                    } else {
                        let _ = writeln!(
                            output,
                            "{indent}@MainActor public var {}: {}? {{ anchor.{reader}({argument}) }}",
                            escape(&property),
                            swift_type
                        );
                    }
                }
                SelectionPlan::Linked {
                    name,
                    alias,
                    base_type,
                    non_null,
                    plural,
                    is_abstract,
                    storage_key,
                    lookup,
                    connection,
                    selections: child,
                    ..
                } => {
                    let argument = self.read_argument(type_name, type_is_abstract, storage_key);
                    let property = alias.clone().unwrap_or_else(|| name.clone());
                    let nested_name = unique_nested_name(&property, nested);
                    self.types.insert(base_type.clone());
                    let lookup_argument = lookup
                        .as_ref()
                        .map(|lookup| {
                            format!(", lookup: {}", lookup_expression(lookup, storage_key))
                        })
                        .unwrap_or_default();
                    if *plural {
                        if *non_null {
                            let _ = writeln!(
                                output,
                                "{indent}@MainActor public var {}: Baton.List<{nested_name}> {{ anchor.requiredList({argument}) }}",
                                escape(&property)
                            );
                        } else {
                            let _ = writeln!(
                                output,
                                "{indent}@MainActor public var {}: Baton.List<{nested_name}>? {{ anchor.list({argument}) }}",
                                escape(&property)
                            );
                        }
                    } else if *non_null {
                        let _ = writeln!(
                            output,
                            "{indent}@MainActor public var {}: {nested_name} {{ {nested_name}(anchor: anchor.requiredLinked({argument}, type: Types.{base_type}{lookup_argument})) }}",
                            escape(&property)
                        );
                    } else {
                        let _ = writeln!(
                            output,
                            "{indent}@MainActor public var {}: {nested_name}? {{ anchor.linked({argument}{lookup_argument}).map({nested_name}.init(anchor:)) }}",
                            escape(&property)
                        );
                    }
                    nested.push(Nested {
                        name: nested_name,
                        type_name: base_type.clone(),
                        is_abstract: *is_abstract,
                        selections: child.clone(),
                        connection: connection.clone(),
                    });
                }
                SelectionPlan::Spread {
                    fragment,
                    type_condition,
                    arguments,
                } => {
                    let accessor = spread_names
                        .get(fragment)
                        .cloned()
                        .unwrap_or_else(|| lower_camel(fragment));
                    self.spread_accessor(
                        output,
                        &accessor,
                        fragment,
                        arguments,
                        type_name,
                        type_is_abstract,
                        type_condition,
                        indent,
                    );
                }
                SelectionPlan::Inline {
                    type_condition,
                    alias,
                    selections: child,
                } => {
                    if let Some(alias) = alias {
                        // `@alias(as:)`: a spread keeps its lens under the given
                        // name; any other selection becomes a nested lens.
                        if let [
                            SelectionPlan::Spread {
                                fragment,
                                type_condition: spread_condition,
                                arguments,
                            },
                        ] = child.as_slice()
                        {
                            self.spread_accessor(
                                output,
                                alias,
                                fragment,
                                arguments,
                                type_name,
                                type_is_abstract,
                                spread_condition,
                                indent,
                            );
                            continue;
                        }
                        let nested_name = unique_nested_name(alias, nested);
                        let condition_type = type_condition.as_deref().unwrap_or(type_name);
                        match type_condition {
                            Some(condition) if condition != type_name => {
                                self.types.insert(condition.clone());
                                let _ = writeln!(
                                    output,
                                    "{indent}@MainActor public var {}: {nested_name}? {{ anchor.record.is(Types.{condition}) ? {nested_name}(anchor: anchor) : nil }}",
                                    escape(alias)
                                );
                            }
                            _ => {
                                let _ = writeln!(
                                    output,
                                    "{indent}@MainActor public var {}: {nested_name} {{ {nested_name}(anchor: anchor) }}",
                                    escape(alias)
                                );
                            }
                        }
                        nested.push(Nested {
                            name: nested_name,
                            type_name: condition_type.to_string(),
                            is_abstract: false,
                            selections: child.clone(),
                            connection: None,
                        });
                        continue;
                    }
                    match type_condition {
                        Some(condition) if condition != type_name => {
                            let nested_name = format!("As{condition}");
                            self.types.insert(condition.clone());
                            let _ = writeln!(
                                output,
                                "{indent}@MainActor public var as{condition}: {nested_name}? {{ anchor.record.is(Types.{condition}) ? {nested_name}(anchor: anchor) : nil }}"
                            );
                            nested.push(Nested {
                                name: nested_name,
                                type_name: condition.clone(),
                                is_abstract: false,
                                selections: child.clone(),
                                connection: None,
                            });
                        }
                        _ => self.accessors(
                            output,
                            type_name,
                            type_is_abstract,
                            child,
                            indent,
                            nested,
                            spread_names,
                        ),
                    }
                }
                SelectionPlan::Condition {
                    selections: child, ..
                } => {
                    // `@include` / `@skip`: read as if present; a skipped field reads as missing.
                    self.accessors(
                        output,
                        type_name,
                        type_is_abstract,
                        child,
                        indent,
                        nested,
                        spread_names,
                    );
                }
            }
        }
    }

    /// A spread's accessor. The child's scope is the parent's variables with
    /// the fragment's `@argumentDefinitions` bound: the passed argument, else
    /// the default, else null.
    #[allow(clippy::too_many_arguments)]
    fn spread_accessor(
        &mut self,
        output: &mut String,
        accessor: &str,
        fragment: &str,
        arguments: &[crate::pipeline::ArgumentPlan],
        type_name: &str,
        type_is_abstract: bool,
        type_condition: &str,
        indent: &str,
    ) {
        let definitions = self
            .fragment_arguments
            .get(fragment)
            .cloned()
            .unwrap_or_default();
        let anchor = if definitions.is_empty() {
            "anchor".to_string()
        } else {
            let bindings: Vec<String> = definitions
                .iter()
                .map(|definition| {
                    let value = arguments
                        .iter()
                        .find(|argument| argument.name == definition.name)
                        .map(|argument| argument_expression(&argument.value))
                        .or_else(|| definition.default_value.as_ref().map(variable_literal))
                        .unwrap_or_else(|| ".null".to_string());
                    format!("{}: {value}", swift_literal(&definition.name))
                })
                .collect();
            format!("anchor.binding([{}])", bindings.join(", "))
        };
        if !type_is_abstract || type_condition == type_name {
            let _ = writeln!(
                output,
                "{indent}@MainActor public var {}: {fragment} {{ {fragment}(anchor: {anchor}) }}",
                escape(accessor)
            );
        } else {
            self.types.insert(type_condition.to_string());
            let _ = writeln!(
                output,
                "{indent}@MainActor public var {}: {fragment}? {{ anchor.record.is(Types.{type_condition}) ? {fragment}(anchor: {anchor}) : nil }}",
                escape(accessor)
            );
        }
    }

    /// The argument a lens accessor passes: a static slot on a concrete type, or
    /// a storage key resolved against the record's own type when the selection
    /// is on an interface or union.
    fn read_argument(
        &mut self,
        type_name: &str,
        type_is_abstract: bool,
        storage_key: &str,
    ) -> String {
        if type_is_abstract {
            self.types.insert(type_name.to_string());
            let slot = SlotRef {
                type_name: type_name.to_string(),
                storage_key: storage_key.to_string(),
            };
            if slot.is_dynamic() {
                format!(
                    "key: {}",
                    dynamic_key_expression(storage_key, "anchor.variables")
                )
            } else {
                format!("key: {}", swift_literal(storage_key))
            }
        } else {
            self.slot(type_name, storage_key)
        }
    }

    /// Writes a `Baton.Selection(...)` expression for the normalization plan.
    fn selection_plan(
        &mut self,
        output: &mut String,
        type_name: &str,
        has_id: bool,
        is_abstract: bool,
        selections: &[SelectionPlan],
        depth: usize,
    ) {
        self.types.insert(type_name.to_string());
        let pad = "    ".repeat(depth);
        let _ = write!(
            output,
            "Baton.Selection(type: Types.{type_name}, hasID: {has_id}, abstract: {is_abstract}, fields: ["
        );
        let mut any = false;
        for selection in flatten(selections) {
            any = true;
            let _ = write!(output, "\n{pad}    ");
            match selection {
                SelectionPlan::Scalar {
                    name,
                    alias,
                    base_kind,
                    list,
                    storage_key,
                    handle,
                    ..
                } => {
                    let slot = self.plan_key(type_name, storage_key);
                    let kind = match base_kind {
                        TypeKind::Int => "int",
                        TypeKind::Float => "double",
                        TypeKind::Boolean => "bool",
                        TypeKind::String | TypeKind::Id | TypeKind::Enum => "string",
                        _ => "custom",
                    };
                    let handle_argument = handle
                        .as_ref()
                        .map(|handle| format!(", handle: {}", self.handle_expression(handle)))
                        .unwrap_or_default();
                    let _ = write!(
                        output,
                        ".scalar(\"{}\", key: {slot}, kind: .{kind}, list: {list}{handle_argument}),",
                        alias.as_deref().unwrap_or(name)
                    );
                }
                SelectionPlan::Linked {
                    name,
                    alias,
                    base_type,
                    plural,
                    has_id,
                    is_abstract,
                    storage_key,
                    lookup,
                    connection,
                    handle,
                    selections: child,
                    ..
                } => {
                    let slot = self.plan_key(type_name, storage_key);
                    let lookup_argument = lookup
                        .as_ref()
                        .map(|lookup| {
                            format!(", lookup: {}", lookup_expression(lookup, storage_key))
                        })
                        .unwrap_or_default();
                    let connection_argument = connection
                        .as_ref()
                        .map(|connection| {
                            format!(
                                ", connection: {}",
                                self.connection_expression(type_name, base_type, connection)
                            )
                        })
                        .unwrap_or_default();
                    let handle_argument = handle
                        .as_ref()
                        .map(|handle| format!(", handle: {}", self.handle_expression(handle)))
                        .unwrap_or_default();
                    let _ = write!(
                        output,
                        ".linked(\"{}\", key: {slot}, plural: {plural}{lookup_argument}{connection_argument}{handle_argument}, selection: ",
                        alias.as_deref().unwrap_or(name)
                    );
                    self.selection_plan(output, base_type, *has_id, *is_abstract, child, depth + 1);
                    output.push_str("),");
                }
                _ => unreachable!("flatten removes nested kinds"),
            }
        }
        if any {
            let _ = write!(output, "\n{pad}");
        }
        output.push_str("])");
    }

    /// The plan's description of a connection: the client key on the parent
    /// type, the slots of the connection, edge and page info types, and the
    /// cursor arguments that pick the merge mode.
    fn connection_expression(
        &mut self,
        parent_type: &str,
        connection_type: &str,
        connection: &ConnectionPlan,
    ) -> String {
        let key = self.plan_key(parent_type, &connection.storage_key);
        self.types.insert(connection.edge_type.clone());
        self.types.insert(connection.page_info_type.clone());
        let cursor = |value: &Option<ArgumentValuePlan>, label: &str| match value {
            Some(ArgumentValuePlan::Variable(name)) => {
                format!(", {label}: .variable({})", swift_literal(name))
            }
            Some(ArgumentValuePlan::Constant(_)) => format!(", {label}: .literal"),
            None => String::new(),
        };
        format!(
            "Baton.ConnectionPlan(key: {key}, slots: Baton.ConnectionSlots(connection: Types.{connection_type}, edge: Types.{}, pageInfo: Types.{}){}{})",
            connection.edge_type,
            connection.page_info_type,
            cursor(&connection.after, "after"),
            cursor(&connection.before, "before")
        )
    }

    /// The plan's description of an edge directive.
    fn handle_expression(&mut self, handle: &HandlePlan) -> String {
        let connections = match &handle.connections {
            Some(ArgumentValuePlan::Variable(name)) => {
                format!(", connections: .variable({})", swift_literal(name))
            }
            Some(ArgumentValuePlan::Constant(ConstantPlan::List(items))) => format!(
                ", connections: .literal([{}])",
                items
                    .iter()
                    .map(|item| match item {
                        ConstantPlan::String(text) => swift_literal(text),
                        other => swift_literal(&constant_text(other)),
                    })
                    .collect::<Vec<_>>()
                    .join(", ")
            ),
            Some(ArgumentValuePlan::Constant(other)) => {
                format!(
                    ", connections: .literal([{}])",
                    swift_literal(&constant_text(other))
                )
            }
            None => String::new(),
        };
        let edge_type = match &handle.edge_type_name {
            Some(name) => {
                self.types.insert(name.clone());
                format!(", edgeType: Types.{name}")
            }
            None => String::new(),
        };
        format!(
            "Baton.Handle(kind: .{}{connections}{edge_type})",
            handle.kind
        )
    }

    /// Writes the optimistic-response builder tree for a mutation: one struct
    /// per selection set, every field optional, rendering to JSON.
    fn optimistic_builder(
        &mut self,
        output: &mut String,
        name: &str,
        selections: &[SelectionPlan],
        indent: &str,
    ) {
        let _ = writeln!(
            output,
            "{indent}/// A partial response to show before the server answers; absent fields leave the store untouched."
        );
        let _ = writeln!(output, "{indent}public struct {name}: Sendable {{");
        let inner = format!("{indent}    ");
        let flat = flatten(selections);
        let mut nested: Vec<(String, Vec<SelectionPlan>)> = Vec::new();
        let mut parameters: Vec<String> = Vec::new();
        let mut assignments: Vec<String> = Vec::new();
        let mut renders: Vec<String> = Vec::new();
        for selection in &flat {
            match selection {
                SelectionPlan::Scalar {
                    name,
                    alias,
                    base_kind,
                    list,
                    ..
                } => {
                    let property = alias.clone().unwrap_or_else(|| name.clone());
                    let (_, swift_type) = scalar_reader(*base_kind, *list);
                    let _ = writeln!(
                        output,
                        "{inner}public var {}: {swift_type}?",
                        escape(&property)
                    );
                    parameters.push(format!("{}: {swift_type}? = nil", escape(&property)));
                    assignments.push(format!("self.{0} = {0}", escape(&property)));
                    renders.push(format!(
                        "if let {0} {{ fields[\"{1}\"] = Baton.Variable({0}) }}",
                        escape(&property),
                        property
                    ));
                }
                SelectionPlan::Linked {
                    name,
                    alias,
                    plural,
                    selections: child,
                    ..
                } => {
                    let property = alias.clone().unwrap_or_else(|| name.clone());
                    let mut nested_name = capitalize(&property);
                    let mut counter = 2;
                    while nested.iter().any(|(existing, _)| existing == &nested_name) {
                        nested_name = format!("{}{counter}", capitalize(&property));
                        counter += 1;
                    }
                    let swift_type = if *plural {
                        format!("[{nested_name}]")
                    } else {
                        nested_name.clone()
                    };
                    let _ = writeln!(
                        output,
                        "{inner}public var {}: {swift_type}?",
                        escape(&property)
                    );
                    parameters.push(format!("{}: {swift_type}? = nil", escape(&property)));
                    assignments.push(format!("self.{0} = {0}", escape(&property)));
                    if *plural {
                        renders.push(format!(
                            "if let {0} {{ fields[\"{1}\"] = .list({0}.map(\\.variable)) }}",
                            escape(&property),
                            property
                        ));
                    } else {
                        renders.push(format!(
                            "if let {0} {{ fields[\"{1}\"] = {0}.variable }}",
                            escape(&property),
                            property
                        ));
                    }
                    nested.push((nested_name, child.clone()));
                }
                _ => unreachable!("flatten removes nested kinds"),
            }
        }
        let _ = writeln!(output, "{inner}public init({}) {{", parameters.join(", "));
        for assignment in &assignments {
            let _ = writeln!(output, "{inner}    {assignment}");
        }
        let _ = writeln!(output, "{inner}}}");
        let _ = writeln!(output, "{inner}public var variable: Baton.Variable {{");
        let _ = writeln!(
            output,
            "{inner}    var fields: [String: Baton.Variable] = [:]"
        );
        for render in &renders {
            let _ = writeln!(output, "{inner}    {render}");
        }
        let _ = writeln!(output, "{inner}    return .object(fields)");
        let _ = writeln!(output, "{inner}}}");
        for (nested_name, child) in nested {
            output.push('\n');
            self.optimistic_builder(output, &nested_name, &child, &inner);
        }
        let _ = writeln!(output, "{indent}}}");
    }

    fn slot(&mut self, type_name: &str, storage_key: &str) -> String {
        let slot = SlotRef {
            type_name: type_name.to_string(),
            storage_key: storage_key.to_string(),
        };
        let expression = slot.expression();
        self.slots.insert(slot);
        self.types.insert(type_name.to_string());
        expression
    }

    /// The key expression inside a plan: a fixed slot or a dynamic template.
    fn plan_key(&mut self, type_name: &str, storage_key: &str) -> String {
        let slot = SlotRef {
            type_name: type_name.to_string(),
            storage_key: storage_key.to_string(),
        };
        if slot.is_dynamic() {
            let parts = key_parts(storage_key)
                .into_iter()
                .map(|part| match part {
                    KeyPart::Literal(text) => format!(".literal({})", swift_literal(&text)),
                    KeyPart::Variable(name) => format!(".variable(\"{name}\")"),
                })
                .collect::<Vec<_>>()
                .join(", ");
            self.slots.insert(slot);
            format!(".dynamic([{parts}])")
        } else {
            let expression = format!(".fixed(Slots.{})", slot.identifier());
            self.slots.insert(slot);
            expression
        }
    }
}

/// The response keys of the `edges` field and of its `node`, when the
/// connection selects them and does not select a `nodes` field itself.
fn edge_node_properties(selections: &[SelectionPlan]) -> Option<(String, String)> {
    let flat = flatten(selections);
    let has_nodes_field = flat.iter().any(|selection| match selection {
        SelectionPlan::Scalar { name, alias, .. } | SelectionPlan::Linked { name, alias, .. } => {
            alias.as_deref().unwrap_or(name) == "nodes"
        }
        _ => false,
    });
    if has_nodes_field {
        return None;
    }
    let edges = flat.iter().find_map(|selection| match selection {
        SelectionPlan::Linked {
            name,
            alias,
            selections,
            ..
        } if name == "edges" && alias.is_none() => Some((name.clone(), selections)),
        _ => None,
    })?;
    let node = flatten(edges.1)
        .iter()
        .find_map(|selection| match selection {
            SelectionPlan::Linked { name, alias, .. } if name == "node" && alias.is_none() => {
                Some(name.clone())
            }
            _ => None,
        })?;
    Some((edges.0, node))
}

fn parameter_list(variables: &[VariablePlan]) -> String {
    variables
        .iter()
        .map(|variable| {
            let default = if variable.non_null { "" } else { " = nil" };
            format!("{}: {}{}", variable.name, variable_type(variable), default)
        })
        .collect::<Vec<_>>()
        .join(", ")
}

/// Normalization plans are flat: inline fragments and conditions are folded
/// into their parent; spreads were inlined by the compiler already.
fn flatten(selections: &[SelectionPlan]) -> Vec<&SelectionPlan> {
    let mut result = Vec::new();
    for selection in selections {
        match selection {
            SelectionPlan::Inline { selections, .. }
            | SelectionPlan::Condition { selections, .. } => {
                result.extend(flatten(selections));
            }
            SelectionPlan::Spread { .. } => {}
            other => result.push(other),
        }
    }
    result
}

enum KeyPart {
    Literal(String),
    Variable(String),
}

/// Splits `characters(page:$page,filter:$filter)` into literal and variable parts.
fn key_parts(storage_key: &str) -> Vec<KeyPart> {
    let mut parts = Vec::new();
    let mut literal = String::new();
    let mut characters = storage_key.chars().peekable();
    while let Some(character) = characters.next() {
        if character == '$' {
            if !literal.is_empty() {
                parts.push(KeyPart::Literal(std::mem::take(&mut literal)));
            }
            let mut name = String::new();
            while let Some(next) = characters.peek() {
                if next.is_alphanumeric() || *next == '_' {
                    name.push(*next);
                    characters.next();
                } else {
                    break;
                }
            }
            parts.push(KeyPart::Variable(name));
        } else {
            literal.push(character);
        }
    }
    if !literal.is_empty() {
        parts.push(KeyPart::Literal(literal));
    }
    parts
}

/// A Swift string literal for text that may contain quotes or backslashes
/// (storage keys carry JSON-rendered arguments).
fn swift_literal(text: &str) -> String {
    let mut output = String::with_capacity(text.len() + 2);
    output.push('"');
    for character in text.chars() {
        match character {
            '"' => output.push_str("\\\""),
            '\\' => output.push_str("\\\\"),
            '\n' => output.push_str("\\n"),
            other => output.push(other),
        }
    }
    output.push('"');
    output
}

/// A Swift expression building the storage key from `variables`.
fn dynamic_key_expression(storage_key: &str, variables: &str) -> String {
    key_parts(storage_key)
        .into_iter()
        .map(|part| match part {
            KeyPart::Literal(text) => swift_literal(&text),
            KeyPart::Variable(name) => format!("{variables}.render(\"{name}\")"),
        })
        .collect::<Vec<_>>()
        .join(" + ")
}

/// A `Baton.Variable` expression for a constant.
fn variable_literal(constant: &ConstantPlan) -> String {
    match constant {
        ConstantPlan::Null => ".null".to_string(),
        ConstantPlan::Bool(boolean) => format!(".bool({boolean})"),
        ConstantPlan::Int(int) => format!(".int({int})"),
        ConstantPlan::Float(float) => format!(".double({float:?})"),
        ConstantPlan::String(text) => format!(".string({})", swift_literal(text)),
        ConstantPlan::List(items) => format!(
            ".list([{}])",
            items
                .iter()
                .map(variable_literal)
                .collect::<Vec<_>>()
                .join(", ")
        ),
        ConstantPlan::Object(fields) if fields.is_empty() => ".object([:])".to_string(),
        ConstantPlan::Object(fields) => format!(
            ".object([{}])",
            fields
                .iter()
                .map(|(name, value)| format!(
                    "{}: {}",
                    swift_literal(name),
                    variable_literal(value)
                ))
                .collect::<Vec<_>>()
                .join(", ")
        ),
    }
}

/// A constant's text, for the rare constant list of connection ids.
fn constant_text(constant: &ConstantPlan) -> String {
    match constant {
        ConstantPlan::Null => "null".to_string(),
        ConstantPlan::Bool(boolean) => boolean.to_string(),
        ConstantPlan::Int(int) => int.to_string(),
        ConstantPlan::Float(float) => float.to_string(),
        ConstantPlan::String(text) => text.clone(),
        ConstantPlan::List(items) => format!(
            "[{}]",
            items
                .iter()
                .map(constant_text)
                .collect::<Vec<_>>()
                .join(",")
        ),
        ConstantPlan::Object(fields) => format!(
            "{{{}}}",
            fields
                .iter()
                .map(|(name, value)| format!("{name}:{}", constant_text(value)))
                .collect::<Vec<_>>()
                .join(",")
        ),
    }
}

/// A spread argument as the parent lens binds it: the parent's variable, or
/// a constant.
fn argument_expression(value: &ArgumentValuePlan) -> String {
    match value {
        ArgumentValuePlan::Variable(name) => format!("anchor.variables[{}]", swift_literal(name)),
        ArgumentValuePlan::Constant(constant) => variable_literal(constant),
    }
}

/// The lookup: the entity type (or none, for an id across types) and the
/// argument's value, a variable or a literal in the storage key.
fn lookup_expression(lookup: &LookupPlan, storage_key: &str) -> String {
    let argument_prefix = format!("{}:", lookup.argument);
    let inside = storage_key
        .split_once('(')
        .map(|(_, rest)| rest.trim_end_matches(')'))
        .unwrap_or("");
    let value = inside
        .split(',')
        .find_map(|pair| pair.strip_prefix(&argument_prefix))
        .unwrap_or("");
    let type_expression = match &lookup.type_name {
        Some(type_name) => format!("Types.{type_name}"),
        None => "nil".to_string(),
    };
    if let Some(variable) = value.strip_prefix('$') {
        format!("Baton.Lookup(type: {type_expression}, key: .variable(\"{variable}\"))")
    } else {
        format!(
            "Baton.Lookup(type: {type_expression}, key: .literal(\"{}\"))",
            value.trim_matches('"')
        )
    }
}

fn scalar_reader(kind: TypeKind, list: bool) -> (&'static str, String) {
    let (reader, swift) = match kind {
        TypeKind::Int => ("int", "Int"),
        TypeKind::Float => ("double", "Double"),
        TypeKind::Boolean => ("bool", "Bool"),
        _ => ("string", "String"),
    };
    if list {
        (
            match reader {
                "int" => "ints",
                "double" => "doubles",
                "bool" => "bools",
                _ => "strings",
            },
            format!("[{swift}]"),
        )
    } else {
        (reader, swift.to_string())
    }
}

fn variable_type(variable: &VariablePlan) -> String {
    let base = match variable.base_kind {
        TypeKind::Int => "Int",
        TypeKind::Float => "Double",
        TypeKind::Boolean => "Bool",
        TypeKind::String | TypeKind::Id | TypeKind::Enum | TypeKind::CustomScalar => "String",
        _ => "Baton.Variable",
    };
    let shape = if variable.list {
        format!("[{base}]")
    } else {
        base.to_string()
    };
    if variable.non_null {
        shape
    } else {
        format!("{shape}?")
    }
}

/// The spreads a lens exposes under derived names: its own, and those inside
/// inline fragments and conditions that flatten into it (an inline fragment
/// on the lens's own type, as `@alias` produces; one on another type is a
/// nested lens with its own table). Spreads under an explicit `@alias(as:)`
/// are named by it and left out.
fn collect_spreads<'a>(selections: &'a [SelectionPlan], type_name: &str, into: &mut Vec<&'a str>) {
    for selection in selections {
        match selection {
            SelectionPlan::Spread { fragment, .. } => into.push(fragment.as_str()),
            SelectionPlan::Inline {
                type_condition,
                alias,
                selections: child,
            } => {
                if alias.is_some() {
                    continue;
                }
                match type_condition {
                    Some(condition) if condition != type_name => {}
                    _ => collect_spreads(child, type_name, into),
                }
            }
            SelectionPlan::Condition {
                selections: child, ..
            } => collect_spreads(child, type_name, into),
            _ => {}
        }
    }
}

/// Default spread accessor names: the fragment's owner prefix in lower camel
/// case, falling back to the whole name when two spreads would collide.
fn spread_accessor_names(
    selections: &[SelectionPlan],
    type_name: &str,
) -> BTreeMap<String, String> {
    let mut fragments: Vec<&str> = Vec::new();
    collect_spreads(selections, type_name, &mut fragments);
    let mut by_prefix: BTreeMap<String, Vec<&str>> = BTreeMap::new();
    for fragment in &fragments {
        let prefix = fragment.split('_').next().unwrap_or(fragment);
        by_prefix
            .entry(lower_camel(prefix))
            .or_default()
            .push(fragment);
    }
    let mut names = BTreeMap::new();
    for (prefix, owners) in by_prefix {
        if owners.len() == 1 {
            names.insert(owners[0].to_string(), prefix);
        } else {
            for owner in owners {
                names.insert(owner.to_string(), lower_camel(owner));
            }
        }
    }
    names
}

fn unique_nested_name(property: &str, nested: &[Nested]) -> String {
    let base = capitalize(property);
    let mut candidate = base.clone();
    let mut counter = 2;
    while nested.iter().any(|child| child.name == candidate) {
        candidate = format!("{base}{counter}");
        counter += 1;
    }
    candidate
}

fn capitalize(text: &str) -> String {
    let mut characters = text.chars();
    match characters.next() {
        Some(first) => first.to_uppercase().collect::<String>() + characters.as_str(),
        None => String::new(),
    }
}

fn lower_camel(text: &str) -> String {
    let mut characters = text.chars();
    match characters.next() {
        Some(first) => first.to_lowercase().collect::<String>() + characters.as_str(),
        None => String::new(),
    }
}

/// Escapes a property name that is a Swift keyword.
fn escape(name: &str) -> String {
    const KEYWORDS: &[&str] = &[
        "Type",
        "Protocol",
        "self",
        "Self",
        "init",
        "deinit",
        "subscript",
        "class",
        "struct",
        "enum",
        "func",
        "var",
        "let",
        "import",
        "extension",
        "operator",
        "static",
        "default",
        "case",
        "switch",
        "if",
        "else",
        "for",
        "in",
        "while",
        "repeat",
        "return",
        "break",
        "continue",
        "where",
        "is",
        "as",
        "try",
        "throw",
        "throws",
        "guard",
        "defer",
        "do",
        "catch",
        "true",
        "false",
        "nil",
        "super",
        "internal",
        "private",
        "public",
        "fileprivate",
        "open",
        "inout",
        "typealias",
        "associatedtype",
        "protocol",
        "some",
        "any",
    ];
    if KEYWORDS.contains(&name) {
        format!("`{name}`")
    } else {
        name.to_string()
    }
}
