//! The Swift emitter: lens types, operation values, plan tables, mutation
//! actions with their optimistic builders, and the shared file of interned
//! types and slots. Everything here reads the plan IR only.
//!
//! Output per host file `X.swift` is `X.baton.swift`; the per-target
//! `Baton.baton.swift` carries `Types` and `Slots`.

use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;

use crate::pipeline::{
    FragmentPlan, LookupPlan, OperationPlan, Plan, SelectionPlan, TypeKind, VariablePlan,
};

/// Generated Swift, grouped by the source file that declared the documents.
pub struct Output {
    pub files: BTreeMap<String, String>,
    pub shared: String,
}

/// A slot the generated code refers to: a parent type and a storage key.
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct SlotRef {
    type_name: String,
    storage_key: String,
}

impl SlotRef {
    fn is_dynamic(&self) -> bool {
        self.storage_key.contains('$')
    }

    /// `Character_name`, or `Query_characters_1a2b3c` when the key has arguments.
    fn identifier(&self) -> String {
        let field = self
            .storage_key
            .split('(')
            .next()
            .unwrap_or(&self.storage_key);
        if field == self.storage_key {
            format!("{}_{}", self.type_name, field)
        } else {
            let digest = format!("{:x}", md5::compute(self.storage_key.as_bytes()));
            format!("{}_{}_{}", self.type_name, field, &digest[..6])
        }
    }

    /// The Swift expression that yields the slot.
    fn expression(&self) -> String {
        if self.is_dynamic() {
            format!("Slots.{}(anchor.variables)", self.identifier())
        } else {
            format!("Slots.{}", self.identifier())
        }
    }
}

struct Emitter {
    slots: BTreeSet<SlotRef>,
    types: BTreeSet<String>,
}

/// A nested lens type still to be written: name, GraphQL type, abstractness, selections.
struct Nested {
    name: String,
    type_name: String,
    is_abstract: bool,
    selections: Vec<SelectionPlan>,
}

pub fn emit(plan: &Plan) -> Output {
    let mut emitter = Emitter {
        slots: BTreeSet::new(),
        types: BTreeSet::new(),
    };
    let mut files: BTreeMap<String, String> = BTreeMap::new();
    for fragment in &plan.fragments {
        let text = emitter.fragment(fragment);
        files
            .entry(fragment.source.clone())
            .or_default()
            .push_str(&text);
    }
    for operation in &plan.operations {
        let text = emitter.operation(operation);
        files
            .entry(operation.source.clone())
            .or_default()
            .push_str(&text);
    }
    for text in files.values_mut() {
        *text = format!("{HEADER}\n{text}");
    }
    Output {
        shared: emitter.shared(),
        files,
    }
}

const HEADER: &str = "// Generated by batonc. Do not edit.\nimport Baton\n";

impl Emitter {
    fn shared(&self) -> String {
        let mut output = String::new();
        output.push_str(HEADER);
        output.push('\n');
        output
            .push_str("/// Interned schema types used by this module's documents.\nenum Types {\n");
        for type_name in &self.types {
            let _ = writeln!(
                output,
                "    static let {type_name} = Baton.Registry.type(\"{type_name}\")"
            );
        }
        output.push_str(
            "}\n\n/// Interned storage keys used by this module's documents.\nenum Slots {\n",
        );
        for slot in &self.slots {
            if slot.is_dynamic() {
                let _ = writeln!(
                    output,
                    "    static func {}(_ variables: Baton.Variables) -> Baton.Slot {{\n        Baton.Registry.slot(Types.{}, {})\n    }}",
                    slot.identifier(),
                    slot.type_name,
                    dynamic_key_expression(&slot.storage_key, "variables")
                );
            } else {
                let _ = writeln!(
                    output,
                    "    static let {} = Baton.Registry.slot(Types.{}, {})",
                    slot.identifier(),
                    slot.type_name,
                    swift_literal(&slot.storage_key)
                );
            }
        }
        output.push_str("}\n");
        output
    }

    fn fragment(&mut self, fragment: &FragmentPlan) -> String {
        let mut output = String::new();
        let _ = writeln!(
            output,
            "/// Lens for `fragment {} on {}`.",
            fragment.name, fragment.type_condition
        );
        self.lens_struct(
            &mut output,
            &fragment.name,
            &fragment.type_condition,
            fragment.type_is_abstract,
            &fragment.reader,
            "",
        );
        output.push('\n');
        output
    }

    fn operation(&mut self, operation: &OperationPlan) -> String {
        let mut output = String::new();
        let _ = writeln!(
            output,
            "/// Operation value for `{} {}`.",
            operation.kind, operation.name
        );
        let _ = writeln!(
            output,
            "public struct {}: Baton.Operation {{",
            operation.name
        );
        for variable in &operation.variables {
            let _ = writeln!(
                output,
                "    public var {}: {}",
                variable.name,
                variable_type(variable)
            );
        }
        let _ = writeln!(
            output,
            "    public var resolution: Baton.OperationHandle<Self>? = nil\n"
        );
        let parameters = parameter_list(&operation.variables);
        let _ = writeln!(output, "    public init({parameters}) {{");
        for variable in &operation.variables {
            let _ = writeln!(output, "        self.{0} = {0}", variable.name);
        }
        output.push_str("    }\n\n");
        let _ = writeln!(
            output,
            "    public static let name = \"{}\"",
            operation.name
        );
        let _ = writeln!(
            output,
            "    public static let kind = Baton.OperationKind.{}",
            operation.kind
        );
        let _ = writeln!(
            output,
            "    public static let persistedID = \"{}\"",
            operation.id
        );
        let _ = writeln!(
            output,
            "    public static let text = #\"\"\"\n{}\n\"\"\"#\n",
            operation.text.trim_end()
        );
        output.push_str("    public var variables: Baton.Variables {\n        Baton.Variables([");
        if operation.variables.is_empty() {
            output.push(':');
        } else {
            let entries: Vec<String> = operation
                .variables
                .iter()
                .map(|variable| format!("\"{0}\": Baton.Variable({0})", variable.name))
                .collect();
            output.push_str(&entries.join(", "));
        }
        output.push_str("])\n    }\n\n");
        output.push_str("    public static func == (lhs: Self, rhs: Self) -> Bool {\n");
        if operation.variables.is_empty() {
            output.push_str("        true\n");
        } else {
            let comparisons: Vec<String> = operation
                .variables
                .iter()
                .map(|variable| format!("lhs.{0} == rhs.{0}", variable.name))
                .collect();
            let _ = writeln!(output, "        {}", comparisons.join(" && "));
        }
        output.push_str("    }\n\n    public func hash(into hasher: inout Hasher) {\n");
        for variable in &operation.variables {
            let _ = writeln!(output, "        hasher.combine({})", variable.name);
        }
        output.push_str("    }\n\n");

        // The normalization plan, as static data.
        self.types.insert(operation.root_type.clone());
        output.push_str("    public static let plan = Baton.Plan(root: ");
        self.selection_plan(
            &mut output,
            &operation.root_type,
            false,
            false,
            &operation.normalization,
            2,
        );
        output.push_str(")\n\n");

        // The root lens.
        self.lens_struct(
            &mut output,
            "Data",
            &operation.root_type,
            false,
            &operation.reader,
            "    ",
        );

        if operation.kind == "mutation" {
            output.push('\n');
            output.push_str("    public typealias Action = Baton.MutationAction<Self>\n\n");
            self.optimistic_builder(
                &mut output,
                "OptimisticResponse",
                &operation.normalization,
                "    ",
            );
        }
        output.push_str("}\n\n");

        if operation.kind == "mutation" {
            let parameters = parameter_list(&operation.variables);
            let separator = if operation.variables.is_empty() {
                ""
            } else {
                ", "
            };
            let arguments: Vec<String> = operation
                .variables
                .iter()
                .map(|variable| format!("{0}: {0}", variable.name))
                .collect();
            let _ = writeln!(
                output,
                "extension Baton.MutationAction where Op == {name} {{\n    /// Commits the mutation; the optimistic response, if any, shows at once and rebases until the server answers.\n    @MainActor @discardableResult\n    public func callAsFunction({parameters}{separator}optimistic: {name}.OptimisticResponse? = nil) async throws -> {name}.Data {{\n        try await commit({name}({args}), optimistic: optimistic?.variable)\n    }}\n}}\n",
                name = operation.name,
                args = arguments.join(", ")
            );
        }
        output
    }

    /// Writes a lens struct for a selection set on `type_name`.
    fn lens_struct(
        &mut self,
        output: &mut String,
        name: &str,
        type_name: &str,
        type_is_abstract: bool,
        selections: &[SelectionPlan],
        indent: &str,
    ) {
        self.types.insert(type_name.to_string());
        let _ = writeln!(output, "{indent}public struct {name}: Baton.Lens {{");
        let _ = writeln!(output, "{indent}    public let anchor: Baton.Anchor");
        let _ = writeln!(
            output,
            "{indent}    public init(anchor: Baton.Anchor) {{ self.anchor = anchor }}"
        );
        let _ = writeln!(
            output,
            "{indent}    public static let typeName = \"{type_name}\""
        );
        let inner = format!("{indent}    ");
        let mut nested: Vec<Nested> = Vec::new();
        let mut spread_names = spread_accessor_names(selections, type_name);
        self.accessors(
            output,
            type_name,
            type_is_abstract,
            selections,
            &inner,
            &mut nested,
            &mut spread_names,
        );
        for child in nested {
            output.push('\n');
            self.lens_struct(
                output,
                &child.name,
                &child.type_name,
                child.is_abstract,
                &child.selections,
                &inner,
            );
        }
        let _ = writeln!(output, "{indent}}}");
    }

    #[allow(clippy::too_many_arguments)]
    fn accessors(
        &mut self,
        output: &mut String,
        type_name: &str,
        type_is_abstract: bool,
        selections: &[SelectionPlan],
        indent: &str,
        nested: &mut Vec<Nested>,
        spread_names: &mut BTreeMap<String, String>,
    ) {
        for selection in selections {
            match selection {
                SelectionPlan::Scalar {
                    name,
                    alias,
                    base_kind,
                    non_null,
                    list,
                    storage_key,
                    ..
                } => {
                    if name == "__typename" {
                        continue;
                    }
                    let argument = self.read_argument(type_name, type_is_abstract, storage_key);
                    let property = alias.clone().unwrap_or_else(|| name.clone());
                    let (reader, swift_type) = scalar_reader(*base_kind, *list);
                    if *non_null {
                        let _ = writeln!(
                            output,
                            "{indent}@MainActor public var {}: {} {{ anchor.required{}({argument}) }}",
                            escape(&property),
                            swift_type,
                            capitalize(reader)
                        );
                    } else {
                        let _ = writeln!(
                            output,
                            "{indent}@MainActor public var {}: {}? {{ anchor.{reader}({argument}) }}",
                            escape(&property),
                            swift_type
                        );
                    }
                }
                SelectionPlan::Linked {
                    name,
                    alias,
                    base_type,
                    non_null,
                    plural,
                    is_abstract,
                    storage_key,
                    lookup,
                    selections: child,
                    ..
                } => {
                    let argument = self.read_argument(type_name, type_is_abstract, storage_key);
                    let property = alias.clone().unwrap_or_else(|| name.clone());
                    let nested_name = unique_nested_name(&property, nested);
                    self.types.insert(base_type.clone());
                    let lookup_argument = lookup
                        .as_ref()
                        .map(|lookup| {
                            format!(", lookup: {}", lookup_expression(lookup, storage_key))
                        })
                        .unwrap_or_default();
                    if *plural {
                        if *non_null {
                            let _ = writeln!(
                                output,
                                "{indent}@MainActor public var {}: Baton.List<{nested_name}> {{ anchor.requiredList({argument}) }}",
                                escape(&property)
                            );
                        } else {
                            let _ = writeln!(
                                output,
                                "{indent}@MainActor public var {}: Baton.List<{nested_name}>? {{ anchor.list({argument}) }}",
                                escape(&property)
                            );
                        }
                    } else if *non_null {
                        let _ = writeln!(
                            output,
                            "{indent}@MainActor public var {}: {nested_name} {{ {nested_name}(anchor: anchor.requiredLinked({argument}, type: Types.{base_type}{lookup_argument})) }}",
                            escape(&property)
                        );
                    } else {
                        let _ = writeln!(
                            output,
                            "{indent}@MainActor public var {}: {nested_name}? {{ anchor.linked({argument}{lookup_argument}).map({nested_name}.init(anchor:)) }}",
                            escape(&property)
                        );
                    }
                    nested.push(Nested {
                        name: nested_name,
                        type_name: base_type.clone(),
                        is_abstract: *is_abstract,
                        selections: child.clone(),
                    });
                }
                SelectionPlan::Spread {
                    fragment,
                    type_condition,
                } => {
                    let accessor = spread_names
                        .get(fragment)
                        .cloned()
                        .unwrap_or_else(|| lower_camel(fragment));
                    if !type_is_abstract || type_condition == type_name {
                        let _ = writeln!(
                            output,
                            "{indent}@MainActor public var {accessor}: {fragment} {{ {fragment}(anchor: anchor) }}"
                        );
                    } else {
                        self.types.insert(type_condition.clone());
                        let _ = writeln!(
                            output,
                            "{indent}@MainActor public var {accessor}: {fragment}? {{ anchor.record.is(Types.{type_condition}) ? {fragment}(anchor: anchor) : nil }}"
                        );
                    }
                }
                SelectionPlan::Inline {
                    type_condition,
                    selections: child,
                } => match type_condition {
                    Some(condition) if condition != type_name => {
                        let nested_name = format!("As{condition}");
                        self.types.insert(condition.clone());
                        let _ = writeln!(
                            output,
                            "{indent}@MainActor public var as{condition}: {nested_name}? {{ anchor.record.is(Types.{condition}) ? {nested_name}(anchor: anchor) : nil }}"
                        );
                        nested.push(Nested {
                            name: nested_name,
                            type_name: condition.clone(),
                            is_abstract: false,
                            selections: child.clone(),
                        });
                    }
                    _ => self.accessors(
                        output,
                        type_name,
                        type_is_abstract,
                        child,
                        indent,
                        nested,
                        spread_names,
                    ),
                },
                SelectionPlan::Condition {
                    selections: child, ..
                } => {
                    // `@include` / `@skip`: read as if present; a skipped field reads as missing.
                    self.accessors(
                        output,
                        type_name,
                        type_is_abstract,
                        child,
                        indent,
                        nested,
                        spread_names,
                    );
                }
            }
        }
    }

    /// The argument a lens accessor passes: a static slot on a concrete type, or
    /// a storage key resolved against the record's own type when the selection
    /// is on an interface or union.
    fn read_argument(
        &mut self,
        type_name: &str,
        type_is_abstract: bool,
        storage_key: &str,
    ) -> String {
        if type_is_abstract {
            self.types.insert(type_name.to_string());
            let slot = SlotRef {
                type_name: type_name.to_string(),
                storage_key: storage_key.to_string(),
            };
            if slot.is_dynamic() {
                format!(
                    "key: {}",
                    dynamic_key_expression(storage_key, "anchor.variables")
                )
            } else {
                format!("key: {}", swift_literal(storage_key))
            }
        } else {
            self.slot(type_name, storage_key)
        }
    }

    /// Writes a `Baton.Selection(...)` expression for the normalization plan.
    fn selection_plan(
        &mut self,
        output: &mut String,
        type_name: &str,
        has_id: bool,
        is_abstract: bool,
        selections: &[SelectionPlan],
        depth: usize,
    ) {
        self.types.insert(type_name.to_string());
        let pad = "    ".repeat(depth);
        let _ = write!(
            output,
            "Baton.Selection(type: Types.{type_name}, hasID: {has_id}, abstract: {is_abstract}, fields: ["
        );
        let mut any = false;
        for selection in flatten(selections) {
            any = true;
            let _ = write!(output, "\n{pad}    ");
            match selection {
                SelectionPlan::Scalar {
                    name,
                    alias,
                    base_kind,
                    list,
                    storage_key,
                    ..
                } => {
                    let slot = self.plan_key(type_name, storage_key);
                    let kind = match base_kind {
                        TypeKind::Int => "int",
                        TypeKind::Float => "double",
                        TypeKind::Boolean => "bool",
                        TypeKind::String | TypeKind::Id | TypeKind::Enum => "string",
                        _ => "custom",
                    };
                    let _ = write!(
                        output,
                        ".scalar(\"{}\", key: {slot}, kind: .{kind}, list: {list}),",
                        alias.as_deref().unwrap_or(name)
                    );
                }
                SelectionPlan::Linked {
                    name,
                    alias,
                    base_type,
                    plural,
                    has_id,
                    is_abstract,
                    storage_key,
                    lookup,
                    selections: child,
                    ..
                } => {
                    let slot = self.plan_key(type_name, storage_key);
                    let lookup_argument = lookup
                        .as_ref()
                        .map(|lookup| {
                            format!(", lookup: {}", lookup_expression(lookup, storage_key))
                        })
                        .unwrap_or_default();
                    let _ = write!(
                        output,
                        ".linked(\"{}\", key: {slot}, plural: {plural}{lookup_argument}, selection: ",
                        alias.as_deref().unwrap_or(name)
                    );
                    self.selection_plan(output, base_type, *has_id, *is_abstract, child, depth + 1);
                    output.push_str("),");
                }
                _ => unreachable!("flatten removes nested kinds"),
            }
        }
        if any {
            let _ = write!(output, "\n{pad}");
        }
        output.push_str("])");
    }

    /// Writes the optimistic-response builder tree for a mutation: one struct
    /// per selection set, every field optional, rendering to JSON.
    fn optimistic_builder(
        &mut self,
        output: &mut String,
        name: &str,
        selections: &[SelectionPlan],
        indent: &str,
    ) {
        let _ = writeln!(
            output,
            "{indent}/// A partial response to show before the server answers; absent fields leave the store untouched."
        );
        let _ = writeln!(output, "{indent}public struct {name}: Sendable {{");
        let inner = format!("{indent}    ");
        let flat = flatten(selections);
        let mut nested: Vec<(String, Vec<SelectionPlan>)> = Vec::new();
        let mut parameters: Vec<String> = Vec::new();
        let mut assignments: Vec<String> = Vec::new();
        let mut renders: Vec<String> = Vec::new();
        for selection in &flat {
            match selection {
                SelectionPlan::Scalar {
                    name,
                    alias,
                    base_kind,
                    list,
                    ..
                } => {
                    let property = alias.clone().unwrap_or_else(|| name.clone());
                    let (_, swift_type) = scalar_reader(*base_kind, *list);
                    let _ = writeln!(
                        output,
                        "{inner}public var {}: {swift_type}?",
                        escape(&property)
                    );
                    parameters.push(format!("{}: {swift_type}? = nil", escape(&property)));
                    assignments.push(format!("self.{0} = {0}", escape(&property)));
                    renders.push(format!(
                        "if let {0} {{ fields[\"{1}\"] = Baton.Variable({0}) }}",
                        escape(&property),
                        property
                    ));
                }
                SelectionPlan::Linked {
                    name,
                    alias,
                    plural,
                    selections: child,
                    ..
                } => {
                    let property = alias.clone().unwrap_or_else(|| name.clone());
                    let mut nested_name = capitalize(&property);
                    let mut counter = 2;
                    while nested.iter().any(|(existing, _)| existing == &nested_name) {
                        nested_name = format!("{}{counter}", capitalize(&property));
                        counter += 1;
                    }
                    let swift_type = if *plural {
                        format!("[{nested_name}]")
                    } else {
                        nested_name.clone()
                    };
                    let _ = writeln!(
                        output,
                        "{inner}public var {}: {swift_type}?",
                        escape(&property)
                    );
                    parameters.push(format!("{}: {swift_type}? = nil", escape(&property)));
                    assignments.push(format!("self.{0} = {0}", escape(&property)));
                    if *plural {
                        renders.push(format!(
                            "if let {0} {{ fields[\"{1}\"] = .list({0}.map(\\.variable)) }}",
                            escape(&property),
                            property
                        ));
                    } else {
                        renders.push(format!(
                            "if let {0} {{ fields[\"{1}\"] = {0}.variable }}",
                            escape(&property),
                            property
                        ));
                    }
                    nested.push((nested_name, child.clone()));
                }
                _ => unreachable!("flatten removes nested kinds"),
            }
        }
        let _ = writeln!(output, "{inner}public init({}) {{", parameters.join(", "));
        for assignment in &assignments {
            let _ = writeln!(output, "{inner}    {assignment}");
        }
        let _ = writeln!(output, "{inner}}}");
        let _ = writeln!(output, "{inner}public var variable: Baton.Variable {{");
        let _ = writeln!(
            output,
            "{inner}    var fields: [String: Baton.Variable] = [:]"
        );
        for render in &renders {
            let _ = writeln!(output, "{inner}    {render}");
        }
        let _ = writeln!(output, "{inner}    return .object(fields)");
        let _ = writeln!(output, "{inner}}}");
        for (nested_name, child) in nested {
            output.push('\n');
            self.optimistic_builder(output, &nested_name, &child, &inner);
        }
        let _ = writeln!(output, "{indent}}}");
    }

    fn slot(&mut self, type_name: &str, storage_key: &str) -> String {
        let slot = SlotRef {
            type_name: type_name.to_string(),
            storage_key: storage_key.to_string(),
        };
        let expression = slot.expression();
        self.slots.insert(slot);
        self.types.insert(type_name.to_string());
        expression
    }

    /// The key expression inside a plan: a fixed slot or a dynamic template.
    fn plan_key(&mut self, type_name: &str, storage_key: &str) -> String {
        let slot = SlotRef {
            type_name: type_name.to_string(),
            storage_key: storage_key.to_string(),
        };
        if slot.is_dynamic() {
            let parts = key_parts(storage_key)
                .into_iter()
                .map(|part| match part {
                    KeyPart::Literal(text) => format!(".literal(\"{text}\")"),
                    KeyPart::Variable(name) => format!(".variable(\"{name}\")"),
                })
                .collect::<Vec<_>>()
                .join(", ");
            self.slots.insert(slot);
            format!(".dynamic([{parts}])")
        } else {
            let expression = format!(".fixed(Slots.{})", slot.identifier());
            self.slots.insert(slot);
            expression
        }
    }
}

fn parameter_list(variables: &[VariablePlan]) -> String {
    variables
        .iter()
        .map(|variable| {
            let default = if variable.non_null { "" } else { " = nil" };
            format!("{}: {}{}", variable.name, variable_type(variable), default)
        })
        .collect::<Vec<_>>()
        .join(", ")
}

/// Normalization plans are flat: inline fragments and conditions are folded
/// into their parent; spreads were inlined by the compiler already.
fn flatten(selections: &[SelectionPlan]) -> Vec<&SelectionPlan> {
    let mut result = Vec::new();
    for selection in selections {
        match selection {
            SelectionPlan::Inline { selections, .. }
            | SelectionPlan::Condition { selections, .. } => {
                result.extend(flatten(selections));
            }
            SelectionPlan::Spread { .. } => {}
            other => result.push(other),
        }
    }
    result
}

enum KeyPart {
    Literal(String),
    Variable(String),
}

/// Splits `characters(page:$page,filter:$filter)` into literal and variable parts.
fn key_parts(storage_key: &str) -> Vec<KeyPart> {
    let mut parts = Vec::new();
    let mut literal = String::new();
    let mut characters = storage_key.chars().peekable();
    while let Some(character) = characters.next() {
        if character == '$' {
            if !literal.is_empty() {
                parts.push(KeyPart::Literal(std::mem::take(&mut literal)));
            }
            let mut name = String::new();
            while let Some(next) = characters.peek() {
                if next.is_alphanumeric() || *next == '_' {
                    name.push(*next);
                    characters.next();
                } else {
                    break;
                }
            }
            parts.push(KeyPart::Variable(name));
        } else {
            literal.push(character);
        }
    }
    if !literal.is_empty() {
        parts.push(KeyPart::Literal(literal));
    }
    parts
}

/// A Swift expression building the storage key from `variables`.
/// A Swift string literal for text that may contain quotes or backslashes
/// (storage keys carry JSON-rendered arguments).
fn swift_literal(text: &str) -> String {
    let mut output = String::with_capacity(text.len() + 2);
    output.push('"');
    for character in text.chars() {
        match character {
            '"' => output.push_str("\\\""),
            '\\' => output.push_str("\\\\"),
            '\n' => output.push_str("\\n"),
            other => output.push(other),
        }
    }
    output.push('"');
    output
}

fn dynamic_key_expression(storage_key: &str, variables: &str) -> String {
    key_parts(storage_key)
        .into_iter()
        .map(|part| match part {
            KeyPart::Literal(text) => swift_literal(&text),
            KeyPart::Variable(name) => format!("{variables}.render(\"{name}\")"),
        })
        .collect::<Vec<_>>()
        .join(" + ")
}

/// The lookup: the entity type (or none, for an id across types) and the
/// argument's value, a variable or a literal in the storage key.
fn lookup_expression(lookup: &LookupPlan, storage_key: &str) -> String {
    let argument_prefix = format!("{}:", lookup.argument);
    let inside = storage_key
        .split_once('(')
        .map(|(_, rest)| rest.trim_end_matches(')'))
        .unwrap_or("");
    let value = inside
        .split(',')
        .find_map(|pair| pair.strip_prefix(&argument_prefix))
        .unwrap_or("");
    let type_expression = match &lookup.type_name {
        Some(type_name) => format!("Types.{type_name}"),
        None => "nil".to_string(),
    };
    if let Some(variable) = value.strip_prefix('$') {
        format!("Baton.Lookup(type: {type_expression}, key: .variable(\"{variable}\"))")
    } else {
        format!(
            "Baton.Lookup(type: {type_expression}, key: .literal(\"{}\"))",
            value.trim_matches('"')
        )
    }
}

fn scalar_reader(kind: TypeKind, list: bool) -> (&'static str, String) {
    let (reader, swift) = match kind {
        TypeKind::Int => ("int", "Int"),
        TypeKind::Float => ("double", "Double"),
        TypeKind::Boolean => ("bool", "Bool"),
        _ => ("string", "String"),
    };
    if list {
        (
            match reader {
                "int" => "ints",
                "double" => "doubles",
                "bool" => "bools",
                _ => "strings",
            },
            format!("[{swift}]"),
        )
    } else {
        (reader, swift.to_string())
    }
}

fn variable_type(variable: &VariablePlan) -> String {
    let base = match variable.base_kind {
        TypeKind::Int => "Int",
        TypeKind::Float => "Double",
        TypeKind::Boolean => "Bool",
        TypeKind::String | TypeKind::Id | TypeKind::Enum | TypeKind::CustomScalar => "String",
        _ => "Baton.Variable",
    };
    let shape = if variable.list {
        format!("[{base}]")
    } else {
        base.to_string()
    };
    if variable.non_null {
        shape
    } else {
        format!("{shape}?")
    }
}

/// Default spread accessor names: the fragment's owner prefix in lower camel
/// case, falling back to the whole name when two spreads would collide.
/// The spreads a lens exposes directly: its own, and those inside inline
/// fragments and conditions that flatten into it (an inline fragment on the
/// lens's own type, as `@alias` produces; one on another type is a nested
/// lens with its own table).
fn collect_spreads<'a>(selections: &'a [SelectionPlan], type_name: &str, into: &mut Vec<&'a str>) {
    for selection in selections {
        match selection {
            SelectionPlan::Spread { fragment, .. } => into.push(fragment.as_str()),
            SelectionPlan::Inline {
                type_condition,
                selections: child,
            } => match type_condition {
                Some(condition) if condition != type_name => {}
                _ => collect_spreads(child, type_name, into),
            },
            SelectionPlan::Condition {
                selections: child, ..
            } => collect_spreads(child, type_name, into),
            _ => {}
        }
    }
}

fn spread_accessor_names(
    selections: &[SelectionPlan],
    type_name: &str,
) -> BTreeMap<String, String> {
    let mut fragments: Vec<&str> = Vec::new();
    collect_spreads(selections, type_name, &mut fragments);
    let mut by_prefix: BTreeMap<String, Vec<&str>> = BTreeMap::new();
    for fragment in &fragments {
        let prefix = fragment.split('_').next().unwrap_or(fragment);
        by_prefix
            .entry(lower_camel(prefix))
            .or_default()
            .push(fragment);
    }
    let mut names = BTreeMap::new();
    for (prefix, owners) in by_prefix {
        if owners.len() == 1 {
            names.insert(owners[0].to_string(), prefix);
        } else {
            for owner in owners {
                names.insert(owner.to_string(), lower_camel(owner));
            }
        }
    }
    names
}

fn unique_nested_name(property: &str, nested: &[Nested]) -> String {
    let base = capitalize(property);
    let mut candidate = base.clone();
    let mut counter = 2;
    while nested.iter().any(|child| child.name == candidate) {
        candidate = format!("{base}{counter}");
        counter += 1;
    }
    candidate
}

fn capitalize(text: &str) -> String {
    let mut characters = text.chars();
    match characters.next() {
        Some(first) => first.to_uppercase().collect::<String>() + characters.as_str(),
        None => String::new(),
    }
}

fn lower_camel(text: &str) -> String {
    let mut characters = text.chars();
    match characters.next() {
        Some(first) => first.to_lowercase().collect::<String>() + characters.as_str(),
        None => String::new(),
    }
}

/// Escapes a property name that is a Swift keyword.
fn escape(name: &str) -> String {
    const KEYWORDS: &[&str] = &[
        "Type",
        "Protocol",
        "self",
        "Self",
        "init",
        "deinit",
        "subscript",
        "class",
        "struct",
        "enum",
        "func",
        "var",
        "let",
        "import",
        "extension",
        "operator",
        "static",
        "default",
        "case",
        "switch",
        "if",
        "else",
        "for",
        "in",
        "while",
        "repeat",
        "return",
        "break",
        "continue",
        "where",
        "is",
        "as",
        "try",
        "throw",
        "throws",
        "guard",
        "defer",
        "do",
        "catch",
        "true",
        "false",
        "nil",
        "super",
        "internal",
        "private",
        "public",
        "fileprivate",
        "open",
        "inout",
        "typealias",
        "associatedtype",
        "protocol",
        "some",
        "any",
    ];
    if KEYWORDS.contains(&name) {
        format!("`{name}`")
    } else {
        name.to_string()
    }
}
