// Generated by scripts/relay-harvest/translate.py from the documents of
// Relay's store tests (MIT, Meta Platforms, Inc. and affiliates). Do not
// edit; run the translator again.

import Baton

@MainActor
struct RelayDocuments {
    @Query("""
        query RelayResponseNormalizerTest1Query($id: ID, $size: [Int]) {
          node(id: $id) {
            id
            __typename
            ... on User {
              firstName
              friends(first: 3) {
                edges {
                  cursor
                  node {
                    id
                    firstName
                  }
                }
              }
              profilePicture(size: $size) {
                uri
              }
            }
          }
        }
        """)
    var relayResponseNormalizerTest1Query: RelayResponseNormalizerTest1Query

    @Query("""
        query RelayResponseNormalizerTest6Query(
          $id: ID!
          $enableDefer: Boolean!
        ) {
          node(id: $id) {
            ...RelayResponseNormalizerTest2Fragment
              @alias
              @defer(label: "TestFragment", if: $enableDefer)
          }
        }
        """)
    var relayResponseNormalizerTest6Query: RelayResponseNormalizerTest6Query

    @Fragment("""
        fragment RelayResponseNormalizerTest2Fragment on User {
          id
          name
        }
        """)
    var relayResponseNormalizerTest2Fragment: RelayResponseNormalizerTest2Fragment

    @Query("""
        query RelayResponseNormalizerTest7Query($id: ID!) {
          node(id: $id) {
            ...RelayResponseNormalizerTest3Fragment
              @alias
              @defer(label: "TestFragment", if: true)
          }
        }
        """)
    var relayResponseNormalizerTest7Query: RelayResponseNormalizerTest7Query

    @Fragment("""
        fragment RelayResponseNormalizerTest3Fragment on User {
          id
          name
        }
        """)
    var relayResponseNormalizerTest3Fragment: RelayResponseNormalizerTest3Fragment

    @Query("""
        query RelayResponseNormalizerTest8Query(
          $id: ID!
          $enableDefer: Boolean!
        ) {
          node(id: $id) {
            ...RelayResponseNormalizerTest4Fragment
              @alias
              @defer(label: "TestFragment", if: $enableDefer)
          }
        }
        """)
    var relayResponseNormalizerTest8Query: RelayResponseNormalizerTest8Query

    @Fragment("""
        fragment RelayResponseNormalizerTest4Fragment on User {
          id
          name
        }
        """)
    var relayResponseNormalizerTest4Fragment: RelayResponseNormalizerTest4Fragment

    @Query("""
        query RelayResponseNormalizerTest9Query($id: ID!) {
          node(id: $id) {
            ... on Feedback {
              actors {
                ...RelayResponseNormalizerTest5Fragment
                  @alias
                  @defer(label: "TestFragment", if: true)
              }
            }
          }
        }
        """)
    var relayResponseNormalizerTest9Query: RelayResponseNormalizerTest9Query

    @Fragment("""
        fragment RelayResponseNormalizerTest5Fragment on User {
          name
        }
        """)
    var relayResponseNormalizerTest5Fragment: RelayResponseNormalizerTest5Fragment

    @Query("""
        query RelayResponseNormalizerTest10Query($id: ID!) {
          node(id: $id) {
            ...RelayResponseNormalizerTest6Fragment
              @alias
              @defer(label: "TestFragment")
          }
        }
        """)
    var relayResponseNormalizerTest10Query: RelayResponseNormalizerTest10Query

    @Fragment("""
        fragment RelayResponseNormalizerTest6Fragment on User {
          id
          name
        }
        """)
    var relayResponseNormalizerTest6Fragment: RelayResponseNormalizerTest6Fragment

    @Query("""
        query RelayResponseNormalizerTest20Query($id: ID) {
          node(id: $id) {
            id
            __typename
            ... on User {
              firstName
              profilePicture(size: 100) {
                uri
              }
            }
          }
        }
        """)
    var relayResponseNormalizerTest20Query: RelayResponseNormalizerTest20Query

    @Query("""
        query RelayResponseNormalizerTest21Query {
          named {
            name
            ... on Node {
              id
            }
          }
        }
        """)
    var relayResponseNormalizerTest21Query: RelayResponseNormalizerTest21Query

    @Query("""
        query RelayResponseNormalizerTest22Query($id: ID) {
          node(id: $id) {
            id
            __typename
            ... on User {
              name
              friends(first: 2) {
                edges {
                  node {
                    id
                    firstName
                  }
                }
              }
            }
          }
        }
        """)
    var relayResponseNormalizerTest22Query: RelayResponseNormalizerTest22Query

    @Query("""
        query RelayResponseNormalizerTest32Query($id: ID) {
          node(id: $id) {
            id
            __typename
            ... on User {
              name
              friends(first: 2) {
                edges {
                  node {
                    id
                    firstName
                  }
                }
              }
            }
          }
        }
        """)
    var relayResponseNormalizerTest32Query: RelayResponseNormalizerTest32Query

    @Query("""
        query RelayResponseNormalizerTest23Query($id: ID) {
          node(id: $id) {
            id
            __typename
            ... on User {
              name
              friends(first: 2) {
                edges {
                  node {
                    id
                    emailAddresses
                  }
                }
              }
            }
          }
        }
        """)
    var relayResponseNormalizerTest23Query: RelayResponseNormalizerTest23Query

    @Query("""
        query RelayResponseNormalizerTest24Query($id: ID) {
          node(id: $id) {
            id
            __typename
            ... on User {
              name
              friends(first: 4) {
                edges {
                  node {
                    id
                    firstName
                  }
                }
              }
            }
          }
        }
        """)
    var relayResponseNormalizerTest24Query: RelayResponseNormalizerTest24Query

    @Query("""
        query RelayResponseNormalizerTest25Query($id: ID) {
          node(id: $id) {
            id
            __typename
            ... on User {
              name
              friends(first: 2) {
                edges {
                  node {
                    id
                    firstName
                    comments(first: 1) {
                      edges {
                        node {
                          id
                          body {
                            text
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
        """)
    var relayResponseNormalizerTest25Query: RelayResponseNormalizerTest25Query

    @Query("""
        query RelayResponseNormalizerTest26Query($id: ID) {
          node(id: $id) {
            id
            __typename
            ... on User {
              name
              friends(first: 2) {
                edges {
                  node {
                    id
                    firstName
                    comments(first: 1) {
                      edges {
                        node {
                          id
                          body {
                            text
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
        """)
    var relayResponseNormalizerTest26Query: RelayResponseNormalizerTest26Query

    @Query("""
        query RelayResponseNormalizerTest29Query($id: ID, $size: [Int]) {
          node(id: $id) {
            id
            __typename
            ... on User {
              firstName
              profilePicture(size: $size) {
                uri
              }
            }
          }
        }
        """)
    var relayResponseNormalizerTest29Query: RelayResponseNormalizerTest29Query

    @Query("""
        query RelayResponseNormalizerTest30Query {
          me {
            author {
              id
            }
          }
        }
        """)
    var relayResponseNormalizerTest30Query: RelayResponseNormalizerTest30Query

    @Query("""
        query RelayResponseNormalizerTest31Query {
          me {
            actors {
              id
            }
          }
        }
        """)
    var relayResponseNormalizerTest31Query: RelayResponseNormalizerTest31Query

    @Query("""
        query RelayResponseNormalizerTest37Query($id: ID!) {
          node(id: $id) {
            id
            __typename
            ... on User {
              firstName
              lastName
              friends(first: 3) {
                edges {
                  cursor
                  node {
                    firstName
                    lastName
                  }
                }
              }
            }
          }
        }
        """)
    var relayResponseNormalizerTest37Query: RelayResponseNormalizerTest37Query

    @Query("""
        query RelayResponseNormalizerTest38Query($id: ID!) {
          node(id: $id) {
            id
            __typename
            ... on User {
              firstName
              lastName
              friends(first: 3) {
                edges {
                  cursor
                  node {
                    firstName
                    lastName
                  }
                }
              }
            }
          }
        }
        """)
    var relayResponseNormalizerTest38Query: RelayResponseNormalizerTest38Query

    @Query("""
        query RelayResponseNormalizerTest39Query($id: ID!) {
          node(id: $id) {
            id
            __typename
            ... on User {
              friends(first: 3) {
                edges {
                  cursor
                }
              }
            }
          }
        }
        """)
    var relayResponseNormalizerTest39Query: RelayResponseNormalizerTest39Query

    @Query("""
        query RelayResponseNormalizerTest42Query($id: ID!) {
          node(id: $id) {
            ...RelayResponseNormalizerTest42Fragment
          }
        }
        """)
    var relayResponseNormalizerTest42Query: RelayResponseNormalizerTest42Query

    @Fragment("""
        fragment RelayResponseNormalizerTest42Fragment on Node {
          id
          ... on User {
            name
          }
        }
        """)
    var relayResponseNormalizerTest42Fragment: RelayResponseNormalizerTest42Fragment

    @Query("""
        query RelayResponseNormalizerTest43Query($id: ID!) {
          userOrPage(id: $id) {
            ... on User {
              id
            }
          }
        }
        """)
    var relayResponseNormalizerTest43Query: RelayResponseNormalizerTest43Query
}

extension RelayDocuments {
    /// Every operation by its name.
    static let operations: [String: any Baton.Operation.Type] = [
        "RelayResponseNormalizerTest1Query": RelayResponseNormalizerTest1Query.self,
        "RelayResponseNormalizerTest6Query": RelayResponseNormalizerTest6Query.self,
        "RelayResponseNormalizerTest7Query": RelayResponseNormalizerTest7Query.self,
        "RelayResponseNormalizerTest8Query": RelayResponseNormalizerTest8Query.self,
        "RelayResponseNormalizerTest9Query": RelayResponseNormalizerTest9Query.self,
        "RelayResponseNormalizerTest10Query": RelayResponseNormalizerTest10Query.self,
        "RelayResponseNormalizerTest20Query": RelayResponseNormalizerTest20Query.self,
        "RelayResponseNormalizerTest21Query": RelayResponseNormalizerTest21Query.self,
        "RelayResponseNormalizerTest22Query": RelayResponseNormalizerTest22Query.self,
        "RelayResponseNormalizerTest32Query": RelayResponseNormalizerTest32Query.self,
        "RelayResponseNormalizerTest23Query": RelayResponseNormalizerTest23Query.self,
        "RelayResponseNormalizerTest24Query": RelayResponseNormalizerTest24Query.self,
        "RelayResponseNormalizerTest25Query": RelayResponseNormalizerTest25Query.self,
        "RelayResponseNormalizerTest26Query": RelayResponseNormalizerTest26Query.self,
        "RelayResponseNormalizerTest29Query": RelayResponseNormalizerTest29Query.self,
        "RelayResponseNormalizerTest30Query": RelayResponseNormalizerTest30Query.self,
        "RelayResponseNormalizerTest31Query": RelayResponseNormalizerTest31Query.self,
        "RelayResponseNormalizerTest37Query": RelayResponseNormalizerTest37Query.self,
        "RelayResponseNormalizerTest38Query": RelayResponseNormalizerTest38Query.self,
        "RelayResponseNormalizerTest39Query": RelayResponseNormalizerTest39Query.self,
        "RelayResponseNormalizerTest42Query": RelayResponseNormalizerTest42Query.self,
        "RelayResponseNormalizerTest43Query": RelayResponseNormalizerTest43Query.self,
    ]
}
