// Generated by batonc. Do not edit.
@_spi(Generated) import Baton

/// Lens for `fragment Fragment on Character`.
nonisolated public struct Fragment: Baton.Lens {
    @_spi(Generated) public let anchor: Baton.Anchor
    @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
    public static let typeName = "Character"
    @MainActor public var status: String? { anchor.string(Slots.Character.status) }
    /// The field errors in this selection, for `@catch` and `@throwOnFieldError`.
    @_spi(Generated) @MainActor public static func fieldErrors(_ anchor: Baton.Anchor) -> [Baton.FieldError] {
        var errors: [Baton.FieldError] = []
        anchor.collectError(Slots.Character.status, into: &errors)
        return errors
    }
    /// The lens, or the field errors in it as a thrown `FieldErrors`.
    @_spi(Generated) @MainActor public static func throwing(_ anchor: Baton.Anchor) throws -> Self { try caught(anchor).get() }
    /// The lens, or the field errors in it as a `Result`.
    @_spi(Generated) @MainActor public static func caught(_ anchor: Baton.Anchor) -> Result<Self, Baton.FieldErrors> {
        let errors = fieldErrors(anchor)
        return errors.isEmpty ? .success(Self(anchor: anchor)) : .failure(.init(errors))
    }
}

/// Lens for `fragment TestCaughtProfile_character on Character`.
nonisolated public struct TestCaughtProfile_character: Baton.Lens {
    @_spi(Generated) public let anchor: Baton.Anchor
    @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
    public static let typeName = "Character"
    @MainActor public var name: String? { anchor.string(Slots.Character.name) }
    @MainActor public var origin: Origin? { anchor.linked(Slots.Character.origin).map(Origin.init(anchor:)) }
    /// The field errors in this selection, for `@catch` and `@throwOnFieldError`.
    @_spi(Generated) @MainActor public static func fieldErrors(_ anchor: Baton.Anchor) -> [Baton.FieldError] {
        var errors: [Baton.FieldError] = []
        anchor.collectError(Slots.Character.name, into: &errors)
        anchor.collectErrors(Slots.Character.origin, within: Origin.fieldErrors, into: &errors)
        return errors
    }
    /// The lens, or the field errors in it as a thrown `FieldErrors`.
    @_spi(Generated) @MainActor public static func throwing(_ anchor: Baton.Anchor) throws -> Self { try caught(anchor).get() }
    /// The lens, or the field errors in it as a `Result`.
    @_spi(Generated) @MainActor public static func caught(_ anchor: Baton.Anchor) -> Result<Self, Baton.FieldErrors> {
        let errors = fieldErrors(anchor)
        return errors.isEmpty ? .success(Self(anchor: anchor)) : .failure(.init(errors))
    }

    nonisolated public struct Origin: Baton.Lens {
        @_spi(Generated) public let anchor: Baton.Anchor
        @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
        public static let typeName = "Location"
        @MainActor public var name: String? { anchor.string(Slots.Location.name) }
        /// The field errors in this selection, for `@catch` and `@throwOnFieldError`.
        @_spi(Generated) @MainActor public static func fieldErrors(_ anchor: Baton.Anchor) -> [Baton.FieldError] {
            var errors: [Baton.FieldError] = []
            anchor.collectError(Slots.Location.name, into: &errors)
            return errors
        }
        /// The lens, or the field errors in it as a thrown `FieldErrors`.
        @_spi(Generated) @MainActor public static func throwing(_ anchor: Baton.Anchor) throws -> Self { try caught(anchor).get() }
        /// The lens, or the field errors in it as a `Result`.
        @_spi(Generated) @MainActor public static func caught(_ anchor: Baton.Anchor) -> Result<Self, Baton.FieldErrors> {
            let errors = fieldErrors(anchor)
            return errors.isEmpty ? .success(Self(anchor: anchor)) : .failure(.init(errors))
        }
    }
}

/// Lens for `fragment TestCaughtStrict_character on Character`.
nonisolated public struct TestCaughtStrict_character: Baton.Lens {
    @_spi(Generated) public let anchor: Baton.Anchor
    @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
    public static let typeName = "Character"
    @MainActor public var species: String { anchor.requiredString(Slots.Character.species) }
    /// The field errors in this selection, for `@catch` and `@throwOnFieldError`.
    @_spi(Generated) @MainActor public static func fieldErrors(_ anchor: Baton.Anchor) -> [Baton.FieldError] {
        var errors: [Baton.FieldError] = []
        anchor.collectError(Slots.Character.species, into: &errors)
        return errors
    }
    /// The lens, or the field errors in it as a thrown `FieldErrors`.
    @_spi(Generated) @MainActor public static func throwing(_ anchor: Baton.Anchor) throws -> Self { try caught(anchor).get() }
    /// The lens, or the field errors in it as a `Result`.
    @_spi(Generated) @MainActor public static func caught(_ anchor: Baton.Anchor) -> Result<Self, Baton.FieldErrors> {
        let errors = fieldErrors(anchor)
        return errors.isEmpty ? .success(Self(anchor: anchor)) : .failure(.init(errors))
    }
}

/// Lens for `fragment TestEdgesNames_character on Character`.
nonisolated public struct TestEdgesNames_character: Baton.Lens {
    @_spi(Generated) public let anchor: Baton.Anchor
    @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
    public static let typeName = "Character"
    @MainActor public var notes: Notes { Notes(anchor: anchor.requiredLinked(Slots.Character.__TestEdgesNames_notes_connection, type: Types.NoteConnection)) }

    nonisolated public struct Notes: Baton.Lens {
        @_spi(Generated) public let anchor: Baton.Anchor
        @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
        public static let typeName = "NoteConnection"
        @MainActor public var Edges: Edges2 { Edges2(anchor: anchor.requiredLinked(Slots.NoteConnection.pageInfo, type: Types.PageInfo)) }
        @MainActor public var edges: Baton.List<Edges3>? { anchor.list(Slots.NoteConnection.edges) }
        @MainActor public var pageInfo: PageInfo { PageInfo(anchor: anchor.requiredLinked(Slots.NoteConnection.pageInfo, type: Types.PageInfo)) }
        /// The connection's slots: edges, nodes, cursors and the page info, for the store's merge and the state below.
        @_spi(Generated) public static let connection: Baton.ConnectionSlots = .init(connection: Types.NoteConnection, edge: Types.NoteEdge, pageInfo: Types.PageInfo)
        /// The edges' nodes, in order, without nulls.
        @MainActor public var nodes: [Edges3.Node] { anchor.nodes(Self.connection) }
        /// Whether the server has edges after the last one, from the merged `pageInfo`.
        @MainActor public var hasNext: Bool { anchor.hasNext(Self.connection) }
        @MainActor public var hasPrevious: Bool { anchor.hasPrevious(Self.connection) }
        @MainActor public var isLoadingNext: Bool { anchor.isLoadingNext(Self.connection) }
        @MainActor public var isLoadingPrevious: Bool { anchor.isLoadingPrevious(Self.connection) }
        /// Relay's connection id, for the `connections` argument of the edge directives.
        @MainActor public var connectionID: String { anchor.record.key }

        nonisolated public struct Edges2: Baton.Lens {
            @_spi(Generated) public let anchor: Baton.Anchor
            @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
            public static let typeName = "PageInfo"
            @MainActor public var hasNextPage: Bool { anchor.requiredBool(Slots.PageInfo.hasNextPage) }
        }

        nonisolated public struct Edges3: Baton.Lens {
            @_spi(Generated) public let anchor: Baton.Anchor
            @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
            public static let typeName = "NoteEdge"
            @MainActor public var node: Node? { anchor.linked(Slots.NoteEdge.node).map(Node.init(anchor:)) }
            @MainActor public var cursor: String { anchor.requiredString(Slots.NoteEdge.cursor) }

            nonisolated public struct Node: Baton.Lens {
                @_spi(Generated) public let anchor: Baton.Anchor
                @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
                public static let typeName = "Note"
                @MainActor public var id: String? { anchor.string(Slots.Note.id) }
                @MainActor public var text: String? { anchor.string(Slots.Note.text) }
            }
        }

        nonisolated public struct PageInfo: Baton.Lens {
            @_spi(Generated) public let anchor: Baton.Anchor
            @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
            public static let typeName = "PageInfo"
            @MainActor public var endCursor: String? { anchor.string(Slots.PageInfo.endCursor) }
            @MainActor public var hasNextPage: Bool { anchor.requiredBool(Slots.PageInfo.hasNextPage) }
        }
    }
}

/// Lens for `fragment TestProgramNames_character on Character`.
nonisolated public struct TestProgramNames_character: Baton.Lens {
    @_spi(Generated) public let anchor: Baton.Anchor
    @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
    public static let typeName = "Character"
    @MainActor public var testProgramNamesRefetchQuery: TestProgramNamesRefetchQueryLens? { anchor.linked(Slots.Character.origin).map(TestProgramNamesRefetchQueryLens.init(anchor:)) }
    @MainActor public var testCaughtProfile_character: TestCaughtProfile_characterLens? { anchor.linked(Slots.Character.location).map(TestCaughtProfile_characterLens.init(anchor:)) }
    @MainActor public var testCaughtProfile: TestCaughtProfile_character { .init(anchor: anchor) }
    @MainActor public var id: String? { anchor.string(Slots.Character.id) }
    /// How the fragment is fetched again: `TestProgramNamesRefetchQuery` with the lens's variables.
    @_spi(Generated) public static let refetchable: Baton.Refetch = .init(variables: ["id"], identifier: "id", first: nil, after: nil, last: nil, before: nil)
    /// Fetches the fragment again through `TestProgramNamesRefetchQuery` with its current variables; the records update in place.
    @MainActor public func refetch() async throws {
        typealias Query = TestProgramNamesRefetchQuery
        try await anchor.refetch(Query.self, Self.refetchable)
    }

    nonisolated public struct TestProgramNamesRefetchQueryLens: Baton.Lens {
        @_spi(Generated) public let anchor: Baton.Anchor
        @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
        public static let typeName = "Location"
        @MainActor public var name: String? { anchor.string(Slots.Location.name) }
    }

    nonisolated public struct TestCaughtProfile_characterLens: Baton.Lens {
        @_spi(Generated) public let anchor: Baton.Anchor
        @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
        public static let typeName = "Location"
        @MainActor public var name: String? { anchor.string(Slots.Location.name) }
    }
}

/// Lens for `fragment testLowercase on Character`.
nonisolated public struct testLowercase: Baton.Lens {
    @_spi(Generated) public let anchor: Baton.Anchor
    @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
    public static let typeName = "Character"
    @MainActor public var name: String? { anchor.string(Slots.Character.name) }
}

/// Lens for `fragment testLowercaseRequired on Character`.
nonisolated public struct testLowercaseRequired: Baton.Lens {
    @_spi(Generated) public let anchor: Baton.Anchor
    @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
    public static let typeName = "Character"
    @MainActor public var origin: Origin { Origin(anchor: anchor.requiredLinked(Slots.Character.origin, type: Types.Location)) }
    /// Whether every `@required` field is present; the lens is otherwise null to its parent, as Relay bubbles.
    @_spi(Generated) @MainActor public static func satisfied(_ anchor: Baton.Anchor) -> Bool {
        guard anchor.hasValue(Slots.Character.origin, path: "origin", log: false) else { return false }
        return true
    }

    nonisolated public struct Origin: Baton.Lens {
        @_spi(Generated) public let anchor: Baton.Anchor
        @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
        public static let typeName = "Location"
        @MainActor public var name: String? { anchor.string(Slots.Location.name) }
    }
}

/// Operation value for `mutation TestBuilderNames`.
nonisolated public struct TestBuilderNames: Baton.Mutation {
    public var id: String
    public var favorite: Bool
    public var `self`: String

    public init(id: String, favorite: Bool, `self` selfValue: String) {
        self.id = id
        self.favorite = favorite
        self.`self` = selfValue
    }

    public static let name = "TestBuilderNames"
    public static let persistedID = "257b27e016fc51dd507f48551b1bc353"
    public static let text = #"""
mutation TestBuilderNames(
  $id: ID!
  $favorite: Boolean!
  $self: ID!
) {
  type: setFavorite(id: $id, favorite: $favorite) {
    character {
      id
      favorite
    }
  }
  self: setFavorite(id: $self, favorite: $favorite) {
    character {
      id
      favorite
    }
  }
  string: setFavorite(id: $id, favorite: $favorite) {
    character {
      id
      name
    }
  }
  sendable: setFavorite(id: $id, favorite: $favorite) {
    character {
      id
      favorite
    }
  }
}
"""#

    public var variables: Baton.Variables {
        Baton.Variables(["id": Baton.Variable(self.id), "favorite": Baton.Variable(self.favorite), "self": Baton.Variable(self.`self`)])
    }

    public static func == (lhs: Self, rhs: Self) -> Bool {
        lhs.id == rhs.id && lhs.favorite == rhs.favorite && lhs.`self` == rhs.`self`
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(self.id)
        hasher.combine(self.favorite)
        hasher.combine(self.`self`)
    }

    @_spi(Generated) public static let plan = Baton.Plan(root: Baton.Selection(type: Types.Mutation, hasID: false, abstract: false, fields: [
            .linked("type", key: .fixed(Slots.Mutation.setFavorite_10eb38), plural: false, selection: Baton.Selection(type: Types.FavoritePayload, hasID: false, abstract: false, fields: [
                .linked("character", key: .fixed(Slots.FavoritePayload.character), plural: false, selection: Baton.Selection(type: Types.Character, hasID: true, abstract: false, fields: [
                    .scalar("id", key: .fixed(Slots.Character.id), kind: .string, list: false),
                    .scalar("favorite", key: .fixed(Slots.Character.favorite), kind: .bool, list: false),
                ])),
            ])),
            .linked("self", key: .fixed(Slots.Mutation.setFavorite_e62d42), plural: false, selection: Baton.Selection(type: Types.FavoritePayload, hasID: false, abstract: false, fields: [
                .linked("character", key: .fixed(Slots.FavoritePayload.character), plural: false, selection: Baton.Selection(type: Types.Character, hasID: true, abstract: false, fields: [
                    .scalar("id", key: .fixed(Slots.Character.id), kind: .string, list: false),
                    .scalar("favorite", key: .fixed(Slots.Character.favorite), kind: .bool, list: false),
                ])),
            ])),
            .linked("string", key: .fixed(Slots.Mutation.setFavorite_937be0), plural: false, selection: Baton.Selection(type: Types.FavoritePayload, hasID: false, abstract: false, fields: [
                .linked("character", key: .fixed(Slots.FavoritePayload.character), plural: false, selection: Baton.Selection(type: Types.Character, hasID: true, abstract: false, fields: [
                    .scalar("id", key: .fixed(Slots.Character.id), kind: .string, list: false),
                    .scalar("name", key: .fixed(Slots.Character.name), kind: .string, list: false),
                ])),
            ])),
            .linked("sendable", key: .fixed(Slots.Mutation.setFavorite_a93f6b), plural: false, selection: Baton.Selection(type: Types.FavoritePayload, hasID: false, abstract: false, fields: [
                .linked("character", key: .fixed(Slots.FavoritePayload.character), plural: false, selection: Baton.Selection(type: Types.Character, hasID: true, abstract: false, fields: [
                    .scalar("id", key: .fixed(Slots.Character.id), kind: .string, list: false),
                    .scalar("favorite", key: .fixed(Slots.Character.favorite), kind: .bool, list: false),
                ])),
            ])),
        ]))

    nonisolated public struct Data: Baton.Lens {
        @_spi(Generated) public let anchor: Baton.Anchor
        @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
        public static let typeName = "Mutation"
        @MainActor public var type: TypeLens? { anchor.linked(Slots.Mutation.setFavorite_10eb38).map(TypeLens.init(anchor:)) }
        @MainActor public var `self`: SelfLens? { anchor.linked(Slots.Mutation.setFavorite_e62d42).map(SelfLens.init(anchor:)) }
        @MainActor public var string: StringLens? { anchor.linked(Slots.Mutation.setFavorite_937be0).map(StringLens.init(anchor:)) }
        @MainActor public var sendable: Sendable? { anchor.linked(Slots.Mutation.setFavorite_a93f6b).map(Sendable.init(anchor:)) }

        nonisolated public struct TypeLens: Baton.Lens {
            @_spi(Generated) public let anchor: Baton.Anchor
            @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
            public static let typeName = "FavoritePayload"
            @MainActor public var character: Character? { anchor.linked(Slots.FavoritePayload.character).map(Character.init(anchor:)) }

            nonisolated public struct Character: Baton.Lens {
                @_spi(Generated) public let anchor: Baton.Anchor
                @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
                public static let typeName = "Character"
                @MainActor public var id: String? { anchor.string(Slots.Character.id) }
                @MainActor public var favorite: Bool? { anchor.bool(Slots.Character.favorite) }
            }
        }

        nonisolated public struct SelfLens: Baton.Lens {
            @_spi(Generated) public let anchor: Baton.Anchor
            @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
            public static let typeName = "FavoritePayload"
            @MainActor public var character: Character? { anchor.linked(Slots.FavoritePayload.character).map(Character.init(anchor:)) }

            nonisolated public struct Character: Baton.Lens {
                @_spi(Generated) public let anchor: Baton.Anchor
                @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
                public static let typeName = "Character"
                @MainActor public var id: String? { anchor.string(Slots.Character.id) }
                @MainActor public var favorite: Bool? { anchor.bool(Slots.Character.favorite) }
            }
        }

        nonisolated public struct StringLens: Baton.Lens {
            @_spi(Generated) public let anchor: Baton.Anchor
            @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
            public static let typeName = "FavoritePayload"
            @MainActor public var character: Character? { anchor.linked(Slots.FavoritePayload.character).map(Character.init(anchor:)) }

            nonisolated public struct Character: Baton.Lens {
                @_spi(Generated) public let anchor: Baton.Anchor
                @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
                public static let typeName = "Character"
                @MainActor public var id: String? { anchor.string(Slots.Character.id) }
                @MainActor public var name: String? { anchor.string(Slots.Character.name) }
            }
        }

        nonisolated public struct Sendable: Baton.Lens {
            @_spi(Generated) public let anchor: Baton.Anchor
            @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
            public static let typeName = "FavoritePayload"
            @MainActor public var character: Character? { anchor.linked(Slots.FavoritePayload.character).map(Character.init(anchor:)) }

            nonisolated public struct Character: Baton.Lens {
                @_spi(Generated) public let anchor: Baton.Anchor
                @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
                public static let typeName = "Character"
                @MainActor public var id: String? { anchor.string(Slots.Character.id) }
                @MainActor public var favorite: Bool? { anchor.bool(Slots.Character.favorite) }
            }
        }
    }

    public typealias Action = Baton.MutationAction<Self>

    /// A partial response to show before the server answers; absent fields leave the store untouched.
    nonisolated public struct OptimisticResponse: Sendable {
        public var type: TypeResponse?
        public var `self`: SelfResponse?
        public var string: StringResponse?
        public var sendable: SendableResponse?
        public init(type: TypeResponse? = nil, `self` selfValue: SelfResponse? = nil, string: StringResponse? = nil, sendable: SendableResponse? = nil) {
            self.type = type
            self.`self` = selfValue
            self.string = string
            self.sendable = sendable
        }
        public var variable: Baton.Variable {
            var fields: [String: Baton.Variable] = [:]
            if let type { fields["type"] = type.variable }
            if let selfValue = self.`self` { fields["self"] = selfValue.variable }
            if let string { fields["string"] = string.variable }
            if let sendable { fields["sendable"] = sendable.variable }
            return .object(fields)
        }

        /// A partial response to show before the server answers; absent fields leave the store untouched.
        nonisolated public struct TypeResponse: Sendable {
            public var character: Character?
            public init(character: Character? = nil) {
                self.character = character
            }
            public var variable: Baton.Variable {
                var fields: [String: Baton.Variable] = [:]
                if let character { fields["character"] = character.variable }
                return .object(fields)
            }

            /// A partial response to show before the server answers; absent fields leave the store untouched.
            nonisolated public struct Character: Sendable {
                public var id: String?
                public var favorite: Bool?
                public init(id: String? = nil, favorite: Bool? = nil) {
                    self.id = id
                    self.favorite = favorite
                }
                public var variable: Baton.Variable {
                    var fields: [String: Baton.Variable] = [:]
                    if let id { fields["id"] = .init(id) }
                    if let favorite { fields["favorite"] = .init(favorite) }
                    return .object(fields)
                }
            }
        }

        /// A partial response to show before the server answers; absent fields leave the store untouched.
        nonisolated public struct SelfResponse: Sendable {
            public var character: Character?
            public init(character: Character? = nil) {
                self.character = character
            }
            public var variable: Baton.Variable {
                var fields: [String: Baton.Variable] = [:]
                if let character { fields["character"] = character.variable }
                return .object(fields)
            }

            /// A partial response to show before the server answers; absent fields leave the store untouched.
            nonisolated public struct Character: Sendable {
                public var id: String?
                public var favorite: Bool?
                public init(id: String? = nil, favorite: Bool? = nil) {
                    self.id = id
                    self.favorite = favorite
                }
                public var variable: Baton.Variable {
                    var fields: [String: Baton.Variable] = [:]
                    if let id { fields["id"] = .init(id) }
                    if let favorite { fields["favorite"] = .init(favorite) }
                    return .object(fields)
                }
            }
        }

        /// A partial response to show before the server answers; absent fields leave the store untouched.
        nonisolated public struct StringResponse: Sendable {
            public var character: Character?
            public init(character: Character? = nil) {
                self.character = character
            }
            public var variable: Baton.Variable {
                var fields: [String: Baton.Variable] = [:]
                if let character { fields["character"] = character.variable }
                return .object(fields)
            }

            /// A partial response to show before the server answers; absent fields leave the store untouched.
            nonisolated public struct Character: Sendable {
                public var id: String?
                public var name: String?
                public init(id: String? = nil, name: String? = nil) {
                    self.id = id
                    self.name = name
                }
                public var variable: Baton.Variable {
                    var fields: [String: Baton.Variable] = [:]
                    if let id { fields["id"] = .init(id) }
                    if let name { fields["name"] = .init(name) }
                    return .object(fields)
                }
            }
        }

        /// A partial response to show before the server answers; absent fields leave the store untouched.
        nonisolated public struct SendableResponse: Sendable {
            public var character: Character?
            public init(character: Character? = nil) {
                self.character = character
            }
            public var variable: Baton.Variable {
                var fields: [String: Baton.Variable] = [:]
                if let character { fields["character"] = character.variable }
                return .object(fields)
            }

            /// A partial response to show before the server answers; absent fields leave the store untouched.
            nonisolated public struct Character: Sendable {
                public var id: String?
                public var favorite: Bool?
                public init(id: String? = nil, favorite: Bool? = nil) {
                    self.id = id
                    self.favorite = favorite
                }
                public var variable: Baton.Variable {
                    var fields: [String: Baton.Variable] = [:]
                    if let id { fields["id"] = .init(id) }
                    if let favorite { fields["favorite"] = .init(favorite) }
                    return .object(fields)
                }
            }
        }
    }
}

extension Baton.MutationAction where Op == TestBuilderNames {
    /// Commits the mutation; the optimistic response, if any, shows at once and rebases until the server answers.
    @MainActor @discardableResult
    public func callAsFunction(id: String, favorite: Bool, `self` selfValue: String, optimistic: TestBuilderNames.OptimisticResponse? = nil) async throws -> TestBuilderNames.Data {
        try await self.commit(TestBuilderNames(id: id, favorite: favorite, self: selfValue), optimistic: optimistic?.variable)
    }
}

/// Operation value for `query TestCaughtSpreads`.
nonisolated public struct TestCaughtSpreads: Baton.Query {
    public var id: String
    public var resolution: Baton.OperationHandle<Self>? = nil

    public init(id: String) {
        self.id = id
    }

    public static let name = "TestCaughtSpreads"
    public static let persistedID = "0d9fb324ff48b3e70d0bcc6c3e3df062"
    public static let text = #"""
query TestCaughtSpreads(
  $id: ID!
) {
  character(id: $id) {
    id
    ...TestCaughtProfile_character
    ...TestCaughtStrict_character
  }
  node(id: $id) {
    __typename
    id
    ... on Character {
      ...TestCaughtProfile_character
    }
  }
}

fragment TestCaughtProfile_character on Character {
  name
  origin {
    name
    id
  }
}

fragment TestCaughtStrict_character on Character {
  species
}
"""#

    public var variables: Baton.Variables {
        Baton.Variables(["id": Baton.Variable(self.id)])
    }

    public static func == (lhs: Self, rhs: Self) -> Bool {
        lhs.id == rhs.id
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(self.id)
    }

    @_spi(Generated) public static let plan = Baton.Plan(root: Baton.Selection(type: Types.Query, hasID: false, abstract: false, fields: [
            .linked("character", key: .dynamic(Slots.Query.character_bca4f9), plural: false, lookup: Baton.Lookup(type: Types.Character, key: .variable("id")), selection: Baton.Selection(type: Types.Character, hasID: true, abstract: false, fields: [
                .scalar("id", key: .fixed(Slots.Character.id), kind: .string, list: false),
                .scalar("name", key: .fixed(Slots.Character.name), kind: .string, list: false),
                .linked("origin", key: .fixed(Slots.Character.origin), plural: false, selection: Baton.Selection(type: Types.Location, hasID: true, abstract: false, fields: [
                    .scalar("name", key: .fixed(Slots.Location.name), kind: .string, list: false),
                    .scalar("id", key: .fixed(Slots.Location.id), kind: .string, list: false),
                ])),
                .scalar("species", key: .fixed(Slots.Character.species), kind: .string, list: false),
            ])),
            .linked("node", key: .dynamic(Slots.Query.node_8f7d08), plural: false, lookup: Baton.Lookup(type: nil, possibleTypes: Types.Node_possible, key: .variable("id")), selection: Baton.Selection(type: Types.Node, hasID: true, abstract: true, variants: [
                .init(types: [Types.Character], fields: [
                    .scalar("__typename", key: .fixed(Slots.Character.__typename), kind: .string, list: false),
                    .scalar("id", key: .fixed(Slots.Character.id), kind: .string, list: false),
                    .scalar("name", key: .fixed(Slots.Character.name), kind: .string, list: false, caught: true),
                    .linked("origin", key: .fixed(Slots.Character.origin), plural: false, caught: true, selection: Baton.Selection(type: Types.Location, hasID: true, abstract: false, fields: [
                        .scalar("name", key: .fixed(Slots.Location.name), kind: .string, list: false, caught: true),
                        .scalar("id", key: .fixed(Slots.Location.id), kind: .string, list: false, caught: true),
                    ])),
                ]),
                .init(types: nil, fields: [
                    .scalar("__typename", key: .fixed(Slots.Node.__typename), kind: .string, list: false),
                    .scalar("id", key: .fixed(Slots.Node.id), kind: .string, list: false),
                ]),
            ])),
        ]))

    nonisolated public struct Data: Baton.Lens {
        @_spi(Generated) public let anchor: Baton.Anchor
        @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
        public static let typeName = "Query"
        @MainActor public var character: Character? { anchor.linked(anchor.owner.slot(Slots.Query.character_bca4f9)).map(Character.init(anchor:)) }
        @MainActor public var node: Node? { anchor.linked(anchor.owner.slot(Slots.Query.node_8f7d08)).map(Node.init(anchor:)) }

        nonisolated public struct Character: Baton.Lens {
            @_spi(Generated) public let anchor: Baton.Anchor
            @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
            public static let typeName = "Character"
            @MainActor public var id: String? { anchor.string(Slots.Character.id) }
            @MainActor public var profile: Result<TestCaughtProfile_character, Baton.FieldErrors> {
                typealias Fragment = TestCaughtProfile_character
                let errors = Fragment.fieldErrors(anchor)
                return errors.isEmpty ? .success(.init(anchor: anchor)) : .failure(.init(errors))
            }
            @MainActor public var nulledProfile: TestCaughtProfile_character? {
                typealias Fragment = TestCaughtProfile_character
                guard Fragment.fieldErrors(anchor).isEmpty else { return nil }
                return .init(anchor: anchor)
            }
            @MainActor public var strict: Result<TestCaughtStrict_character, Baton.FieldErrors> {
                typealias Fragment = TestCaughtStrict_character
                let errors = Fragment.fieldErrors(anchor)
                return errors.isEmpty ? .success(.init(anchor: anchor)) : .failure(.init(errors))
            }
            @MainActor public var nulledStrict: TestCaughtStrict_character? {
                typealias Fragment = TestCaughtStrict_character
                guard Fragment.fieldErrors(anchor).isEmpty else { return nil }
                return .init(anchor: anchor)
            }
        }

        nonisolated public struct Node: Baton.Lens {
            @_spi(Generated) public let anchor: Baton.Anchor
            @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
            public static let typeName = "Node"
            @MainActor public var id: String? { anchor.string(AbstractSlots.Node.id.on(anchor.record.type)) }
            @MainActor public var profile: Result<TestCaughtProfile_character?, Baton.FieldErrors> {
                typealias Fragment = TestCaughtProfile_character
                guard anchor.record.is(Types.Character) else { return .success(nil) }
                let errors = Fragment.fieldErrors(anchor)
                return errors.isEmpty ? .success(.init(anchor: anchor)) : .failure(.init(errors))
            }
        }
    }
}

/// Operation value for `mutation TestCommitVariable`.
nonisolated public struct TestCommitVariable: Baton.Mutation {
    public var commit: String

    public init(commit: String) {
        self.commit = commit
    }

    public static let name = "TestCommitVariable"
    public static let persistedID = "74901df28f2929f51d2e12a1d300c09c"
    public static let text = #"""
mutation TestCommitVariable(
  $commit: ID!
) {
  setFavorite(id: $commit, favorite: true) {
    character {
      id
      name
      favorite
    }
  }
}
"""#

    public var variables: Baton.Variables {
        Baton.Variables(["commit": Baton.Variable(self.commit)])
    }

    public static func == (lhs: Self, rhs: Self) -> Bool {
        lhs.commit == rhs.commit
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(self.commit)
    }

    @_spi(Generated) public static let plan = Baton.Plan(root: Baton.Selection(type: Types.Mutation, hasID: false, abstract: false, fields: [
            .linked("setFavorite", key: .fixed(Slots.Mutation.setFavorite), plural: false, selection: Baton.Selection(type: Types.FavoritePayload, hasID: false, abstract: false, fields: [
                .linked("character", key: .fixed(Slots.FavoritePayload.character), plural: false, selection: Baton.Selection(type: Types.Character, hasID: true, abstract: false, fields: [
                    .scalar("id", key: .fixed(Slots.Character.id), kind: .string, list: false),
                    .scalar("name", key: .fixed(Slots.Character.name), kind: .string, list: false),
                    .scalar("favorite", key: .fixed(Slots.Character.favorite), kind: .bool, list: false),
                ])),
            ])),
        ]))

    nonisolated public struct Data: Baton.Lens {
        @_spi(Generated) public let anchor: Baton.Anchor
        @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
        public static let typeName = "Mutation"
        @MainActor public var setFavorite: SetFavorite? { anchor.linked(Slots.Mutation.setFavorite).map(SetFavorite.init(anchor:)) }

        nonisolated public struct SetFavorite: Baton.Lens {
            @_spi(Generated) public let anchor: Baton.Anchor
            @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
            public static let typeName = "FavoritePayload"
            @MainActor public var character: Character? { anchor.linked(Slots.FavoritePayload.character).map(Character.init(anchor:)) }

            nonisolated public struct Character: Baton.Lens {
                @_spi(Generated) public let anchor: Baton.Anchor
                @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
                public static let typeName = "Character"
                @MainActor public var id: String? { anchor.string(Slots.Character.id) }
                @MainActor public var name: String? { anchor.string(Slots.Character.name) }
                @MainActor public var favorite: Bool? { anchor.bool(Slots.Character.favorite) }
            }
        }
    }

    public typealias Action = Baton.MutationAction<Self>

    /// A partial response to show before the server answers; absent fields leave the store untouched.
    nonisolated public struct OptimisticResponse: Sendable {
        public var setFavorite: SetFavorite?
        public init(setFavorite: SetFavorite? = nil) {
            self.setFavorite = setFavorite
        }
        public var variable: Baton.Variable {
            var fields: [String: Baton.Variable] = [:]
            if let setFavorite { fields["setFavorite"] = setFavorite.variable }
            return .object(fields)
        }

        /// A partial response to show before the server answers; absent fields leave the store untouched.
        nonisolated public struct SetFavorite: Sendable {
            public var character: Character?
            public init(character: Character? = nil) {
                self.character = character
            }
            public var variable: Baton.Variable {
                var fields: [String: Baton.Variable] = [:]
                if let character { fields["character"] = character.variable }
                return .object(fields)
            }

            /// A partial response to show before the server answers; absent fields leave the store untouched.
            nonisolated public struct Character: Sendable {
                public var id: String?
                public var name: String?
                public var favorite: Bool?
                public init(id: String? = nil, name: String? = nil, favorite: Bool? = nil) {
                    self.id = id
                    self.name = name
                    self.favorite = favorite
                }
                public var variable: Baton.Variable {
                    var fields: [String: Baton.Variable] = [:]
                    if let id { fields["id"] = .init(id) }
                    if let name { fields["name"] = .init(name) }
                    if let favorite { fields["favorite"] = .init(favorite) }
                    return .object(fields)
                }
            }
        }
    }
}

extension Baton.MutationAction where Op == TestCommitVariable {
    /// Commits the mutation; the optimistic response, if any, shows at once and rebases until the server answers.
    @MainActor @discardableResult
    public func callAsFunction(commit: String, optimistic: TestCommitVariable.OptimisticResponse? = nil) async throws -> TestCommitVariable.Data {
        try await self.commit(TestCommitVariable(commit: commit), optimistic: optimistic?.variable)
    }
}

/// Operation value for `query TestConditionNames`.
nonisolated public struct TestConditionNames: Baton.Query {
    public var id: String
    public var name: String
    public var resolution: Baton.OperationHandle<Self>? = nil

    public init(id: String, name: String) {
        self.id = id
        self.name = name
    }

    public static let name = "TestConditionNames"
    public static let persistedID = "996d89a10b1bacf5ca5f86cf7ad861e3"
    public static let text = #"""
query TestConditionNames(
  $id: ID!
  $name: String!
) {
  namesake(name: $name) {
    __typename
    asCharacter: name
    ... on Character {
      status
    }
    ... on Node {
      __isNode: __typename
      id
    }
  }
  node(id: $id) {
    __typename
    id
    ... on Episode {
      name
    }
    ... on Character {
      name
    }
  }
}
"""#

    public var variables: Baton.Variables {
        Baton.Variables(["id": Baton.Variable(self.id), "name": Baton.Variable(self.name)])
    }

    public static func == (lhs: Self, rhs: Self) -> Bool {
        lhs.id == rhs.id && lhs.name == rhs.name
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(self.id)
        hasher.combine(self.name)
    }

    @_spi(Generated) public static let plan = Baton.Plan(root: Baton.Selection(type: Types.Query, hasID: false, abstract: false, fields: [
            .linked("namesake", key: .dynamic(Slots.Query.namesake_9b6471), plural: false, selection: Baton.Selection(type: Types.Named, hasID: true, abstract: true, variants: [
                .init(types: [Types.Character], fields: [
                    .scalar("__typename", key: .fixed(Slots.Character.__typename), kind: .string, list: false),
                    .scalar("asCharacter", key: .fixed(Slots.Character.name), kind: .string, list: false),
                    .scalar("status", key: .fixed(Slots.Character.status), kind: .string, list: false),
                    .scalar("id", key: .fixed(Slots.Character.id), kind: .string, list: false),
                ]),
                .init(types: [Types.Location], fields: [
                    .scalar("__typename", key: .fixed(Slots.Location.__typename), kind: .string, list: false),
                    .scalar("asCharacter", key: .fixed(Slots.Location.name), kind: .string, list: false),
                    .scalar("id", key: .fixed(Slots.Location.id), kind: .string, list: false),
                ]),
                .init(types: nil, fields: [
                    .scalar("__typename", key: .fixed(Slots.Named.__typename), kind: .string, list: false),
                    .scalar("asCharacter", key: .fixed(Slots.Named.name), kind: .string, list: false),
                ]),
            ])),
            .linked("node", key: .dynamic(Slots.Query.node_8f7d08), plural: false, lookup: Baton.Lookup(type: nil, possibleTypes: Types.Node_possible, key: .variable("id")), selection: Baton.Selection(type: Types.Node, hasID: true, abstract: true, variants: [
                .init(types: [Types.Character, Types.Episode], fields: [
                    .scalar("__typename", key: .fixed(Slots.Node.__typename), kind: .string, list: false),
                    .scalar("id", key: .fixed(Slots.Node.id), kind: .string, list: false),
                    .scalar("name", key: .fixed(Slots.Node.name), kind: .string, list: false),
                ]),
                .init(types: nil, fields: [
                    .scalar("__typename", key: .fixed(Slots.Node.__typename), kind: .string, list: false),
                    .scalar("id", key: .fixed(Slots.Node.id), kind: .string, list: false),
                ]),
            ])),
        ]))

    nonisolated public struct Data: Baton.Lens {
        @_spi(Generated) public let anchor: Baton.Anchor
        @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
        public static let typeName = "Query"
        @MainActor public var namesake: Namesake? { anchor.linked(anchor.owner.slot(Slots.Query.namesake_9b6471)).map(Namesake.init(anchor:)) }
        @MainActor public var node: Node? { anchor.linked(anchor.owner.slot(Slots.Query.node_8f7d08)).map(Node.init(anchor:)) }

        nonisolated public struct Namesake: Baton.Lens {
            @_spi(Generated) public let anchor: Baton.Anchor
            @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
            public static let typeName = "Named"
            @MainActor public var asCharacter: String? { anchor.string(AbstractSlots.Named.name.on(anchor.record.type)) }
            @MainActor public var asCharacter2: AsCharacter2? { anchor.record.is(Types.Character) ? AsCharacter2(anchor: anchor) : nil }

            nonisolated public struct AsCharacter2: Baton.Lens {
                @_spi(Generated) public let anchor: Baton.Anchor
                @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
                public static let typeName = "Character"
                @MainActor public var status: String? { anchor.string(Slots.Character.status) }
            }
        }

        nonisolated public struct Node: Baton.Lens {
            @_spi(Generated) public let anchor: Baton.Anchor
            @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
            public static let typeName = "Node"
            @MainActor public var id: String? { anchor.string(AbstractSlots.Node.id.on(anchor.record.type)) }
            @MainActor public var asCharacter: AsCharacter? { anchor.record.is(Types.Episode) ? AsCharacter(anchor: anchor) : nil }
            @MainActor public var asCharacter2: AsCharacter2? { anchor.record.is(Types.Character) ? AsCharacter2(anchor: anchor) : nil }

            nonisolated public struct AsCharacter: Baton.Lens {
                @_spi(Generated) public let anchor: Baton.Anchor
                @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
                public static let typeName = "Episode"
                @MainActor public var name: String? { anchor.string(Slots.Episode.name) }
            }

            nonisolated public struct AsCharacter2: Baton.Lens {
                @_spi(Generated) public let anchor: Baton.Anchor
                @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
                public static let typeName = "Character"
                @MainActor public var name: String? { anchor.string(Slots.Character.name) }
            }
        }
    }
}

/// Operation value for `query TestEdgesNamesQuery`.
nonisolated public struct TestEdgesNamesQuery: Baton.Query {
    public var id: String
    public var resolution: Baton.OperationHandle<Self>? = nil

    public init(id: String) {
        self.id = id
    }

    public static let name = "TestEdgesNamesQuery"
    public static let persistedID = "92a753811dab9a0b66fc8f686e451eb4"
    public static let text = #"""
query TestEdgesNamesQuery(
  $id: ID!
) {
  character(id: $id) {
    ...TestEdgesNames_character
    id
  }
}

fragment TestEdgesNames_character on Character {
  notes(first: 2) {
    Edges: pageInfo {
      hasNextPage
    }
    edges {
      node {
        id
        text
        __typename
      }
      cursor
    }
    pageInfo {
      endCursor
      hasNextPage
    }
  }
}
"""#

    public var variables: Baton.Variables {
        Baton.Variables(["id": Baton.Variable(self.id)])
    }

    public static func == (lhs: Self, rhs: Self) -> Bool {
        lhs.id == rhs.id
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(self.id)
    }

    @_spi(Generated) public static let plan = Baton.Plan(root: Baton.Selection(type: Types.Query, hasID: false, abstract: false, fields: [
            .linked("character", key: .dynamic(Slots.Query.character_bca4f9), plural: false, lookup: Baton.Lookup(type: Types.Character, key: .variable("id")), selection: Baton.Selection(type: Types.Character, hasID: true, abstract: false, fields: [
                .linked("notes", key: .fixed(Slots.Character.notes_29a6d8), plural: false, connection: Baton.ConnectionPlan(key: .fixed(Slots.Character.__TestEdgesNames_notes_connection), slots: Baton.ConnectionSlots(connection: Types.NoteConnection, edge: Types.NoteEdge, pageInfo: Types.PageInfo)), selection: Baton.Selection(type: Types.NoteConnection, hasID: false, abstract: false, fields: [
                    .linked("Edges", key: .fixed(Slots.NoteConnection.pageInfo), plural: false, selection: Baton.Selection(type: Types.PageInfo, hasID: false, abstract: false, fields: [
                        .scalar("hasNextPage", key: .fixed(Slots.PageInfo.hasNextPage), kind: .bool, list: false),
                    ])),
                    .linked("edges", key: .fixed(Slots.NoteConnection.edges), plural: true, selection: Baton.Selection(type: Types.NoteEdge, hasID: false, abstract: false, fields: [
                        .linked("node", key: .fixed(Slots.NoteEdge.node), plural: false, selection: Baton.Selection(type: Types.Note, hasID: true, abstract: false, fields: [
                            .scalar("__typename", key: .fixed(Slots.Note.__typename), kind: .string, list: false),
                            .scalar("id", key: .fixed(Slots.Note.id), kind: .string, list: false),
                            .scalar("text", key: .fixed(Slots.Note.text), kind: .string, list: false),
                        ])),
                        .scalar("cursor", key: .fixed(Slots.NoteEdge.cursor), kind: .string, list: false),
                    ])),
                    .linked("pageInfo", key: .fixed(Slots.NoteConnection.pageInfo), plural: false, selection: Baton.Selection(type: Types.PageInfo, hasID: false, abstract: false, fields: [
                        .scalar("endCursor", key: .fixed(Slots.PageInfo.endCursor), kind: .string, list: false),
                        .scalar("hasNextPage", key: .fixed(Slots.PageInfo.hasNextPage), kind: .bool, list: false),
                    ])),
                ])),
                .scalar("id", key: .fixed(Slots.Character.id), kind: .string, list: false),
            ])),
        ]))

    nonisolated public struct Data: Baton.Lens {
        @_spi(Generated) public let anchor: Baton.Anchor
        @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
        public static let typeName = "Query"
        @MainActor public var character: Character? { anchor.linked(anchor.owner.slot(Slots.Query.character_bca4f9)).map(Character.init(anchor:)) }

        nonisolated public struct Character: Baton.Lens {
            @_spi(Generated) public let anchor: Baton.Anchor
            @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
            public static let typeName = "Character"
            @MainActor public var testEdgesNames: TestEdgesNames_character { .init(anchor: anchor) }
        }
    }
}

/// Operation value for `query TestEscapedText`.
nonisolated public struct TestEscapedText: Baton.Query {
    public var resolution: Baton.OperationHandle<Self>? = nil

    public init() {
    }

    public static let name = "TestEscapedText"
    public static let persistedID = "e45d6792260fea7beb23f33fa5369c96"
    public static let text = ##"""
query TestEscapedText {
  search(name: "\\#1") {
    __typename
    ... on Node {
      __isNode: __typename
      id
    }
  }
}
"""##

    public var variables: Baton.Variables {
        Baton.Variables([:])
    }

    public static func == (lhs: Self, rhs: Self) -> Bool {
        true
    }

    public func hash(into hasher: inout Hasher) {
    }

    @_spi(Generated) public static let plan = Baton.Plan(root: Baton.Selection(type: Types.Query, hasID: false, abstract: false, fields: [
            .linked("search", key: .fixed(Slots.Query.search_b80531), plural: true, selection: Baton.Selection(type: Types.SearchResult, hasID: true, abstract: true, variants: [
                .init(types: [Types.Character, Types.Episode, Types.Location], fields: [
                    .scalar("__typename", key: .fixed(Slots.SearchResult.__typename), kind: .string, list: false),
                    .scalar("id", key: .fixed(Slots.SearchResult.id), kind: .string, list: false),
                ]),
                .init(types: nil, fields: [
                    .scalar("__typename", key: .fixed(Slots.SearchResult.__typename), kind: .string, list: false),
                ]),
            ])),
        ]))

    nonisolated public struct Data: Baton.Lens {
        @_spi(Generated) public let anchor: Baton.Anchor
        @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
        public static let typeName = "Query"
        @MainActor public var search: Baton.List<Search>? { anchor.list(Slots.Query.search_b80531) }

        nonisolated public struct Search: Baton.Lens {
            @_spi(Generated) public let anchor: Baton.Anchor
            @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
            public static let typeName = "SearchResult"
        }
    }
}

/// Operation value for `query TestFragmentNamedFields`.
nonisolated public struct TestFragmentNamedFields: Baton.Query {
    public var id: String
    public var resolution: Baton.OperationHandle<Self>? = nil

    public init(id: String) {
        self.id = id
    }

    public static let name = "TestFragmentNamedFields"
    public static let persistedID = "67a56714d3b957a723ef0e58f0161910"
    public static let text = #"""
query TestFragmentNamedFields(
  $id: ID!
) {
  character(id: $id) {
    TestCaughtProfile_character: name
    TestCaughtStrict_character: species
    ...TestCaughtProfile_character
    ...TestCaughtStrict_character
    Fragment: status
    ...Fragment
    id
  }
}

fragment Fragment on Character {
  status
}

fragment TestCaughtProfile_character on Character {
  name
  origin {
    name
    id
  }
}

fragment TestCaughtStrict_character on Character {
  species
}
"""#

    public var variables: Baton.Variables {
        Baton.Variables(["id": Baton.Variable(self.id)])
    }

    public static func == (lhs: Self, rhs: Self) -> Bool {
        lhs.id == rhs.id
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(self.id)
    }

    @_spi(Generated) public static let plan = Baton.Plan(root: Baton.Selection(type: Types.Query, hasID: false, abstract: false, fields: [
            .linked("character", key: .dynamic(Slots.Query.character_bca4f9), plural: false, lookup: Baton.Lookup(type: Types.Character, key: .variable("id")), selection: Baton.Selection(type: Types.Character, hasID: true, abstract: false, fields: [
                .scalar("TestCaughtProfile_character", key: .fixed(Slots.Character.name), kind: .string, list: false),
                .scalar("TestCaughtStrict_character", key: .fixed(Slots.Character.species), kind: .string, list: false),
                .scalar("name", key: .fixed(Slots.Character.name), kind: .string, list: false),
                .linked("origin", key: .fixed(Slots.Character.origin), plural: false, selection: Baton.Selection(type: Types.Location, hasID: true, abstract: false, fields: [
                    .scalar("name", key: .fixed(Slots.Location.name), kind: .string, list: false),
                    .scalar("id", key: .fixed(Slots.Location.id), kind: .string, list: false),
                ])),
                .scalar("species", key: .fixed(Slots.Character.species), kind: .string, list: false),
                .scalar("Fragment", key: .fixed(Slots.Character.status), kind: .string, list: false),
                .scalar("status", key: .fixed(Slots.Character.status), kind: .string, list: false),
                .scalar("id", key: .fixed(Slots.Character.id), kind: .string, list: false),
            ])),
        ]))

    nonisolated public struct Data: Baton.Lens {
        @_spi(Generated) public let anchor: Baton.Anchor
        @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
        public static let typeName = "Query"
        @MainActor public var character: Character? { anchor.linked(anchor.owner.slot(Slots.Query.character_bca4f9)).map(Character.init(anchor:)) }

        nonisolated public struct Character: Baton.Lens {
            @_spi(Generated) public let anchor: Baton.Anchor
            @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
            public static let typeName = "Character"
            @MainActor public var TestCaughtProfile_character: String? { anchor.string(Slots.Character.name) }
            @MainActor public var TestCaughtStrict_character: String? { anchor.string(Slots.Character.species) }
            @MainActor public var testCaughtProfile: TestCaughtProfile_character { .init(anchor: anchor) }
            @MainActor public var testCaughtStrict: TestCaughtStrict_character { get throws { try .throwing(anchor) } }
            @MainActor public var caughtProfile: Result<TestCaughtProfile_character, Baton.FieldErrors> {
                typealias Fragment = TestCaughtProfile_character
                let errors = Fragment.fieldErrors(anchor)
                return errors.isEmpty ? .success(.init(anchor: anchor)) : .failure(.init(errors))
            }
            @MainActor public var nulledProfile: TestCaughtProfile_character? {
                typealias Fragment = TestCaughtProfile_character
                guard Fragment.fieldErrors(anchor).isEmpty else { return nil }
                return .init(anchor: anchor)
            }
            @MainActor public var Fragment: String? { anchor.string(Slots.Character.status) }
            @MainActor public var nulledFragment: Fragment? {
                typealias Spread = Fragment
                guard Spread.fieldErrors(anchor).isEmpty else { return nil }
                return .init(anchor: anchor)
            }
        }
    }
}

/// Operation value for `query TestHasherVariable`.
nonisolated public struct TestHasherVariable: Baton.Query {
    public var hasher: String
    public var resolution: Baton.OperationHandle<Self>? = nil

    public init(hasher: String) {
        self.hasher = hasher
    }

    public static let name = "TestHasherVariable"
    public static let persistedID = "2c80978abfd935e0e3e0bd9006ff6e49"
    public static let text = #"""
query TestHasherVariable(
  $hasher: ID!
) {
  character(id: $hasher) {
    id
    name
  }
}
"""#

    public var variables: Baton.Variables {
        Baton.Variables(["hasher": Baton.Variable(self.hasher)])
    }

    public static func == (lhs: Self, rhs: Self) -> Bool {
        lhs.hasher == rhs.hasher
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(self.hasher)
    }

    @_spi(Generated) public static let plan = Baton.Plan(root: Baton.Selection(type: Types.Query, hasID: false, abstract: false, fields: [
            .linked("character", key: .dynamic(Slots.Query.character_662906), plural: false, lookup: Baton.Lookup(type: Types.Character, key: .variable("hasher")), selection: Baton.Selection(type: Types.Character, hasID: true, abstract: false, fields: [
                .scalar("id", key: .fixed(Slots.Character.id), kind: .string, list: false),
                .scalar("name", key: .fixed(Slots.Character.name), kind: .string, list: false),
            ])),
        ]))

    nonisolated public struct Data: Baton.Lens {
        @_spi(Generated) public let anchor: Baton.Anchor
        @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
        public static let typeName = "Query"
        @MainActor public var character: Character? { anchor.linked(anchor.owner.slot(Slots.Query.character_662906)).map(Character.init(anchor:)) }

        nonisolated public struct Character: Baton.Lens {
            @_spi(Generated) public let anchor: Baton.Anchor
            @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
            public static let typeName = "Character"
            @MainActor public var id: String? { anchor.string(Slots.Character.id) }
            @MainActor public var name: String? { anchor.string(Slots.Character.name) }
        }
    }
}

/// Operation value for `query TestLowercaseSpreads`.
nonisolated public struct TestLowercaseSpreads: Baton.Query {
    public var id: String
    public var resolution: Baton.OperationHandle<Self>? = nil

    public init(id: String) {
        self.id = id
    }

    public static let name = "TestLowercaseSpreads"
    public static let persistedID = "bcd9d385f91dc14b5bc18b85c9a1ae84"
    public static let text = #"""
query TestLowercaseSpreads(
  $id: ID!
) {
  character(id: $id) {
    ...testLowercase
    ...testLowercaseRequired
    id
  }
}

fragment testLowercase on Character {
  name
}

fragment testLowercaseRequired on Character {
  origin {
    name
    id
  }
}
"""#

    public var variables: Baton.Variables {
        Baton.Variables(["id": Baton.Variable(self.id)])
    }

    public static func == (lhs: Self, rhs: Self) -> Bool {
        lhs.id == rhs.id
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(self.id)
    }

    @_spi(Generated) public static let plan = Baton.Plan(root: Baton.Selection(type: Types.Query, hasID: false, abstract: false, fields: [
            .linked("character", key: .dynamic(Slots.Query.character_bca4f9), plural: false, lookup: Baton.Lookup(type: Types.Character, key: .variable("id")), selection: Baton.Selection(type: Types.Character, hasID: true, abstract: false, fields: [
                .scalar("name", key: .fixed(Slots.Character.name), kind: .string, list: false),
                .linked("origin", key: .fixed(Slots.Character.origin), plural: false, selection: Baton.Selection(type: Types.Location, hasID: true, abstract: false, fields: [
                    .scalar("name", key: .fixed(Slots.Location.name), kind: .string, list: false),
                    .scalar("id", key: .fixed(Slots.Location.id), kind: .string, list: false),
                ])),
                .scalar("id", key: .fixed(Slots.Character.id), kind: .string, list: false),
            ])),
        ]))

    nonisolated public struct Data: Baton.Lens {
        @_spi(Generated) public let anchor: Baton.Anchor
        @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
        public static let typeName = "Query"
        @MainActor public var character: Character? { anchor.linked(anchor.owner.slot(Slots.Query.character_bca4f9)).map(Character.init(anchor:)) }

        nonisolated public struct Character: Baton.Lens {
            @_spi(Generated) public let anchor: Baton.Anchor
            @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
            public static let typeName = "Character"
            @MainActor public var testLowercase: testLowercase { .init(anchor: anchor) }
            @MainActor public var testLowercaseRequired: testLowercaseRequired? {
                typealias Fragment = testLowercaseRequired
                guard Fragment.satisfied(anchor) else { return nil }
                return .init(anchor: anchor)
            }
        }
    }
}

/// Operation value for `mutation TestModuleNamedPayload`.
nonisolated public struct TestModuleNamedPayload: Baton.Mutation {
    public var id: String

    public init(id: String) {
        self.id = id
    }

    public static let name = "TestModuleNamedPayload"
    public static let persistedID = "d0ecd0de4ae40d2122dbcbeeab23d20b"
    public static let text = #"""
mutation TestModuleNamedPayload(
  $id: ID!
) {
  setFavorite(id: $id, favorite: true) {
    Baton: character {
      id
      Baton: name
    }
  }
}
"""#

    public var variables: Baton.Variables {
        Baton.Variables(["id": Baton.Variable(self.id)])
    }

    public static func == (lhs: Self, rhs: Self) -> Bool {
        lhs.id == rhs.id
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(self.id)
    }

    @_spi(Generated) public static let plan = Baton.Plan(root: Baton.Selection(type: Types.Mutation, hasID: false, abstract: false, fields: [
            .linked("setFavorite", key: .fixed(Slots.Mutation.setFavorite), plural: false, selection: Baton.Selection(type: Types.FavoritePayload, hasID: false, abstract: false, fields: [
                .linked("Baton", key: .fixed(Slots.FavoritePayload.character), plural: false, selection: Baton.Selection(type: Types.Character, hasID: true, abstract: false, fields: [
                    .scalar("id", key: .fixed(Slots.Character.id), kind: .string, list: false),
                    .scalar("Baton", key: .fixed(Slots.Character.name), kind: .string, list: false),
                ])),
            ])),
        ]))

    nonisolated public struct Data: Baton.Lens {
        @_spi(Generated) public let anchor: Baton.Anchor
        @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
        public static let typeName = "Mutation"
        @MainActor public var setFavorite: SetFavorite? { anchor.linked(Slots.Mutation.setFavorite).map(SetFavorite.init(anchor:)) }

        nonisolated public struct SetFavorite: Baton.Lens {
            @_spi(Generated) public let anchor: Baton.Anchor
            @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
            public static let typeName = "FavoritePayload"
            @MainActor public var Baton: BatonLens? { anchor.linked(Slots.FavoritePayload.character).map(BatonLens.init(anchor:)) }

            nonisolated public struct BatonLens: Baton.Lens {
                @_spi(Generated) public let anchor: Baton.Anchor
                @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
                public static let typeName = "Character"
                @MainActor public var id: String? { anchor.string(Slots.Character.id) }
                @MainActor public var Baton: String? { anchor.string(Slots.Character.name) }
            }
        }
    }

    public typealias Action = Baton.MutationAction<Self>

    /// A partial response to show before the server answers; absent fields leave the store untouched.
    nonisolated public struct OptimisticResponse: Sendable {
        public var setFavorite: SetFavorite?
        public init(setFavorite: SetFavorite? = nil) {
            self.setFavorite = setFavorite
        }
        public var variable: Baton.Variable {
            var fields: [String: Baton.Variable] = [:]
            if let setFavorite { fields["setFavorite"] = setFavorite.variable }
            return .object(fields)
        }

        /// A partial response to show before the server answers; absent fields leave the store untouched.
        nonisolated public struct SetFavorite: Sendable {
            public var Baton: BatonResponse?
            public init(Baton: BatonResponse? = nil) {
                self.Baton = Baton
            }
            public var variable: Baton.Variable {
                var fields: [String: Baton.Variable] = [:]
                if let Baton { fields["Baton"] = Baton.variable }
                return .object(fields)
            }

            /// A partial response to show before the server answers; absent fields leave the store untouched.
            nonisolated public struct BatonResponse: Sendable {
                public var id: String?
                public var Baton: String?
                public init(id: String? = nil, Baton: String? = nil) {
                    self.id = id
                    self.Baton = Baton
                }
                public var variable: Baton.Variable {
                    var fields: [String: Baton.Variable] = [:]
                    if let id { fields["id"] = .init(id) }
                    if let Baton { fields["Baton"] = .init(Baton) }
                    return .object(fields)
                }
            }
        }
    }
}

extension Baton.MutationAction where Op == TestModuleNamedPayload {
    /// Commits the mutation; the optimistic response, if any, shows at once and rebases until the server answers.
    @MainActor @discardableResult
    public func callAsFunction(id: String, optimistic: TestModuleNamedPayload.OptimisticResponse? = nil) async throws -> TestModuleNamedPayload.Data {
        try await self.commit(TestModuleNamedPayload(id: id), optimistic: optimistic?.variable)
    }
}

/// Operation value for `query TestProgramNamesQuery`.
nonisolated public struct TestProgramNamesQuery: Baton.Query {
    public var id: String
    public var resolution: Baton.OperationHandle<Self>? = nil

    public init(id: String) {
        self.id = id
    }

    public static let name = "TestProgramNamesQuery"
    public static let persistedID = "a1b90f4a3947b5e81ef88954bdf187a3"
    public static let text = #"""
query TestProgramNamesQuery(
  $id: ID!
) {
  character(id: $id) {
    ...TestProgramNames_character
    id
  }
}

fragment TestCaughtProfile_character on Character {
  name
  origin {
    name
    id
  }
}

fragment TestProgramNames_character on Character {
  testProgramNamesRefetchQuery: origin {
    name
    id
  }
  testCaughtProfile_character: location {
    name
    id
  }
  ...TestCaughtProfile_character
  id
}
"""#

    public var variables: Baton.Variables {
        Baton.Variables(["id": Baton.Variable(self.id)])
    }

    public static func == (lhs: Self, rhs: Self) -> Bool {
        lhs.id == rhs.id
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(self.id)
    }

    @_spi(Generated) public static let plan = Baton.Plan(root: Baton.Selection(type: Types.Query, hasID: false, abstract: false, fields: [
            .linked("character", key: .dynamic(Slots.Query.character_bca4f9), plural: false, lookup: Baton.Lookup(type: Types.Character, key: .variable("id")), selection: Baton.Selection(type: Types.Character, hasID: true, abstract: false, fields: [
                .linked("testProgramNamesRefetchQuery", key: .fixed(Slots.Character.origin), plural: false, selection: Baton.Selection(type: Types.Location, hasID: true, abstract: false, fields: [
                    .scalar("name", key: .fixed(Slots.Location.name), kind: .string, list: false),
                    .scalar("id", key: .fixed(Slots.Location.id), kind: .string, list: false),
                ])),
                .linked("testCaughtProfile_character", key: .fixed(Slots.Character.location), plural: false, selection: Baton.Selection(type: Types.Location, hasID: true, abstract: false, fields: [
                    .scalar("name", key: .fixed(Slots.Location.name), kind: .string, list: false),
                    .scalar("id", key: .fixed(Slots.Location.id), kind: .string, list: false),
                ])),
                .scalar("name", key: .fixed(Slots.Character.name), kind: .string, list: false),
                .linked("origin", key: .fixed(Slots.Character.origin), plural: false, selection: Baton.Selection(type: Types.Location, hasID: true, abstract: false, fields: [
                    .scalar("name", key: .fixed(Slots.Location.name), kind: .string, list: false),
                    .scalar("id", key: .fixed(Slots.Location.id), kind: .string, list: false),
                ])),
                .scalar("id", key: .fixed(Slots.Character.id), kind: .string, list: false),
            ])),
        ]))

    nonisolated public struct Data: Baton.Lens {
        @_spi(Generated) public let anchor: Baton.Anchor
        @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
        public static let typeName = "Query"
        @MainActor public var character: Character? { anchor.linked(anchor.owner.slot(Slots.Query.character_bca4f9)).map(Character.init(anchor:)) }

        nonisolated public struct Character: Baton.Lens {
            @_spi(Generated) public let anchor: Baton.Anchor
            @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
            public static let typeName = "Character"
            @MainActor public var testProgramNames: TestProgramNames_character { .init(anchor: anchor) }
        }
    }
}

/// Operation value for `query TestProgramNamesRefetchQuery`.
nonisolated public struct TestProgramNamesRefetchQuery: Baton.Query {
    public var id: String
    public var resolution: Baton.OperationHandle<Self>? = nil

    public init(id: String) {
        self.id = id
    }

    public static let name = "TestProgramNamesRefetchQuery"
    public static let persistedID = "34337398903367958287f89c6e28d4f2"
    public static let text = #"""
query TestProgramNamesRefetchQuery(
  $id: ID!
) {
  node(id: $id) {
    __typename
    ...TestProgramNames_character
    id
  }
}

fragment TestCaughtProfile_character on Character {
  name
  origin {
    name
    id
  }
}

fragment TestProgramNames_character on Character {
  testProgramNamesRefetchQuery: origin {
    name
    id
  }
  testCaughtProfile_character: location {
    name
    id
  }
  ...TestCaughtProfile_character
  id
}
"""#

    public var variables: Baton.Variables {
        Baton.Variables(["id": Baton.Variable(self.id)])
    }

    public static func == (lhs: Self, rhs: Self) -> Bool {
        lhs.id == rhs.id
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(self.id)
    }

    @_spi(Generated) public static let plan = Baton.Plan(root: Baton.Selection(type: Types.Query, hasID: false, abstract: false, fields: [
            .linked("node", key: .dynamic(Slots.Query.node_8f7d08), plural: false, lookup: Baton.Lookup(type: nil, possibleTypes: Types.Node_possible, key: .variable("id")), selection: Baton.Selection(type: Types.Node, hasID: true, abstract: true, variants: [
                .init(types: [Types.Character], fields: [
                    .scalar("__typename", key: .fixed(Slots.Character.__typename), kind: .string, list: false),
                    .scalar("id", key: .fixed(Slots.Character.id), kind: .string, list: false),
                    .linked("testProgramNamesRefetchQuery", key: .fixed(Slots.Character.origin), plural: false, selection: Baton.Selection(type: Types.Location, hasID: true, abstract: false, fields: [
                        .scalar("name", key: .fixed(Slots.Location.name), kind: .string, list: false),
                        .scalar("id", key: .fixed(Slots.Location.id), kind: .string, list: false),
                    ])),
                    .linked("testCaughtProfile_character", key: .fixed(Slots.Character.location), plural: false, selection: Baton.Selection(type: Types.Location, hasID: true, abstract: false, fields: [
                        .scalar("name", key: .fixed(Slots.Location.name), kind: .string, list: false),
                        .scalar("id", key: .fixed(Slots.Location.id), kind: .string, list: false),
                    ])),
                    .scalar("name", key: .fixed(Slots.Character.name), kind: .string, list: false),
                    .linked("origin", key: .fixed(Slots.Character.origin), plural: false, selection: Baton.Selection(type: Types.Location, hasID: true, abstract: false, fields: [
                        .scalar("name", key: .fixed(Slots.Location.name), kind: .string, list: false),
                        .scalar("id", key: .fixed(Slots.Location.id), kind: .string, list: false),
                    ])),
                ]),
                .init(types: nil, fields: [
                    .scalar("__typename", key: .fixed(Slots.Node.__typename), kind: .string, list: false),
                    .scalar("id", key: .fixed(Slots.Node.id), kind: .string, list: false),
                ]),
            ])),
        ]))

    nonisolated public struct Data: Baton.Lens {
        @_spi(Generated) public let anchor: Baton.Anchor
        @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
        public static let typeName = "Query"
        @MainActor public var node: Node? { anchor.linked(anchor.owner.slot(Slots.Query.node_8f7d08)).map(Node.init(anchor:)) }

        nonisolated public struct Node: Baton.Lens {
            @_spi(Generated) public let anchor: Baton.Anchor
            @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
            public static let typeName = "Node"
            @MainActor public var testProgramNames: TestProgramNames_character? {
                guard anchor.record.is(Types.Character) else { return nil }
                return .init(anchor: anchor)
            }
        }
    }
}

/// Operation value for `query TestSpreadNames`.
nonisolated public struct TestSpreadNames: Baton.Query {
    public var id: String
    public var resolution: Baton.OperationHandle<Self>? = nil

    public init(id: String) {
        self.id = id
    }

    public static let name = "TestSpreadNames"
    public static let persistedID = "2fe130f1c33827440491d07eada160bf"
    public static let text = #"""
query TestSpreadNames(
  $id: ID!
) {
  character(id: $id) {
    testCaughtStrict: species
    ...TestCaughtStrict_character
    id
  }
}

fragment TestCaughtStrict_character on Character {
  species
}
"""#

    public var variables: Baton.Variables {
        Baton.Variables(["id": Baton.Variable(self.id)])
    }

    public static func == (lhs: Self, rhs: Self) -> Bool {
        lhs.id == rhs.id
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(self.id)
    }

    @_spi(Generated) public static let plan = Baton.Plan(root: Baton.Selection(type: Types.Query, hasID: false, abstract: false, fields: [
            .linked("character", key: .dynamic(Slots.Query.character_bca4f9), plural: false, lookup: Baton.Lookup(type: Types.Character, key: .variable("id")), selection: Baton.Selection(type: Types.Character, hasID: true, abstract: false, fields: [
                .scalar("testCaughtStrict", key: .fixed(Slots.Character.species), kind: .string, list: false),
                .scalar("species", key: .fixed(Slots.Character.species), kind: .string, list: false),
                .scalar("id", key: .fixed(Slots.Character.id), kind: .string, list: false),
            ])),
        ]))

    nonisolated public struct Data: Baton.Lens {
        @_spi(Generated) public let anchor: Baton.Anchor
        @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
        public static let typeName = "Query"
        @MainActor public var character: Character? { anchor.linked(anchor.owner.slot(Slots.Query.character_bca4f9)).map(Character.init(anchor:)) }

        nonisolated public struct Character: Baton.Lens {
            @_spi(Generated) public let anchor: Baton.Anchor
            @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
            public static let typeName = "Character"
            @MainActor public var testCaughtStrict: String? { anchor.string(Slots.Character.species) }
            @MainActor public var testCaughtStrict_character: TestCaughtStrict_character { get throws { try .throwing(anchor) } }
        }
    }
}

