// Generated by batonc. Do not edit.
import Foundation
@_spi(Generated) import Baton

/// Lens for `fragment TestRootNotes_query on Query`.
nonisolated public struct TestRootNotes_query: Baton.Lens {
    @_spi(Generated) public let anchor: Baton.Anchor
    @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
    @MainActor public var notes: Notes { Notes(anchor: anchor.requiredLinked(Slots.Query.__TestRootNotes_notes_connection, type: Types.NoteConnection)) }
    /// How the fragment is fetched again: `TestRootNotesPaginationQuery` with the lens's variables.
    @_spi(Generated) public static let refetchable: Baton.Refetch = .init(variables: ["count", "cursor"], identifier: nil, identity: nil, first: "count", after: "cursor", last: nil, before: nil)
    /// Fetches the fragment again through `TestRootNotesPaginationQuery` with its current variables; the records update in place.
    @MainActor public func refetch() async throws {
        typealias Query = TestRootNotesPaginationQuery
        try await anchor.refetch(Query.self, Self.refetchable)
    }

    nonisolated public struct Notes: Baton.Lens {
        @_spi(Generated) public let anchor: Baton.Anchor
        @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
        @MainActor public var totalCount: Int { anchor.requiredInt(Slots.NoteConnection.totalCount) }
        @MainActor public var edges: Baton.List<Edges>? { anchor.list(Slots.NoteConnection.edges) }
        @MainActor public var pageInfo: PageInfo { PageInfo(anchor: anchor.requiredLinked(Slots.NoteConnection.pageInfo, type: Types.PageInfo)) }
        /// The connection's slots: edges, nodes, cursors and the page info, for the store's merge and the state below.
        @_spi(Generated) public static let connection: Baton.ConnectionSlots = .init(connection: Types.NoteConnection, edge: Types.NoteEdge, pageInfo: Types.PageInfo)
        /// The edges' nodes, in order, without nulls.
        @MainActor public var nodes: [Edges.Node] { anchor.nodes(Self.connection) }
        /// Whether the server has edges after the last one, from the merged `pageInfo`.
        @MainActor public var hasNext: Bool { anchor.hasNext(Self.connection) }
        @MainActor public var hasPrevious: Bool { anchor.hasPrevious(Self.connection) }
        @MainActor public var isLoadingNext: Bool { anchor.isLoadingNext(Self.connection) }
        @MainActor public var isLoadingPrevious: Bool { anchor.isLoadingPrevious(Self.connection) }
        /// Relay's connection id, for the `connections` argument of the edge directives.
        @MainActor public var connectionID: String { anchor.record.key }
        /// Fetches the next `count` edges through `TestRootNotesPaginationQuery` and appends them; a no-op while loading or at the end.
        @MainActor public func loadNext(_ count: Int = 2) async throws {
            typealias Query = TestRootNotesPaginationQuery
            typealias Fragment = TestRootNotes_query
            try await anchor.loadNext(Query.self, Self.connection, Fragment.refetchable, count: count)
        }

        nonisolated public struct Edges: Baton.Lens {
            @_spi(Generated) public let anchor: Baton.Anchor
            @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
            @MainActor public var node: Node? { anchor.linked(Slots.NoteEdge.node).map(Node.init(anchor:)) }
            @MainActor public var cursor: String { anchor.requiredString(Slots.NoteEdge.cursor) }

            nonisolated public struct Node: Baton.Lens {
                @_spi(Generated) public let anchor: Baton.Anchor
                @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
                @MainActor public var id: String? { anchor.string(Slots.Note.id) }
                @MainActor public var text: String? { anchor.string(Slots.Note.text) }
            }
        }

        nonisolated public struct PageInfo: Baton.Lens {
            @_spi(Generated) public let anchor: Baton.Anchor
            @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
            @MainActor public var endCursor: String? { anchor.string(Slots.PageInfo.endCursor) }
            @MainActor public var hasNextPage: Bool { anchor.requiredBool(Slots.PageInfo.hasNextPage) }
        }
    }
}

/// Operation value for `query TestRootNotesPaginationQuery`.
nonisolated public struct TestRootNotesPaginationQuery: Baton.Query {
    public var count: Int?
    public var cursor: String?
    @_spi(Generated) public var resolution: Baton.OperationHandle<Self>? = nil

    public init(count: Int? = nil, cursor: String? = nil) {
        self.count = count
        self.cursor = cursor
    }

    public static let name = "TestRootNotesPaginationQuery"
    public static let document: Baton.Document = .text(#"""
query TestRootNotesPaginationQuery(
  $count: Int = 2
  $cursor: String
) {
  ...TestRootNotes_query_1G22uz
}

fragment TestRootNotes_query_1G22uz on Query {
  notes(first: $count, after: $cursor) {
    totalCount
    edges {
      node {
        id
        text
        __typename
      }
      cursor
    }
    pageInfo {
      endCursor
      hasNextPage
    }
  }
}
"""#)

    public var variables: Baton.Variables {
        Baton.Variables(["count": Baton.Variable(self.count), "cursor": Baton.Variable(self.cursor)])
    }

    public static func == (lhs: Self, rhs: Self) -> Bool {
        lhs.count == rhs.count && lhs.cursor == rhs.cursor
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(self.count)
        hasher.combine(self.cursor)
    }

    @_spi(Generated) public static let plan = Baton.Plan(root: selection0, transient: Types.transient)
    private static let selection0: Baton.Selection = Baton.Selection(type: Types.Query, key: [], abstract: false, fields: [
        .linked("notes", key: .dynamic(Slots.Query.notes_a9400e), plural: false, connection: Baton.ConnectionPlan(key: .fixed(Slots.Query.__TestRootNotes_notes_connection), slots: Baton.ConnectionSlots(connection: Types.NoteConnection, edge: Types.NoteEdge, pageInfo: Types.PageInfo), after: .variable("cursor")), selection: selection1),
    ])
    private static let selection1: Baton.Selection = Baton.Selection(type: Types.NoteConnection, key: [], abstract: false, fields: [
        .scalar("totalCount", key: .fixed(Slots.NoteConnection.totalCount), kind: .int, list: false),
        .linked("edges", key: .fixed(Slots.NoteConnection.edges), plural: true, selection: selection3),
        .linked("pageInfo", key: .fixed(Slots.NoteConnection.pageInfo), plural: false, selection: selection2),
    ])
    private static let selection2: Baton.Selection = Baton.Selection(type: Types.PageInfo, key: [], abstract: false, fields: [
        .scalar("endCursor", key: .fixed(Slots.PageInfo.endCursor), kind: .string, list: false),
        .scalar("hasNextPage", key: .fixed(Slots.PageInfo.hasNextPage), kind: .bool, list: false),
    ])
    private static let selection3: Baton.Selection = Baton.Selection(type: Types.NoteEdge, key: [], abstract: false, fields: [
        .linked("node", key: .fixed(Slots.NoteEdge.node), plural: false, selection: selection4),
        .scalar("cursor", key: .fixed(Slots.NoteEdge.cursor), kind: .string, list: false),
    ])
    private static let selection4: Baton.Selection = Baton.Selection(type: Types.Note, key: ["id"], abstract: false, fields: [
        .scalar("__typename", key: .fixed(Slots.Note.__typename), kind: .string, list: false),
        .scalar("id", key: .fixed(Slots.Note.id), kind: .string, list: false),
        .scalar("text", key: .fixed(Slots.Note.text), kind: .string, list: false),
    ])

    nonisolated public struct Data: Baton.Lens {
        @_spi(Generated) public let anchor: Baton.Anchor
        @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
        @MainActor public var testRootNotes: TestRootNotes_query {
            let bound = anchor.binding(Sites.TestRootNotesPaginationQuery_testRootNotes) { () -> [String: Baton.Variable?] in ["count": anchor.variables["count"], "cursor": anchor.variables["cursor"]] }
            return .init(anchor: bound.entering())
        }
    }
}

/// Operation value for `query TestRootNotesQuery`.
nonisolated public struct TestRootNotesQuery: Baton.Query {
    @_spi(Generated) public var resolution: Baton.OperationHandle<Self>? = nil

    public init() {
    }

    public static let name = "TestRootNotesQuery"
    public static let document: Baton.Document = .text(#"""
query TestRootNotesQuery {
  ...TestRootNotes_query
}

fragment TestRootNotes_query on Query {
  notes(first: 2) {
    totalCount
    edges {
      node {
        id
        text
        __typename
      }
      cursor
    }
    pageInfo {
      endCursor
      hasNextPage
    }
  }
}
"""#)

    public var variables: Baton.Variables {
        Baton.Variables([:])
    }

    public static func == (lhs: Self, rhs: Self) -> Bool {
        true
    }

    public func hash(into hasher: inout Hasher) {
    }

    @_spi(Generated) public static let plan = Baton.Plan(root: selection0, transient: Types.transient)
    private static let selection0: Baton.Selection = Baton.Selection(type: Types.Query, key: [], abstract: false, fields: [
        .linked("notes", key: .fixed(Slots.Query.notes_29a6d8), plural: false, connection: Baton.ConnectionPlan(key: .fixed(Slots.Query.__TestRootNotes_notes_connection), slots: Baton.ConnectionSlots(connection: Types.NoteConnection, edge: Types.NoteEdge, pageInfo: Types.PageInfo)), selection: selection1),
    ])
    private static let selection1: Baton.Selection = Baton.Selection(type: Types.NoteConnection, key: [], abstract: false, fields: [
        .scalar("totalCount", key: .fixed(Slots.NoteConnection.totalCount), kind: .int, list: false),
        .linked("edges", key: .fixed(Slots.NoteConnection.edges), plural: true, selection: selection3),
        .linked("pageInfo", key: .fixed(Slots.NoteConnection.pageInfo), plural: false, selection: selection2),
    ])
    private static let selection2: Baton.Selection = Baton.Selection(type: Types.PageInfo, key: [], abstract: false, fields: [
        .scalar("endCursor", key: .fixed(Slots.PageInfo.endCursor), kind: .string, list: false),
        .scalar("hasNextPage", key: .fixed(Slots.PageInfo.hasNextPage), kind: .bool, list: false),
    ])
    private static let selection3: Baton.Selection = Baton.Selection(type: Types.NoteEdge, key: [], abstract: false, fields: [
        .linked("node", key: .fixed(Slots.NoteEdge.node), plural: false, selection: selection4),
        .scalar("cursor", key: .fixed(Slots.NoteEdge.cursor), kind: .string, list: false),
    ])
    private static let selection4: Baton.Selection = Baton.Selection(type: Types.Note, key: ["id"], abstract: false, fields: [
        .scalar("__typename", key: .fixed(Slots.Note.__typename), kind: .string, list: false),
        .scalar("id", key: .fixed(Slots.Note.id), kind: .string, list: false),
        .scalar("text", key: .fixed(Slots.Note.text), kind: .string, list: false),
    ])

    nonisolated public struct Data: Baton.Lens {
        @_spi(Generated) public let anchor: Baton.Anchor
        @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
        @MainActor public var testRootNotes: TestRootNotes_query {
            let bound = anchor.binding(Sites.TestRootNotesQuery_testRootNotes) { () -> [String: Baton.Variable?] in ["count": .int(2), "cursor": .null] }
            return .init(anchor: bound.entering())
        }
    }
}

