// Generated by batonc. Do not edit.
import Baton

/// Operation value for `query TestTokenizerQuery`.
public struct TestTokenizerQuery: Baton.Operation {
    public var resolution: Baton.OperationHandle<Self>? = nil

    public init() {
    }

    public static let name = "TestTokenizerQuery"
    public static let kind = Baton.OperationKind.query
    public static let persistedID = "504409d6f5f972bacc91cd4b4546bf53"
    public static let text = #"""
query TestTokenizerQuery {
  tokenizer {
    id
    text
    strings
    count
    counts
    ratio
    ratios
    flag
    flags
    json
    jsons
  }
}
"""#

    public var variables: Baton.Variables {
        Baton.Variables([:])
    }

    public static func == (lhs: Self, rhs: Self) -> Bool {
        true
    }

    public func hash(into hasher: inout Hasher) {
    }

    public static let plan = Baton.Plan(root: Baton.Selection(type: Types.Query, hasID: false, abstract: false, fields: [
            .linked("tokenizer", key: .fixed(Slots.Query_tokenizer), plural: false, selection: Baton.Selection(type: Types.Tokenizer, hasID: true, abstract: false, fields: [
                .scalar("id", key: .fixed(Slots.Tokenizer_id), kind: .string, list: false),
                .scalar("text", key: .fixed(Slots.Tokenizer_text), kind: .string, list: false),
                .scalar("strings", key: .fixed(Slots.Tokenizer_strings), kind: .string, list: true),
                .scalar("count", key: .fixed(Slots.Tokenizer_count), kind: .int, list: false),
                .scalar("counts", key: .fixed(Slots.Tokenizer_counts), kind: .int, list: true),
                .scalar("ratio", key: .fixed(Slots.Tokenizer_ratio), kind: .double, list: false),
                .scalar("ratios", key: .fixed(Slots.Tokenizer_ratios), kind: .double, list: true),
                .scalar("flag", key: .fixed(Slots.Tokenizer_flag), kind: .bool, list: false),
                .scalar("flags", key: .fixed(Slots.Tokenizer_flags), kind: .bool, list: true),
                .scalar("json", key: .fixed(Slots.Tokenizer_json), kind: .custom, list: false),
                .scalar("jsons", key: .fixed(Slots.Tokenizer_jsons), kind: .custom, list: true),
            ])),
        ]))

    public struct Data: Baton.Lens {
        public let anchor: Baton.Anchor
        public init(anchor: Baton.Anchor) { self.anchor = anchor }
        public static let typeName = "Query"
        @MainActor public var tokenizer: Tokenizer? { anchor.linked(Slots.Query_tokenizer).map(Tokenizer.init(anchor:)) }

        public struct Tokenizer: Baton.Lens {
            public let anchor: Baton.Anchor
            public init(anchor: Baton.Anchor) { self.anchor = anchor }
            public static let typeName = "Tokenizer"
            @MainActor public var id: String? { anchor.string(Slots.Tokenizer_id) }
            @MainActor public var text: String? { anchor.string(Slots.Tokenizer_text) }
            @MainActor public var strings: [String]? { anchor.strings(Slots.Tokenizer_strings) }
            @MainActor public var count: Int? { anchor.int(Slots.Tokenizer_count) }
            @MainActor public var counts: [Int]? { anchor.ints(Slots.Tokenizer_counts) }
            @MainActor public var ratio: Double? { anchor.double(Slots.Tokenizer_ratio) }
            @MainActor public var ratios: [Double]? { anchor.doubles(Slots.Tokenizer_ratios) }
            @MainActor public var flag: Bool? { anchor.bool(Slots.Tokenizer_flag) }
            @MainActor public var flags: [Bool]? { anchor.bools(Slots.Tokenizer_flags) }
            @MainActor public var json: String? { anchor.string(Slots.Tokenizer_json) }
            @MainActor public var jsons: [String]? { anchor.strings(Slots.Tokenizer_jsons) }
        }
    }
}

