// Generated by batonc. Do not edit.
import Foundation
@_spi(Generated) import Baton

/// Operation value for `query TestTokenizerQuery`.
nonisolated public struct TestTokenizerQuery: Baton.Query {
    public var resolution: Baton.OperationHandle<Self>? = nil

    public init() {
    }

    public static let name = "TestTokenizerQuery"
    public static let document: Baton.Document = .text(#"""
query TestTokenizerQuery {
  tokenizer {
    id
    text
    strings
    count
    counts
    ratio
    ratios
    flag
    flags
    json
    jsons
  }
}
"""#)

    public var variables: Baton.Variables {
        Baton.Variables([:])
    }

    public static func == (lhs: Self, rhs: Self) -> Bool {
        true
    }

    public func hash(into hasher: inout Hasher) {
    }

    @_spi(Generated) public static let plan = Baton.Plan(root: Baton.Selection(type: Types.Query, key: [], abstract: false, fields: [
            .linked("tokenizer", key: .fixed(Slots.Query.tokenizer), plural: false, selection: Baton.Selection(type: Types.Tokenizer, key: ["id"], abstract: false, fields: [
                .scalar("id", key: .fixed(Slots.Tokenizer.id), kind: .string, list: false),
                .scalar("text", key: .fixed(Slots.Tokenizer.text), kind: .string, list: false),
                .scalar("strings", key: .fixed(Slots.Tokenizer.strings), kind: .string, list: true),
                .scalar("count", key: .fixed(Slots.Tokenizer.count), kind: .int, list: false),
                .scalar("counts", key: .fixed(Slots.Tokenizer.counts), kind: .int, list: true),
                .scalar("ratio", key: .fixed(Slots.Tokenizer.ratio), kind: .double, list: false),
                .scalar("ratios", key: .fixed(Slots.Tokenizer.ratios), kind: .double, list: true),
                .scalar("flag", key: .fixed(Slots.Tokenizer.flag), kind: .bool, list: false),
                .scalar("flags", key: .fixed(Slots.Tokenizer.flags), kind: .bool, list: true),
                .scalar("json", key: .fixed(Slots.Tokenizer.json), kind: .custom, list: false),
                .scalar("jsons", key: .fixed(Slots.Tokenizer.jsons), kind: .custom, list: true),
            ])),
        ]), transient: Types.transient)

    nonisolated public struct Data: Baton.Lens {
        @_spi(Generated) public let anchor: Baton.Anchor
        @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
        public static let typeName = "Query"
        @MainActor public var tokenizer: Tokenizer? { anchor.linked(Slots.Query.tokenizer).map(Tokenizer.init(anchor:)) }

        nonisolated public struct Tokenizer: Baton.Lens {
            @_spi(Generated) public let anchor: Baton.Anchor
            @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
            public static let typeName = "Tokenizer"
            @MainActor public var id: String? { anchor.string(Slots.Tokenizer.id) }
            @MainActor public var text: String? { anchor.string(Slots.Tokenizer.text) }
            @MainActor public var strings: [String?]? { anchor.nullableStrings(Slots.Tokenizer.strings) }
            @MainActor public var count: Int? { anchor.int(Slots.Tokenizer.count) }
            @MainActor public var counts: [Int?]? { anchor.nullableInts(Slots.Tokenizer.counts) }
            @MainActor public var ratio: Double? { anchor.double(Slots.Tokenizer.ratio) }
            @MainActor public var ratios: [Double?]? { anchor.nullableDoubles(Slots.Tokenizer.ratios) }
            @MainActor public var flag: Bool? { anchor.bool(Slots.Tokenizer.flag) }
            @MainActor public var flags: [Bool?]? { anchor.nullableBools(Slots.Tokenizer.flags) }
            @MainActor public var json: String? { anchor.string(Slots.Tokenizer.json) }
            @MainActor public var jsons: [String?]? { anchor.nullableStrings(Slots.Tokenizer.jsons) }
        }
    }
}

