// Generated by batonc. Do not edit.
import Foundation
@_spi(Generated) import Baton

/// Lens for `fragment TestFavorite_character on Character`.
nonisolated public struct TestFavorite_character: Baton.Lens {
    @_spi(Generated) public let anchor: Baton.Anchor
    @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
    public static let typeName = "Character"
    @MainActor public var id: String? { anchor.string(Slots.Character.id) }
    @MainActor public var name: String? { anchor.string(Slots.Character.name) }
    @MainActor public var favorite: Bool? { anchor.bool(Slots.Character.favorite) }
}

/// Lens for `fragment TestRenamePayload_mutation on Mutation`.
nonisolated public struct TestRenamePayload_mutation: Baton.Lens {
    @_spi(Generated) public let anchor: Baton.Anchor
    @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
    public static let typeName = "Mutation"
    @MainActor public var rename: Rename? { anchor.linked(Slots.Mutation.rename).map(Rename.init(anchor:)) }

    nonisolated public struct Rename: Baton.Lens {
        @_spi(Generated) public let anchor: Baton.Anchor
        @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
        public static let typeName = "FavoritePayload"
        @MainActor public var character: Character? { anchor.linked(Slots.FavoritePayload.character).map(Character.init(anchor:)) }

        nonisolated public struct Character: Baton.Lens {
            @_spi(Generated) public let anchor: Baton.Anchor
            @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
            public static let typeName = "Character"
            @MainActor public var id: String? { anchor.string(Slots.Character.id) }
            @MainActor public var name: String? { anchor.string(Slots.Character.name) }
        }
    }
}

/// Operation value for `query TestNode`.
nonisolated public struct TestNode: Baton.Query {
    public var id: String
    public var resolution: Baton.OperationHandle<Self>? = nil

    public init(id: String) {
        self.id = id
    }

    public static let name = "TestNode"
    public static let persistedID = "2304788bc851c146c51814dfce6bce4d"
    public static let text = #"""
query TestNode(
  $id: ID!
) {
  node(id: $id) {
    __typename
    ... on Character {
      id
      name
    }
    ... on Episode {
      id
      name
    }
    id
  }
}
"""#

    public var variables: Baton.Variables {
        Baton.Variables(["id": Baton.Variable(self.id)])
    }

    public static func == (lhs: Self, rhs: Self) -> Bool {
        lhs.id == rhs.id
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(self.id)
    }

    @_spi(Generated) public static let plan = Baton.Plan(root: Baton.Selection(type: Types.Query, key: [], abstract: false, fields: [
            .linked("node", key: .dynamic(Slots.Query.node_8f7d08), plural: false, lookup: Baton.Lookup(type: nil, possibleTypes: Types.Node_keyed, key: [.variable("id")]), selection: Baton.Selection(type: Types.Node, key: ["id"], abstract: true, variants: [
                .init(types: [Types.Character, Types.Episode], key: ["id"], fields: [
                    .scalar("__typename", key: .fixed(Slots.Node.__typename), kind: .string, list: false),
                    .scalar("id", key: .fixed(Slots.Node.id), kind: .string, list: false),
                    .scalar("name", key: .fixed(Slots.Node.name), kind: .string, list: false),
                ]),
                .init(types: nil, fields: [
                    .scalar("__typename", key: .fixed(Slots.Node.__typename), kind: .string, list: false),
                    .scalar("id", key: .fixed(Slots.Node.id), kind: .string, list: false),
                ]),
            ])),
        ]), transient: Types.transient)

    nonisolated public struct Data: Baton.Lens {
        @_spi(Generated) public let anchor: Baton.Anchor
        @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
        public static let typeName = "Query"
        @MainActor public var node: Node? { anchor.linked(anchor.owner.slot(Slots.Query.node_8f7d08)).map(Node.init(anchor:)) }

        nonisolated public struct Node: Baton.Lens {
            @_spi(Generated) public let anchor: Baton.Anchor
            @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
            public static let typeName = "Node"
            @MainActor public var asCharacter: AsCharacter? { anchor.record.is(Types.Character) ? AsCharacter(anchor: anchor) : nil }
            @MainActor public var asEpisode: AsEpisode? { anchor.record.is(Types.Episode) ? AsEpisode(anchor: anchor) : nil }

            nonisolated public struct AsCharacter: Baton.Lens {
                @_spi(Generated) public let anchor: Baton.Anchor
                @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
                public static let typeName = "Character"
                @MainActor public var id: String? { anchor.string(Slots.Character.id) }
                @MainActor public var name: String? { anchor.string(Slots.Character.name) }
            }

            nonisolated public struct AsEpisode: Baton.Lens {
                @_spi(Generated) public let anchor: Baton.Anchor
                @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
                public static let typeName = "Episode"
                @MainActor public var id: String? { anchor.string(Slots.Episode.id) }
                @MainActor public var name: String? { anchor.string(Slots.Episode.name) }
            }
        }
    }
}

/// Operation value for `mutation TestRename`.
nonisolated public struct TestRename: Baton.Mutation {
    public var id: String
    public var name: String

    public init(id: String, name: String) {
        self.id = id
        self.name = name
    }

    public static let name = "TestRename"
    public static let persistedID = "bbbb03578f7d58a0b3956defbc951f96"
    public static let text = #"""
mutation TestRename(
  $id: ID!
  $name: String!
) {
  rename(id: $id, name: $name) {
    character {
      id
      name
    }
  }
}
"""#

    public var variables: Baton.Variables {
        Baton.Variables(["id": Baton.Variable(self.id), "name": Baton.Variable(self.name)])
    }

    public static func == (lhs: Self, rhs: Self) -> Bool {
        lhs.id == rhs.id && lhs.name == rhs.name
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(self.id)
        hasher.combine(self.name)
    }

    @_spi(Generated) public static let plan = Baton.Plan(root: Baton.Selection(type: Types.Mutation, key: [], abstract: false, fields: [
            .linked("rename", key: .fixed(Slots.Mutation.rename), plural: false, selection: Baton.Selection(type: Types.FavoritePayload, key: [], abstract: false, fields: [
                .linked("character", key: .fixed(Slots.FavoritePayload.character), plural: false, selection: Baton.Selection(type: Types.Character, key: ["id"], abstract: false, fields: [
                    .scalar("id", key: .fixed(Slots.Character.id), kind: .string, list: false),
                    .scalar("name", key: .fixed(Slots.Character.name), kind: .string, list: false),
                ])),
            ])),
        ]), transient: Types.transient)

    nonisolated public struct Data: Baton.Lens {
        @_spi(Generated) public let anchor: Baton.Anchor
        @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
        public static let typeName = "Mutation"
        @MainActor public var rename: Rename? { anchor.linked(Slots.Mutation.rename).map(Rename.init(anchor:)) }

        nonisolated public struct Rename: Baton.Lens {
            @_spi(Generated) public let anchor: Baton.Anchor
            @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
            public static let typeName = "FavoritePayload"
            @MainActor public var character: Character? { anchor.linked(Slots.FavoritePayload.character).map(Character.init(anchor:)) }

            nonisolated public struct Character: Baton.Lens {
                @_spi(Generated) public let anchor: Baton.Anchor
                @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
                public static let typeName = "Character"
                @MainActor public var id: String? { anchor.string(Slots.Character.id) }
                @MainActor public var name: String? { anchor.string(Slots.Character.name) }
            }
        }
    }

    public typealias Action = Baton.MutationAction<Self>

    /// A partial response to show before the server answers; absent fields leave the store untouched.
    nonisolated public struct OptimisticResponse: Sendable {
        public var rename: Rename?
        public init(rename: Rename? = nil) {
            self.rename = rename
        }
        public var variable: Baton.Variable {
            var fields: [String: Baton.Variable] = [:]
            if let rename { fields["rename"] = rename.variable }
            return .object(fields)
        }

        /// A partial response to show before the server answers; absent fields leave the store untouched.
        nonisolated public struct Rename: Sendable {
            public var character: Character?
            public init(character: Character? = nil) {
                self.character = character
            }
            public var variable: Baton.Variable {
                var fields: [String: Baton.Variable] = [:]
                if let character { fields["character"] = character.variable }
                return .object(fields)
            }

            /// A partial response to show before the server answers; absent fields leave the store untouched.
            nonisolated public struct Character: Sendable {
                public var id: String?
                public var name: String?
                public init(id: String? = nil, name: String? = nil) {
                    self.id = id
                    self.name = name
                }
                public var variable: Baton.Variable {
                    var fields: [String: Baton.Variable] = [:]
                    if let id { fields["id"] = .init(id) }
                    if let name { fields["name"] = .init(name) }
                    return .object(fields)
                }
            }
        }
    }
}

extension TestRename.Action {
    /// Commits the mutation; the optimistic response, if any, shows at once and rebases until the server answers.
    @MainActor @discardableResult
    public func callAsFunction(id: String, name: String, optimistic: Op.OptimisticResponse? = nil) async throws -> Op.Data {
        try await self.commit(.init(id: id, name: name), optimistic: optimistic?.variable)
    }
}

/// Operation value for `mutation TestRenameThroughFragment`.
nonisolated public struct TestRenameThroughFragment: Baton.Mutation {
    public var id: String
    public var name: String

    public init(id: String, name: String) {
        self.id = id
        self.name = name
    }

    public static let name = "TestRenameThroughFragment"
    public static let persistedID = "9e2e336fcd7c22f650f9acdf7c7f81e4"
    public static let text = #"""
mutation TestRenameThroughFragment(
  $id: ID!
  $name: String!
) {
  ...TestRenamePayload_mutation
}

fragment TestRenamePayload_mutation on Mutation {
  rename(id: $id, name: $name) {
    character {
      id
      name
    }
  }
}
"""#

    public var variables: Baton.Variables {
        Baton.Variables(["id": Baton.Variable(self.id), "name": Baton.Variable(self.name)])
    }

    public static func == (lhs: Self, rhs: Self) -> Bool {
        lhs.id == rhs.id && lhs.name == rhs.name
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(self.id)
        hasher.combine(self.name)
    }

    @_spi(Generated) public static let plan = Baton.Plan(root: Baton.Selection(type: Types.Mutation, key: [], abstract: false, fields: [
            .linked("rename", key: .fixed(Slots.Mutation.rename), plural: false, selection: Baton.Selection(type: Types.FavoritePayload, key: [], abstract: false, fields: [
                .linked("character", key: .fixed(Slots.FavoritePayload.character), plural: false, selection: Baton.Selection(type: Types.Character, key: ["id"], abstract: false, fields: [
                    .scalar("id", key: .fixed(Slots.Character.id), kind: .string, list: false),
                    .scalar("name", key: .fixed(Slots.Character.name), kind: .string, list: false),
                ])),
            ])),
        ]), transient: Types.transient)

    nonisolated public struct Data: Baton.Lens {
        @_spi(Generated) public let anchor: Baton.Anchor
        @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
        public static let typeName = "Mutation"
        @MainActor public var testRenamePayload: TestRenamePayload_mutation { .init(anchor: anchor.entering()) }
    }

    public typealias Action = Baton.MutationAction<Self>

    /// A partial response to show before the server answers; absent fields leave the store untouched.
    nonisolated public struct OptimisticResponse: Sendable {
        public var rename: Rename?
        public init(rename: Rename? = nil) {
            self.rename = rename
        }
        public var variable: Baton.Variable {
            var fields: [String: Baton.Variable] = [:]
            if let rename { fields["rename"] = rename.variable }
            return .object(fields)
        }

        /// A partial response to show before the server answers; absent fields leave the store untouched.
        nonisolated public struct Rename: Sendable {
            public var character: Character?
            public init(character: Character? = nil) {
                self.character = character
            }
            public var variable: Baton.Variable {
                var fields: [String: Baton.Variable] = [:]
                if let character { fields["character"] = character.variable }
                return .object(fields)
            }

            /// A partial response to show before the server answers; absent fields leave the store untouched.
            nonisolated public struct Character: Sendable {
                public var id: String?
                public var name: String?
                public init(id: String? = nil, name: String? = nil) {
                    self.id = id
                    self.name = name
                }
                public var variable: Baton.Variable {
                    var fields: [String: Baton.Variable] = [:]
                    if let id { fields["id"] = .init(id) }
                    if let name { fields["name"] = .init(name) }
                    return .object(fields)
                }
            }
        }
    }
}

extension TestRenameThroughFragment.Action {
    /// Commits the mutation; the optimistic response, if any, shows at once and rebases until the server answers.
    @MainActor @discardableResult
    public func callAsFunction(id: String, name: String, optimistic: Op.OptimisticResponse? = nil) async throws -> Op.Data {
        try await self.commit(.init(id: id, name: name), optimistic: optimistic?.variable)
    }
}

/// Operation value for `mutation TestRenameWithOrigin`.
nonisolated public struct TestRenameWithOrigin: Baton.Mutation {
    public var id: String
    public var name: String
    public var withOrigin: Bool

    public init(id: String, name: String, withOrigin: Bool) {
        self.id = id
        self.name = name
        self.withOrigin = withOrigin
    }

    public static let name = "TestRenameWithOrigin"
    public static let persistedID = "8457c567f89b7b5a3ed8f3f5c8364841"
    public static let text = #"""
mutation TestRenameWithOrigin(
  $id: ID!
  $name: String!
  $withOrigin: Boolean!
) {
  rename(id: $id, name: $name) {
    character {
      id
      name
      origin @include(if: $withOrigin) {
        id
        name
      }
    }
  }
}
"""#

    public var variables: Baton.Variables {
        Baton.Variables(["id": Baton.Variable(self.id), "name": Baton.Variable(self.name), "withOrigin": Baton.Variable(self.withOrigin)])
    }

    public static func == (lhs: Self, rhs: Self) -> Bool {
        lhs.id == rhs.id && lhs.name == rhs.name && lhs.withOrigin == rhs.withOrigin
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(self.id)
        hasher.combine(self.name)
        hasher.combine(self.withOrigin)
    }

    @_spi(Generated) public static let plan = Baton.Plan(root: Baton.Selection(type: Types.Mutation, key: [], abstract: false, fields: [
            .linked("rename", key: .fixed(Slots.Mutation.rename), plural: false, selection: Baton.Selection(type: Types.FavoritePayload, key: [], abstract: false, fields: [
                .linked("character", key: .fixed(Slots.FavoritePayload.character), plural: false, selection: Baton.Selection(type: Types.Character, key: ["id"], abstract: false, fields: [
                    .scalar("id", key: .fixed(Slots.Character.id), kind: .string, list: false),
                    .scalar("name", key: .fixed(Slots.Character.name), kind: .string, list: false),
                    .linked("origin", key: .fixed(Slots.Character.origin), plural: false, guards: [[Guards.withOrigin_true]], selection: Baton.Selection(type: Types.Location, key: ["id"], abstract: false, fields: [
                        .scalar("id", key: .fixed(Slots.Location.id), kind: .string, list: false),
                        .scalar("name", key: .fixed(Slots.Location.name), kind: .string, list: false),
                    ])),
                ])),
            ])),
        ]), transient: Types.transient)

    nonisolated public struct Data: Baton.Lens {
        @_spi(Generated) public let anchor: Baton.Anchor
        @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
        public static let typeName = "Mutation"
        @MainActor public var rename: Rename? { anchor.linked(Slots.Mutation.rename).map(Rename.init(anchor:)) }

        nonisolated public struct Rename: Baton.Lens {
            @_spi(Generated) public let anchor: Baton.Anchor
            @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
            public static let typeName = "FavoritePayload"
            @MainActor public var character: Character? { anchor.linked(Slots.FavoritePayload.character).map(Character.init(anchor:)) }

            nonisolated public struct Character: Baton.Lens {
                @_spi(Generated) public let anchor: Baton.Anchor
                @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
                public static let typeName = "Character"
                @MainActor public var id: String? { anchor.string(Slots.Character.id) }
                @MainActor public var name: String? { anchor.string(Slots.Character.name) }
                @MainActor public var origin: Origin? { anchor.owner.selects(Guards.withOrigin_true) ? anchor.linked(Slots.Character.origin).map(Origin.init(anchor:)) : nil }

                nonisolated public struct Origin: Baton.Lens {
                    @_spi(Generated) public let anchor: Baton.Anchor
                    @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
                    public static let typeName = "Location"
                    @MainActor public var id: String? { anchor.string(Slots.Location.id) }
                    @MainActor public var name: String? { anchor.string(Slots.Location.name) }
                }
            }
        }
    }

    public typealias Action = Baton.MutationAction<Self>

    /// A partial response to show before the server answers; absent fields leave the store untouched.
    nonisolated public struct OptimisticResponse: Sendable {
        public var rename: Rename?
        public init(rename: Rename? = nil) {
            self.rename = rename
        }
        public var variable: Baton.Variable {
            var fields: [String: Baton.Variable] = [:]
            if let rename { fields["rename"] = rename.variable }
            return .object(fields)
        }

        /// A partial response to show before the server answers; absent fields leave the store untouched.
        nonisolated public struct Rename: Sendable {
            public var character: Character?
            public init(character: Character? = nil) {
                self.character = character
            }
            public var variable: Baton.Variable {
                var fields: [String: Baton.Variable] = [:]
                if let character { fields["character"] = character.variable }
                return .object(fields)
            }

            /// A partial response to show before the server answers; absent fields leave the store untouched.
            nonisolated public struct Character: Sendable {
                public var id: String?
                public var name: String?
                public var origin: Origin?
                public init(id: String? = nil, name: String? = nil, origin: Origin? = nil) {
                    self.id = id
                    self.name = name
                    self.origin = origin
                }
                public var variable: Baton.Variable {
                    var fields: [String: Baton.Variable] = [:]
                    if let id { fields["id"] = .init(id) }
                    if let name { fields["name"] = .init(name) }
                    if let origin { fields["origin"] = origin.variable }
                    return .object(fields)
                }

                /// A partial response to show before the server answers; absent fields leave the store untouched.
                nonisolated public struct Origin: Sendable {
                    public var id: String?
                    public var name: String?
                    public init(id: String? = nil, name: String? = nil) {
                        self.id = id
                        self.name = name
                    }
                    public var variable: Baton.Variable {
                        var fields: [String: Baton.Variable] = [:]
                        if let id { fields["id"] = .init(id) }
                        if let name { fields["name"] = .init(name) }
                        return .object(fields)
                    }
                }
            }
        }
    }
}

extension TestRenameWithOrigin.Action {
    /// Commits the mutation; the optimistic response, if any, shows at once and rebases until the server answers.
    @MainActor @discardableResult
    public func callAsFunction(id: String, name: String, withOrigin: Bool, optimistic: Op.OptimisticResponse? = nil) async throws -> Op.Data {
        try await self.commit(.init(id: id, name: name, withOrigin: withOrigin), optimistic: optimistic?.variable)
    }
}

/// Operation value for `query TestSearch`.
nonisolated public struct TestSearch: Baton.Query {
    public var name: String
    public var resolution: Baton.OperationHandle<Self>? = nil

    public init(name: String) {
        self.name = name
    }

    public static let name = "TestSearch"
    public static let persistedID = "813ee13fc31b31a05b576bb247d1db8b"
    public static let text = #"""
query TestSearch(
  $name: String!
) {
  search(name: $name) {
    __typename
    ... on Character {
      id
      name
    }
    ... on Location {
      id
      name
      dimension
    }
    ... on Node {
      __isNode: __typename
      id
    }
  }
}
"""#

    public var variables: Baton.Variables {
        Baton.Variables(["name": Baton.Variable(self.name)])
    }

    public static func == (lhs: Self, rhs: Self) -> Bool {
        lhs.name == rhs.name
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(self.name)
    }

    @_spi(Generated) public static let plan = Baton.Plan(root: Baton.Selection(type: Types.Query, key: [], abstract: false, fields: [
            .linked("search", key: .dynamic(Slots.Query.search_954c44), plural: true, selection: Baton.Selection(type: Types.SearchResult, key: ["id"], abstract: true, memberships: [.init("__isNode", Types.Node)], variants: [
                .init(types: [Types.Character], key: ["id"], fields: [
                    .scalar("__typename", key: .fixed(Slots.Character.__typename), kind: .string, list: false),
                    .scalar("id", key: .fixed(Slots.Character.id), kind: .string, list: false),
                    .scalar("name", key: .fixed(Slots.Character.name), kind: .string, list: false),
                ]),
                .init(types: [Types.Episode], key: ["id"], fields: [
                    .scalar("__typename", key: .fixed(Slots.Episode.__typename), kind: .string, list: false),
                    .scalar("id", key: .fixed(Slots.Episode.id), kind: .string, list: false),
                ]),
                .init(types: [Types.Location], key: ["id"], fields: [
                    .scalar("__typename", key: .fixed(Slots.Location.__typename), kind: .string, list: false),
                    .scalar("id", key: .fixed(Slots.Location.id), kind: .string, list: false),
                    .scalar("name", key: .fixed(Slots.Location.name), kind: .string, list: false),
                    .scalar("dimension", key: .fixed(Slots.Location.dimension), kind: .string, list: false),
                ]),
                .init(types: nil, condition: Types.Node, fields: [
                    .scalar("__typename", key: .fixed(Slots.SearchResult.__typename), kind: .string, list: false),
                    .scalar("id", key: .fixed(Slots.SearchResult.id), kind: .string, list: false),
                ]),
                .init(types: nil, fields: [
                    .scalar("__typename", key: .fixed(Slots.SearchResult.__typename), kind: .string, list: false),
                ]),
            ])),
        ]), transient: Types.transient)

    nonisolated public struct Data: Baton.Lens {
        @_spi(Generated) public let anchor: Baton.Anchor
        @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
        public static let typeName = "Query"
        @MainActor public var search: Baton.List<Search>? { anchor.list(anchor.owner.slot(Slots.Query.search_954c44)) }

        nonisolated public struct Search: Baton.Lens {
            @_spi(Generated) public let anchor: Baton.Anchor
            @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
            public static let typeName = "SearchResult"
            @MainActor public var asCharacter: AsCharacter? { anchor.record.is(Types.Character) ? AsCharacter(anchor: anchor) : nil }
            @MainActor public var asLocation: AsLocation? { anchor.record.is(Types.Location) ? AsLocation(anchor: anchor) : nil }

            nonisolated public struct AsCharacter: Baton.Lens {
                @_spi(Generated) public let anchor: Baton.Anchor
                @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
                public static let typeName = "Character"
                @MainActor public var id: String? { anchor.string(Slots.Character.id) }
                @MainActor public var name: String? { anchor.string(Slots.Character.name) }
            }

            nonisolated public struct AsLocation: Baton.Lens {
                @_spi(Generated) public let anchor: Baton.Anchor
                @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
                public static let typeName = "Location"
                @MainActor public var id: String? { anchor.string(Slots.Location.id) }
                @MainActor public var name: String? { anchor.string(Slots.Location.name) }
                @MainActor public var dimension: String? { anchor.string(Slots.Location.dimension) }
            }
        }
    }
}

/// Operation value for `query TestSearchOrigins`.
nonisolated public struct TestSearchOrigins: Baton.Query {
    public var name: String
    public var resolution: Baton.OperationHandle<Self>? = nil

    public init(name: String) {
        self.name = name
    }

    public static let name = "TestSearchOrigins"
    public static let persistedID = "ef63ee320f68af412c96bcdec49f9223"
    public static let text = #"""
query TestSearchOrigins(
  $name: String!
) {
  search(name: $name) {
    __typename
    ... on Character {
      origin {
        name
        id
      }
    }
    ... on Node {
      __isNode: __typename
      id
    }
  }
}
"""#

    public var variables: Baton.Variables {
        Baton.Variables(["name": Baton.Variable(self.name)])
    }

    public static func == (lhs: Self, rhs: Self) -> Bool {
        lhs.name == rhs.name
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(self.name)
    }

    @_spi(Generated) public static let plan = Baton.Plan(root: Baton.Selection(type: Types.Query, key: [], abstract: false, fields: [
            .linked("search", key: .dynamic(Slots.Query.search_954c44), plural: true, selection: Baton.Selection(type: Types.SearchResult, key: ["id"], abstract: true, memberships: [.init("__isNode", Types.Node)], variants: [
                .init(types: [Types.Character], key: ["id"], fields: [
                    .scalar("__typename", key: .fixed(Slots.Character.__typename), kind: .string, list: false),
                    .linked("origin", key: .fixed(Slots.Character.origin), plural: false, selection: Baton.Selection(type: Types.Location, key: ["id"], abstract: false, fields: [
                        .scalar("name", key: .fixed(Slots.Location.name), kind: .string, list: false),
                        .scalar("id", key: .fixed(Slots.Location.id), kind: .string, list: false),
                    ])),
                    .scalar("id", key: .fixed(Slots.Character.id), kind: .string, list: false),
                ]),
                .init(types: [Types.Episode, Types.Location], key: ["id"], fields: [
                    .scalar("__typename", key: .fixed(Slots.SearchResult.__typename), kind: .string, list: false),
                    .scalar("id", key: .fixed(Slots.SearchResult.id), kind: .string, list: false),
                ]),
                .init(types: nil, condition: Types.Node, fields: [
                    .scalar("__typename", key: .fixed(Slots.SearchResult.__typename), kind: .string, list: false),
                    .scalar("id", key: .fixed(Slots.SearchResult.id), kind: .string, list: false),
                ]),
                .init(types: nil, fields: [
                    .scalar("__typename", key: .fixed(Slots.SearchResult.__typename), kind: .string, list: false),
                ]),
            ])),
        ]), transient: Types.transient)

    nonisolated public struct Data: Baton.Lens {
        @_spi(Generated) public let anchor: Baton.Anchor
        @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
        public static let typeName = "Query"
        @MainActor public var search: Baton.List<Search>? { anchor.list(anchor.owner.slot(Slots.Query.search_954c44)) }

        nonisolated public struct Search: Baton.Lens {
            @_spi(Generated) public let anchor: Baton.Anchor
            @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
            public static let typeName = "SearchResult"
            @MainActor public var asCharacter: AsCharacter? { anchor.record.is(Types.Character) ? AsCharacter(anchor: anchor) : nil }

            nonisolated public struct AsCharacter: Baton.Lens {
                @_spi(Generated) public let anchor: Baton.Anchor
                @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
                public static let typeName = "Character"
                @MainActor public var origin: Origin? { anchor.linked(Slots.Character.origin).map(Origin.init(anchor:)) }

                nonisolated public struct Origin: Baton.Lens {
                    @_spi(Generated) public let anchor: Baton.Anchor
                    @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
                    public static let typeName = "Location"
                    @MainActor public var name: String? { anchor.string(Slots.Location.name) }
                }
            }
        }
    }
}

/// Operation value for `mutation TestSetFavorite`.
nonisolated public struct TestSetFavorite: Baton.Mutation {
    public var id: String
    public var favorite: Bool

    public init(id: String, favorite: Bool) {
        self.id = id
        self.favorite = favorite
    }

    public static let name = "TestSetFavorite"
    public static let persistedID = "26a88e1bfd6ec2eaa6508d193effadc7"
    public static let text = #"""
mutation TestSetFavorite(
  $id: ID!
  $favorite: Boolean!
) {
  setFavorite(id: $id, favorite: $favorite) {
    character {
      id
      name
      favorite
    }
  }
}
"""#

    public var variables: Baton.Variables {
        Baton.Variables(["id": Baton.Variable(self.id), "favorite": Baton.Variable(self.favorite)])
    }

    public static func == (lhs: Self, rhs: Self) -> Bool {
        lhs.id == rhs.id && lhs.favorite == rhs.favorite
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(self.id)
        hasher.combine(self.favorite)
    }

    @_spi(Generated) public static let plan = Baton.Plan(root: Baton.Selection(type: Types.Mutation, key: [], abstract: false, fields: [
            .linked("setFavorite", key: .fixed(Slots.Mutation.setFavorite), plural: false, selection: Baton.Selection(type: Types.FavoritePayload, key: [], abstract: false, fields: [
                .linked("character", key: .fixed(Slots.FavoritePayload.character), plural: false, selection: Baton.Selection(type: Types.Character, key: ["id"], abstract: false, fields: [
                    .scalar("id", key: .fixed(Slots.Character.id), kind: .string, list: false),
                    .scalar("name", key: .fixed(Slots.Character.name), kind: .string, list: false),
                    .scalar("favorite", key: .fixed(Slots.Character.favorite), kind: .bool, list: false),
                ])),
            ])),
        ]), transient: Types.transient)

    nonisolated public struct Data: Baton.Lens {
        @_spi(Generated) public let anchor: Baton.Anchor
        @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
        public static let typeName = "Mutation"
        @MainActor public var setFavorite: SetFavorite? { anchor.linked(Slots.Mutation.setFavorite).map(SetFavorite.init(anchor:)) }

        nonisolated public struct SetFavorite: Baton.Lens {
            @_spi(Generated) public let anchor: Baton.Anchor
            @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
            public static let typeName = "FavoritePayload"
            @MainActor public var character: Character? { anchor.linked(Slots.FavoritePayload.character).map(Character.init(anchor:)) }

            nonisolated public struct Character: Baton.Lens {
                @_spi(Generated) public let anchor: Baton.Anchor
                @_spi(Generated) public init(anchor: Baton.Anchor) { self.anchor = anchor }
                public static let typeName = "Character"
                @MainActor public var id: String? { anchor.string(Slots.Character.id) }
                @MainActor public var name: String? { anchor.string(Slots.Character.name) }
                @MainActor public var favorite: Bool? { anchor.bool(Slots.Character.favorite) }
            }
        }
    }

    public typealias Action = Baton.MutationAction<Self>

    /// A partial response to show before the server answers; absent fields leave the store untouched.
    nonisolated public struct OptimisticResponse: Sendable {
        public var setFavorite: SetFavorite?
        public init(setFavorite: SetFavorite? = nil) {
            self.setFavorite = setFavorite
        }
        public var variable: Baton.Variable {
            var fields: [String: Baton.Variable] = [:]
            if let setFavorite { fields["setFavorite"] = setFavorite.variable }
            return .object(fields)
        }

        /// A partial response to show before the server answers; absent fields leave the store untouched.
        nonisolated public struct SetFavorite: Sendable {
            public var character: Character?
            public init(character: Character? = nil) {
                self.character = character
            }
            public var variable: Baton.Variable {
                var fields: [String: Baton.Variable] = [:]
                if let character { fields["character"] = character.variable }
                return .object(fields)
            }

            /// A partial response to show before the server answers; absent fields leave the store untouched.
            nonisolated public struct Character: Sendable {
                public var id: String?
                public var name: String?
                public var favorite: Bool?
                public init(id: String? = nil, name: String? = nil, favorite: Bool? = nil) {
                    self.id = id
                    self.name = name
                    self.favorite = favorite
                }
                public var variable: Baton.Variable {
                    var fields: [String: Baton.Variable] = [:]
                    if let id { fields["id"] = .init(id) }
                    if let name { fields["name"] = .init(name) }
                    if let favorite { fields["favorite"] = .init(favorite) }
                    return .object(fields)
                }
            }
        }
    }
}

extension TestSetFavorite.Action {
    /// Commits the mutation; the optimistic response, if any, shows at once and rebases until the server answers.
    @MainActor @discardableResult
    public func callAsFunction(id: String, favorite: Bool, optimistic: Op.OptimisticResponse? = nil) async throws -> Op.Data {
        try await self.commit(.init(id: id, favorite: favorite), optimistic: optimistic?.variable)
    }
}

