// Generated by batonc. Do not edit.
import Baton

/// Lens for `fragment TestFavorite_character on Character`.
nonisolated public struct TestFavorite_character: Baton.Lens {
    public let anchor: Baton.Anchor
    public init(anchor: Baton.Anchor) { self.anchor = anchor }
    public static let typeName = "Character"
    @MainActor public var id: String? { anchor.string(Slots.Character_id) }
    @MainActor public var name: String? { anchor.string(Slots.Character_name) }
    @MainActor public var favorite: Bool? { anchor.bool(Slots.Character_favorite) }
}

/// Operation value for `query TestNode`.
nonisolated public struct TestNode: Baton.Query {
    public var id: String
    public var resolution: Baton.OperationHandle<Self>? = nil

    public init(id: String) {
        self.id = id
    }

    public static let name = "TestNode"
    public static let persistedID = "f4287aafacae3711c1424cdbcbfc508c"
    public static let text = #"""
query TestNode(
  $id: ID!
) {
  node(id: $id) {
    __typename
    ... on Character {
      id
      name
    }
    ... on Episode {
      id
      name
    }
    id
  }
}
"""#

    public var variables: Baton.Variables {
        Baton.Variables(["id": Baton.Variable(id)])
    }

    public static func == (lhs: Self, rhs: Self) -> Bool {
        lhs.id == rhs.id
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
    }

    public static let plan = Baton.Plan(root: Baton.Selection(type: Types.Query, hasID: false, abstract: false, fields: [
            .linked("node", key: .dynamic(Slots.Query_node_8f7d08), plural: false, lookup: Baton.Lookup(type: nil, possibleTypes: Types.Node_possible, key: .variable("id")), selection: Baton.Selection(type: Types.Node, hasID: true, abstract: true, variants: [
                .init(types: [Types.Character, Types.Episode], fields: [
                    .scalar("__typename", key: .fixed(Slots.Node___typename), kind: .string, list: false),
                    .scalar("id", key: .fixed(Slots.Node_id), kind: .string, list: false),
                    .scalar("name", key: .fixed(Slots.Node_name), kind: .string, list: false),
                ]),
                .init(types: nil, fields: [
                    .scalar("__typename", key: .fixed(Slots.Node___typename), kind: .string, list: false),
                    .scalar("id", key: .fixed(Slots.Node_id), kind: .string, list: false),
                ]),
            ])),
        ]))

    nonisolated public struct Data: Baton.Lens {
        public let anchor: Baton.Anchor
        public init(anchor: Baton.Anchor) { self.anchor = anchor }
        public static let typeName = "Query"
        @MainActor public var node: Node? { anchor.linked(anchor.owner.slot(Slots.Query_node_8f7d08)).map(Node.init(anchor:)) }

        nonisolated public struct Node: Baton.Lens {
            public let anchor: Baton.Anchor
            public init(anchor: Baton.Anchor) { self.anchor = anchor }
            public static let typeName = "Node"
            @MainActor public var asCharacter: AsCharacter? { anchor.record.is(Types.Character) ? AsCharacter(anchor: anchor) : nil }
            @MainActor public var asEpisode: AsEpisode? { anchor.record.is(Types.Episode) ? AsEpisode(anchor: anchor) : nil }

            nonisolated public struct AsCharacter: Baton.Lens {
                public let anchor: Baton.Anchor
                public init(anchor: Baton.Anchor) { self.anchor = anchor }
                public static let typeName = "Character"
                @MainActor public var id: String? { anchor.string(Slots.Character_id) }
                @MainActor public var name: String? { anchor.string(Slots.Character_name) }
            }

            nonisolated public struct AsEpisode: Baton.Lens {
                public let anchor: Baton.Anchor
                public init(anchor: Baton.Anchor) { self.anchor = anchor }
                public static let typeName = "Episode"
                @MainActor public var id: String? { anchor.string(Slots.Episode_id) }
                @MainActor public var name: String? { anchor.string(Slots.Episode_name) }
            }
        }
    }
}

/// Operation value for `mutation TestRename`.
nonisolated public struct TestRename: Baton.Mutation {
    public var id: String
    public var name: String

    public init(id: String, name: String) {
        self.id = id
        self.name = name
    }

    public static let name = "TestRename"
    public static let persistedID = "a73fc2b7303f9449bedc2fffea97fb04"
    public static let text = #"""
mutation TestRename(
  $id: ID!
  $name: String!
) {
  rename(id: $id, name: $name) {
    character {
      id
      name
    }
  }
}
"""#

    public var variables: Baton.Variables {
        Baton.Variables(["id": Baton.Variable(id), "name": Baton.Variable(name)])
    }

    public static func == (lhs: Self, rhs: Self) -> Bool {
        lhs.id == rhs.id && lhs.name == rhs.name
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(name)
    }

    public static let plan = Baton.Plan(root: Baton.Selection(type: Types.Mutation, hasID: false, abstract: false, fields: [
            .linked("rename", key: .fixed(Slots.Mutation_rename), plural: false, selection: Baton.Selection(type: Types.FavoritePayload, hasID: false, abstract: false, fields: [
                .linked("character", key: .fixed(Slots.FavoritePayload_character), plural: false, selection: Baton.Selection(type: Types.Character, hasID: true, abstract: false, fields: [
                    .scalar("id", key: .fixed(Slots.Character_id), kind: .string, list: false),
                    .scalar("name", key: .fixed(Slots.Character_name), kind: .string, list: false),
                ])),
            ])),
        ]))

    nonisolated public struct Data: Baton.Lens {
        public let anchor: Baton.Anchor
        public init(anchor: Baton.Anchor) { self.anchor = anchor }
        public static let typeName = "Mutation"
        @MainActor public var rename: Rename? { anchor.linked(Slots.Mutation_rename).map(Rename.init(anchor:)) }

        nonisolated public struct Rename: Baton.Lens {
            public let anchor: Baton.Anchor
            public init(anchor: Baton.Anchor) { self.anchor = anchor }
            public static let typeName = "FavoritePayload"
            @MainActor public var character: Character? { anchor.linked(Slots.FavoritePayload_character).map(Character.init(anchor:)) }

            nonisolated public struct Character: Baton.Lens {
                public let anchor: Baton.Anchor
                public init(anchor: Baton.Anchor) { self.anchor = anchor }
                public static let typeName = "Character"
                @MainActor public var id: String? { anchor.string(Slots.Character_id) }
                @MainActor public var name: String? { anchor.string(Slots.Character_name) }
            }
        }
    }

    public typealias Action = Baton.MutationAction<Self>

    /// A partial response to show before the server answers; absent fields leave the store untouched.
    nonisolated public struct OptimisticResponse: Sendable {
        public var rename: Rename?
        public init(rename: Rename? = nil) {
            self.rename = rename
        }
        public var variable: Baton.Variable {
            var fields: [String: Baton.Variable] = [:]
            if let rename { fields["rename"] = rename.variable }
            return .object(fields)
        }

        /// A partial response to show before the server answers; absent fields leave the store untouched.
        nonisolated public struct Rename: Sendable {
            public var character: Character?
            public init(character: Character? = nil) {
                self.character = character
            }
            public var variable: Baton.Variable {
                var fields: [String: Baton.Variable] = [:]
                if let character { fields["character"] = character.variable }
                return .object(fields)
            }

            /// A partial response to show before the server answers; absent fields leave the store untouched.
            nonisolated public struct Character: Sendable {
                public var id: String?
                public var name: String?
                public init(id: String? = nil, name: String? = nil) {
                    self.id = id
                    self.name = name
                }
                public var variable: Baton.Variable {
                    var fields: [String: Baton.Variable] = [:]
                    if let id { fields["id"] = Baton.Variable(id) }
                    if let name { fields["name"] = Baton.Variable(name) }
                    return .object(fields)
                }
            }
        }
    }
}

extension Baton.MutationAction where Op == TestRename {
    /// Commits the mutation; the optimistic response, if any, shows at once and rebases until the server answers.
    @MainActor @discardableResult
    public func callAsFunction(id: String, name: String, optimistic: TestRename.OptimisticResponse? = nil) async throws -> TestRename.Data {
        try await commit(TestRename(id: id, name: name), optimistic: optimistic?.variable)
    }
}

/// Operation value for `query TestSearch`.
nonisolated public struct TestSearch: Baton.Query {
    public var name: String
    public var resolution: Baton.OperationHandle<Self>? = nil

    public init(name: String) {
        self.name = name
    }

    public static let name = "TestSearch"
    public static let persistedID = "529930501b89d258d63e782735ce5cf7"
    public static let text = #"""
query TestSearch(
  $name: String!
) {
  search(name: $name) {
    __typename
    ... on Character {
      id
      name
    }
    ... on Location {
      id
      name
      dimension
    }
    ... on Node {
      __isNode: __typename
      id
    }
  }
}
"""#

    public var variables: Baton.Variables {
        Baton.Variables(["name": Baton.Variable(name)])
    }

    public static func == (lhs: Self, rhs: Self) -> Bool {
        lhs.name == rhs.name
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(name)
    }

    public static let plan = Baton.Plan(root: Baton.Selection(type: Types.Query, hasID: false, abstract: false, fields: [
            .linked("search", key: .dynamic(Slots.Query_search_954c44), plural: true, selection: Baton.Selection(type: Types.SearchResult, hasID: true, abstract: true, variants: [
                .init(types: [Types.Character], fields: [
                    .scalar("__typename", key: .fixed(Slots.Character___typename), kind: .string, list: false),
                    .scalar("id", key: .fixed(Slots.Character_id), kind: .string, list: false),
                    .scalar("name", key: .fixed(Slots.Character_name), kind: .string, list: false),
                ]),
                .init(types: [Types.Episode], fields: [
                    .scalar("__typename", key: .fixed(Slots.Episode___typename), kind: .string, list: false),
                    .scalar("id", key: .fixed(Slots.Episode_id), kind: .string, list: false),
                ]),
                .init(types: [Types.Location], fields: [
                    .scalar("__typename", key: .fixed(Slots.Location___typename), kind: .string, list: false),
                    .scalar("id", key: .fixed(Slots.Location_id), kind: .string, list: false),
                    .scalar("name", key: .fixed(Slots.Location_name), kind: .string, list: false),
                    .scalar("dimension", key: .fixed(Slots.Location_dimension), kind: .string, list: false),
                ]),
                .init(types: nil, fields: [
                    .scalar("__typename", key: .fixed(Slots.SearchResult___typename), kind: .string, list: false),
                ]),
            ])),
        ]))

    nonisolated public struct Data: Baton.Lens {
        public let anchor: Baton.Anchor
        public init(anchor: Baton.Anchor) { self.anchor = anchor }
        public static let typeName = "Query"
        @MainActor public var search: Baton.List<Search>? { anchor.list(anchor.owner.slot(Slots.Query_search_954c44)) }

        nonisolated public struct Search: Baton.Lens {
            public let anchor: Baton.Anchor
            public init(anchor: Baton.Anchor) { self.anchor = anchor }
            public static let typeName = "SearchResult"
            @MainActor public var asCharacter: AsCharacter? { anchor.record.is(Types.Character) ? AsCharacter(anchor: anchor) : nil }
            @MainActor public var asLocation: AsLocation? { anchor.record.is(Types.Location) ? AsLocation(anchor: anchor) : nil }

            nonisolated public struct AsCharacter: Baton.Lens {
                public let anchor: Baton.Anchor
                public init(anchor: Baton.Anchor) { self.anchor = anchor }
                public static let typeName = "Character"
                @MainActor public var id: String? { anchor.string(Slots.Character_id) }
                @MainActor public var name: String? { anchor.string(Slots.Character_name) }
            }

            nonisolated public struct AsLocation: Baton.Lens {
                public let anchor: Baton.Anchor
                public init(anchor: Baton.Anchor) { self.anchor = anchor }
                public static let typeName = "Location"
                @MainActor public var id: String? { anchor.string(Slots.Location_id) }
                @MainActor public var name: String? { anchor.string(Slots.Location_name) }
                @MainActor public var dimension: String? { anchor.string(Slots.Location_dimension) }
            }
        }
    }
}

/// Operation value for `query TestSearchOrigins`.
nonisolated public struct TestSearchOrigins: Baton.Query {
    public var name: String
    public var resolution: Baton.OperationHandle<Self>? = nil

    public init(name: String) {
        self.name = name
    }

    public static let name = "TestSearchOrigins"
    public static let persistedID = "b901518a8b1a3f0fb9032a3ac9060d04"
    public static let text = #"""
query TestSearchOrigins(
  $name: String!
) {
  search(name: $name) {
    __typename
    ... on Character {
      origin {
        name
        id
      }
    }
    ... on Node {
      __isNode: __typename
      id
    }
  }
}
"""#

    public var variables: Baton.Variables {
        Baton.Variables(["name": Baton.Variable(name)])
    }

    public static func == (lhs: Self, rhs: Self) -> Bool {
        lhs.name == rhs.name
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(name)
    }

    public static let plan = Baton.Plan(root: Baton.Selection(type: Types.Query, hasID: false, abstract: false, fields: [
            .linked("search", key: .dynamic(Slots.Query_search_954c44), plural: true, selection: Baton.Selection(type: Types.SearchResult, hasID: true, abstract: true, variants: [
                .init(types: [Types.Character], fields: [
                    .scalar("__typename", key: .fixed(Slots.Character___typename), kind: .string, list: false),
                    .linked("origin", key: .fixed(Slots.Character_origin), plural: false, selection: Baton.Selection(type: Types.Location, hasID: true, abstract: false, fields: [
                        .scalar("name", key: .fixed(Slots.Location_name), kind: .string, list: false),
                        .scalar("id", key: .fixed(Slots.Location_id), kind: .string, list: false),
                    ])),
                    .scalar("id", key: .fixed(Slots.Character_id), kind: .string, list: false),
                ]),
                .init(types: [Types.Episode, Types.Location], fields: [
                    .scalar("__typename", key: .fixed(Slots.SearchResult___typename), kind: .string, list: false),
                    .scalar("id", key: .fixed(Slots.SearchResult_id), kind: .string, list: false),
                ]),
                .init(types: nil, fields: [
                    .scalar("__typename", key: .fixed(Slots.SearchResult___typename), kind: .string, list: false),
                ]),
            ])),
        ]))

    nonisolated public struct Data: Baton.Lens {
        public let anchor: Baton.Anchor
        public init(anchor: Baton.Anchor) { self.anchor = anchor }
        public static let typeName = "Query"
        @MainActor public var search: Baton.List<Search>? { anchor.list(anchor.owner.slot(Slots.Query_search_954c44)) }

        nonisolated public struct Search: Baton.Lens {
            public let anchor: Baton.Anchor
            public init(anchor: Baton.Anchor) { self.anchor = anchor }
            public static let typeName = "SearchResult"
            @MainActor public var asCharacter: AsCharacter? { anchor.record.is(Types.Character) ? AsCharacter(anchor: anchor) : nil }

            nonisolated public struct AsCharacter: Baton.Lens {
                public let anchor: Baton.Anchor
                public init(anchor: Baton.Anchor) { self.anchor = anchor }
                public static let typeName = "Character"
                @MainActor public var origin: Origin? { anchor.linked(Slots.Character_origin).map(Origin.init(anchor:)) }

                nonisolated public struct Origin: Baton.Lens {
                    public let anchor: Baton.Anchor
                    public init(anchor: Baton.Anchor) { self.anchor = anchor }
                    public static let typeName = "Location"
                    @MainActor public var name: String? { anchor.string(Slots.Location_name) }
                }
            }
        }
    }
}

/// Operation value for `mutation TestSetFavorite`.
nonisolated public struct TestSetFavorite: Baton.Mutation {
    public var id: String
    public var favorite: Bool

    public init(id: String, favorite: Bool) {
        self.id = id
        self.favorite = favorite
    }

    public static let name = "TestSetFavorite"
    public static let persistedID = "e84c45c8e83cd8488e3e4923ba0e045b"
    public static let text = #"""
mutation TestSetFavorite(
  $id: ID!
  $favorite: Boolean!
) {
  setFavorite(id: $id, favorite: $favorite) {
    character {
      id
      name
      favorite
    }
  }
}
"""#

    public var variables: Baton.Variables {
        Baton.Variables(["id": Baton.Variable(id), "favorite": Baton.Variable(favorite)])
    }

    public static func == (lhs: Self, rhs: Self) -> Bool {
        lhs.id == rhs.id && lhs.favorite == rhs.favorite
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(favorite)
    }

    public static let plan = Baton.Plan(root: Baton.Selection(type: Types.Mutation, hasID: false, abstract: false, fields: [
            .linked("setFavorite", key: .fixed(Slots.Mutation_setFavorite), plural: false, selection: Baton.Selection(type: Types.FavoritePayload, hasID: false, abstract: false, fields: [
                .linked("character", key: .fixed(Slots.FavoritePayload_character), plural: false, selection: Baton.Selection(type: Types.Character, hasID: true, abstract: false, fields: [
                    .scalar("id", key: .fixed(Slots.Character_id), kind: .string, list: false),
                    .scalar("name", key: .fixed(Slots.Character_name), kind: .string, list: false),
                    .scalar("favorite", key: .fixed(Slots.Character_favorite), kind: .bool, list: false),
                ])),
            ])),
        ]))

    nonisolated public struct Data: Baton.Lens {
        public let anchor: Baton.Anchor
        public init(anchor: Baton.Anchor) { self.anchor = anchor }
        public static let typeName = "Mutation"
        @MainActor public var setFavorite: SetFavorite? { anchor.linked(Slots.Mutation_setFavorite).map(SetFavorite.init(anchor:)) }

        nonisolated public struct SetFavorite: Baton.Lens {
            public let anchor: Baton.Anchor
            public init(anchor: Baton.Anchor) { self.anchor = anchor }
            public static let typeName = "FavoritePayload"
            @MainActor public var character: Character? { anchor.linked(Slots.FavoritePayload_character).map(Character.init(anchor:)) }

            nonisolated public struct Character: Baton.Lens {
                public let anchor: Baton.Anchor
                public init(anchor: Baton.Anchor) { self.anchor = anchor }
                public static let typeName = "Character"
                @MainActor public var id: String? { anchor.string(Slots.Character_id) }
                @MainActor public var name: String? { anchor.string(Slots.Character_name) }
                @MainActor public var favorite: Bool? { anchor.bool(Slots.Character_favorite) }
            }
        }
    }

    public typealias Action = Baton.MutationAction<Self>

    /// A partial response to show before the server answers; absent fields leave the store untouched.
    nonisolated public struct OptimisticResponse: Sendable {
        public var setFavorite: SetFavorite?
        public init(setFavorite: SetFavorite? = nil) {
            self.setFavorite = setFavorite
        }
        public var variable: Baton.Variable {
            var fields: [String: Baton.Variable] = [:]
            if let setFavorite { fields["setFavorite"] = setFavorite.variable }
            return .object(fields)
        }

        /// A partial response to show before the server answers; absent fields leave the store untouched.
        nonisolated public struct SetFavorite: Sendable {
            public var character: Character?
            public init(character: Character? = nil) {
                self.character = character
            }
            public var variable: Baton.Variable {
                var fields: [String: Baton.Variable] = [:]
                if let character { fields["character"] = character.variable }
                return .object(fields)
            }

            /// A partial response to show before the server answers; absent fields leave the store untouched.
            nonisolated public struct Character: Sendable {
                public var id: String?
                public var name: String?
                public var favorite: Bool?
                public init(id: String? = nil, name: String? = nil, favorite: Bool? = nil) {
                    self.id = id
                    self.name = name
                    self.favorite = favorite
                }
                public var variable: Baton.Variable {
                    var fields: [String: Baton.Variable] = [:]
                    if let id { fields["id"] = Baton.Variable(id) }
                    if let name { fields["name"] = Baton.Variable(name) }
                    if let favorite { fields["favorite"] = Baton.Variable(favorite) }
                    return .object(fields)
                }
            }
        }
    }
}

extension Baton.MutationAction where Op == TestSetFavorite {
    /// Commits the mutation; the optimistic response, if any, shows at once and rebases until the server answers.
    @MainActor @discardableResult
    public func callAsFunction(id: String, favorite: Bool, optimistic: TestSetFavorite.OptimisticResponse? = nil) async throws -> TestSetFavorite.Data {
        try await commit(TestSetFavorite(id: id, favorite: favorite), optimistic: optimistic?.variable)
    }
}

