// Generated by batonc. Do not edit.
@file:OptIn(baton.Generated::class)

package baton.goldens

import androidx.compose.runtime.Stable
import baton.Anchor
import baton.Document
import baton.Generated
import baton.Lens
import baton.MutationAction
import baton.MutationOperation
import baton.OperationHandle
import baton.OperationKind
import baton.OperationType
import baton.Payload
import baton.Plan
import baton.PlanField
import baton.QueryOperation
import baton.Resolution
import baton.ScalarKind
import baton.Selection
import baton.StorageKey
import baton.Variable
import baton.Variables

/** Operation value for `query TestCharactersWithStatus`. */
class TestCharactersWithStatus(val status: Status, val any: List<Status>? = null) : QueryOperation<TestCharactersWithStatus.Data> {
    override val variables: Variables
        get() = Variables.of("status" to Variable.of(status), "any" to any?.let { Variable.List(it.map { Variable.of(it) }) })
    override var resolution: Resolution<OperationHandle<Data>> = Resolution.Unresolved
    override val type: OperationType<Data> get() = Companion

    override fun equals(other: Any?): Boolean = other is TestCharactersWithStatus && other.status == status && other.any == any
    override fun hashCode(): Int = listOf(status, any).hashCode()

    companion object : OperationType<Data> {
        override val name = "TestCharactersWithStatus"
        override val document: Document = Document.Text("query TestCharactersWithStatus(\$status:Status!,\$any:[Status!]){charactersWithStatus(status:\$status,any:\$any){name,id}}")
        override val kind = OperationKind.QUERY
        override val plan: Plan by lazy { Plan(root = `TestCharactersWithStatus-plan`.selection0, transient = Types.transient) }

        override fun data(anchor: Anchor): Data = Data(anchor)
    }

    @Stable
    class Data(override val anchor: Anchor) : Lens {
        val charactersWithStatus: List<CharactersWithStatus>? get() = anchor.list(anchor.owner.slot(Slots.Query.charactersWithStatus_deb51f), ::CharactersWithStatus)
        override fun equals(other: Any?): Boolean = other is TestCharactersWithStatus.Data && other.anchor == anchor
        override fun hashCode(): Int = anchor.hashCode()

        @Stable
        class CharactersWithStatus(override val anchor: Anchor) : Lens {
            val name: String? get() = anchor.string(Slots.Character.name)
            override fun equals(other: Any?): Boolean = other is TestCharactersWithStatus.Data.CharactersWithStatus && other.anchor == anchor
            override fun hashCode(): Int = anchor.hashCode()
        }
    }
}

private object `TestCharactersWithStatus-plan` {
    val selection0: Selection by lazy {
        Selection(type = Types.Query, key = listOf(), isAbstract = false, fields = listOf(
            PlanField.linked("charactersWithStatus", key = StorageKey.Dynamic(Slots.Query.charactersWithStatus_deb51f), plural = true, selection = selection1),
        ))
    }
    val selection1: Selection by lazy {
        Selection(type = Types.Character, key = listOf("id"), isAbstract = false, fields = listOf(
            PlanField.scalar("name", key = StorageKey.Fixed(Slots.Character.name), kind = ScalarKind.STRING, list = false),
            PlanField.scalar("id", key = StorageKey.Fixed(Slots.Character.id), kind = ScalarKind.STRING, list = false),
        ))
    }
}

/** Operation value for `mutation TestSetStatuses`. */
class TestSetStatuses : MutationOperation<TestSetStatuses.Data> {
    override val variables: Variables
        get() = Variables.none
    override val type: OperationType<Data> get() = Companion

    override fun equals(other: Any?): Boolean = other is TestSetStatuses
    override fun hashCode(): Int = 0

    companion object : OperationType<Data> {
        override val name = "TestSetStatuses"
        override val document: Document = Document.Text("mutation TestSetStatuses{setLists{statuses}}")
        override val kind = OperationKind.MUTATION
        override val plan: Plan by lazy { Plan(root = `TestSetStatuses-plan`.selection0, transient = Types.transient) }

        override fun data(anchor: Anchor): Data = Data(anchor)
    }

    @Stable
    class Data(override val anchor: Anchor) : Lens {
        val setLists: SetLists? get() = anchor.linked(Slots.Mutation.setLists)?.let(::SetLists)
        override fun equals(other: Any?): Boolean = other is TestSetStatuses.Data && other.anchor == anchor
        override fun hashCode(): Int = anchor.hashCode()

        @Stable
        class SetLists(override val anchor: Anchor) : Lens {
            val statuses: List<Status?>? get() = anchor.nullableEnumValues(Slots.ListsPayload.statuses, Status::of)
            override fun equals(other: Any?): Boolean = other is TestSetStatuses.Data.SetLists && other.anchor == anchor
            override fun hashCode(): Int = anchor.hashCode()
        }
    }

    /** A partial response to show before the server answers; absent fields leave the store untouched. */
    class OptimisticResponse(val setLists: SetLists? = null) {
        /** The response's data as a variable, an absent field left out. */
        @Generated
        val variable: Variable
            get() = Variable.Object(Variables.of("setLists" to this.setLists?.variable).values)
        /** The response this builder describes, as the bytes the door takes. */
        val payload: Payload get() = Payload(data = variable)

        /** A partial response to show before the server answers; absent fields leave the store untouched. */
        class SetLists(val statuses: List<Status?>? = null) {
            /** The response's data as a variable, an absent field left out. */
            @Generated
            val variable: Variable
                get() = Variable.Object(Variables.of("statuses" to this.statuses?.let { Variable.List(it.map { Variable.of(it) }) }).values)
        }
    }
}

private object `TestSetStatuses-plan` {
    val selection0: Selection by lazy {
        Selection(type = Types.Mutation, key = listOf(), isAbstract = false, fields = listOf(
            PlanField.linked("setLists", key = StorageKey.Fixed(Slots.Mutation.setLists), plural = false, selection = selection1),
        ))
    }
    val selection1: Selection by lazy {
        Selection(type = Types.ListsPayload, key = listOf(), isAbstract = false, fields = listOf(
            PlanField.scalar("statuses", key = StorageKey.Fixed(Slots.ListsPayload.statuses), kind = ScalarKind.STRING, list = true),
        ))
    }
}

/** Commits the mutation; the optimistic response, if any, shows at once and rebases until the server answers. */
suspend operator fun MutationAction<TestSetStatuses, TestSetStatuses.Data>.invoke(optimistic: TestSetStatuses.OptimisticResponse? = null): TestSetStatuses.Data = this.commit(TestSetStatuses(), optimistic?.payload)
