// Generated by batonc. Do not edit.
@file:OptIn(baton.Generated::class)

package baton.goldens

import androidx.compose.runtime.Immutable
import androidx.compose.runtime.Stable
import baton.Anchor
import baton.Document
import baton.Edit
import baton.Generated
import baton.Lens
import baton.MutationAction
import baton.MutationOperation
import baton.MutationType
import baton.OperationKind
import baton.OperationType
import baton.Payload
import baton.Plan
import baton.PlanField
import baton.ScalarKind
import baton.Selection
import baton.StorageKey
import baton.Variable
import baton.Variables

/** Operation value for `mutation TestAppendCastNodes`. */
@Immutable
class TestAppendCastNodes(val id: String, val name: String, val connections: List<String>) : MutationOperation<TestAppendCastNodes.Data> {
    override val variables: Variables
        get() = Variables.of("id" to Variable.of(id), "name" to Variable.of(name), "connections" to Variable.List(connections.map { Variable.of(it) }))
    override val type: OperationType<Data> get() = Companion

    override fun equals(other: Any?): Boolean = other is TestAppendCastNodes && other.id == id && other.name == name && other.connections == connections
    override fun hashCode(): Int = listOf(id, name, connections).hashCode()

    companion object : MutationType<TestAppendCastNodes, TestAppendCastNodes.Data> {
        override val name = "TestAppendCastNodes"
        override val document: Document = Document.Text("mutation TestAppendCastNodes(\$id:ID!,\$name:String!){rename(id:\$id,name:\$name){character{id,episode{id,name,air_date,episode,characters{id}}}}}")
        override val kind = OperationKind.MUTATION
        override val plan: Plan by lazy { Plan(root = `TestAppendCastNodes-plan`.selection0, transient = Types.transient) }

        override fun data(anchor: Anchor): Data = Data(anchor)
    }

    @Stable
    class Data(override val anchor: Anchor) : Lens {
        val rename: Rename? get() = anchor.linked(Slots.Mutation.rename)?.let(::Rename)
        override fun equals(other: Any?): Boolean = other is TestAppendCastNodes.Data && other.anchor == anchor
        override fun hashCode(): Int = anchor.hashCode()

        @Stable
        class Rename(override val anchor: Anchor) : Lens {
            val character: Character? get() = anchor.linked(Slots.FavoritePayload.character)?.let(::Character)
            override fun equals(other: Any?): Boolean = other is TestAppendCastNodes.Data.Rename && other.anchor == anchor
            override fun hashCode(): Int = anchor.hashCode()

            @Stable
            class Character(override val anchor: Anchor) : Lens {
                val id: String? get() = anchor.string(Slots.Character.id)
                val episode: List<Episode> get() = anchor.requiredList(Slots.Character.episode, ::Episode)
                override fun equals(other: Any?): Boolean = other is TestAppendCastNodes.Data.Rename.Character && other.anchor == anchor
                override fun hashCode(): Int = anchor.hashCode()

                @Stable
                class Episode(override val anchor: Anchor) : Lens {
                    val id: String? get() = anchor.string(Slots.Episode.id)
                    val name: String? get() = anchor.string(Slots.Episode.name)
                    val air_date: String? get() = anchor.string(Slots.Episode.air_date)
                    val episode: String? get() = anchor.string(Slots.Episode.episode)
                    val characters: List<Characters> get() = anchor.requiredList(Slots.Episode.characters, ::Characters)
                    override fun equals(other: Any?): Boolean = other is TestAppendCastNodes.Data.Rename.Character.Episode && other.anchor == anchor
                    override fun hashCode(): Int = anchor.hashCode()

                    @Stable
                    class Characters(override val anchor: Anchor) : Lens {
                        val id: String? get() = anchor.string(Slots.Character.id)
                        override fun equals(other: Any?): Boolean = other is TestAppendCastNodes.Data.Rename.Character.Episode.Characters && other.anchor == anchor
                        override fun hashCode(): Int = anchor.hashCode()
                    }
                }
            }
        }
    }

    /** A partial response to show before the server answers; absent fields leave the store untouched. */
    class OptimisticResponse(val rename: Rename? = null) {
        /** The response's data as a variable, an absent field left out. */
        @Generated
        val variable: Variable
            get() = Variable.Object(Variables.of("rename" to this.rename?.variable).values)
        /** The response this builder describes, as the bytes the door takes. */
        val payload: Payload get() = Payload(data = variable)

        /** A partial response to show before the server answers; absent fields leave the store untouched. */
        class Rename(val character: Character? = null) {
            /** The response's data as a variable, an absent field left out. */
            @Generated
            val variable: Variable
                get() = Variable.Object(Variables.of("character" to this.character?.variable).values)

            /** A partial response to show before the server answers; absent fields leave the store untouched. */
            class Character(val id: String? = null, val episode: List<Episode>? = null) {
                /** The response's data as a variable, an absent field left out. */
                @Generated
                val variable: Variable
                    get() = Variable.Object(Variables.of("id" to this.id?.let { Variable.of(it) }, "episode" to this.episode?.let { Variable.List(it.map { element -> element.variable }) }).values)

                /** A partial response to show before the server answers; absent fields leave the store untouched. */
                class Episode(val id: String? = null, val name: String? = null, val air_date: String? = null, val episode: String? = null, val characters: List<Characters>? = null) {
                    /** The response's data as a variable, an absent field left out. */
                    @Generated
                    val variable: Variable
                        get() = Variable.Object(Variables.of("id" to this.id?.let { Variable.of(it) }, "name" to this.name?.let { Variable.of(it) }, "air_date" to this.air_date?.let { Variable.of(it) }, "episode" to this.episode?.let { Variable.of(it) }, "characters" to this.characters?.let { Variable.List(it.map { element -> element.variable }) }).values)

                    /** A partial response to show before the server answers; absent fields leave the store untouched. */
                    class Characters(val id: String? = null) {
                        /** The response's data as a variable, an absent field left out. */
                        @Generated
                        val variable: Variable
                            get() = Variable.Object(Variables.of("id" to this.id?.let { Variable.of(it) }).values)
                    }
                }
            }
        }
    }
}

private object `TestAppendCastNodes-plan` {
    val selection0: Selection by lazy {
        Selection(type = Types.Mutation, key = listOf(), isAbstract = false, fields = listOf(
            PlanField.linked("rename", key = StorageKey.Fixed(Slots.Mutation.rename), plural = false, selection = selection1),
        ))
    }
    val selection1: Selection by lazy {
        Selection(type = Types.FavoritePayload, key = listOf(), isAbstract = false, fields = listOf(
            PlanField.linked("character", key = StorageKey.Fixed(Slots.FavoritePayload.character), plural = false, selection = selection2),
        ))
    }
    val selection2: Selection by lazy {
        Selection(type = Types.Character, key = listOf("id"), isAbstract = false, fields = listOf(
            PlanField.scalar("id", key = StorageKey.Fixed(Slots.Character.id), kind = ScalarKind.STRING, list = false),
            PlanField.linked("episode", key = StorageKey.Fixed(Slots.Character.episode), plural = true, selection = selection3),
        ))
    }
    val selection3: Selection by lazy {
        Selection(type = Types.Episode, key = listOf("id"), isAbstract = false, fields = listOf(
            PlanField.scalar("id", key = StorageKey.Fixed(Slots.Episode.id), kind = ScalarKind.STRING, list = false),
            PlanField.scalar("name", key = StorageKey.Fixed(Slots.Episode.name), kind = ScalarKind.STRING, list = false),
            PlanField.scalar("air_date", key = StorageKey.Fixed(Slots.Episode.air_date), kind = ScalarKind.STRING, list = false),
            PlanField.scalar("episode", key = StorageKey.Fixed(Slots.Episode.episode), kind = ScalarKind.STRING, list = false),
            PlanField.linked("characters", key = StorageKey.Fixed(Slots.Episode.characters), plural = true, edit = Edit(kind = Edit.Kind.APPEND_NODE, connections = Edit.Connections.Variable("connections"), edgeType = Types.NoteEdge), selection = selection4),
        ))
    }
    val selection4: Selection by lazy {
        Selection(type = Types.Character, key = listOf("id"), isAbstract = false, fields = listOf(
            PlanField.scalar("id", key = StorageKey.Fixed(Slots.Character.id), kind = ScalarKind.STRING, list = false),
        ))
    }
}

/** Commits the mutation; the optimistic response, if any, shows at once and rebases until the server answers. */
suspend operator fun MutationAction<TestAppendCastNodes, TestAppendCastNodes.Data>.invoke(id: String, name: String, connections: List<String>, optimistic: TestAppendCastNodes.OptimisticResponse? = null): TestAppendCastNodes.Data = this.commit(TestAppendCastNodes(id, name, connections), optimistic?.payload)

/** Operation value for `mutation TestAppendEpisodeNodes`. */
@Immutable
class TestAppendEpisodeNodes(val id: String, val name: String, val connections: List<String>) : MutationOperation<TestAppendEpisodeNodes.Data> {
    override val variables: Variables
        get() = Variables.of("id" to Variable.of(id), "name" to Variable.of(name), "connections" to Variable.List(connections.map { Variable.of(it) }))
    override val type: OperationType<Data> get() = Companion

    override fun equals(other: Any?): Boolean = other is TestAppendEpisodeNodes && other.id == id && other.name == name && other.connections == connections
    override fun hashCode(): Int = listOf(id, name, connections).hashCode()

    companion object : MutationType<TestAppendEpisodeNodes, TestAppendEpisodeNodes.Data> {
        override val name = "TestAppendEpisodeNodes"
        override val document: Document = Document.Text("mutation TestAppendEpisodeNodes(\$id:ID!,\$name:String!){rename(id:\$id,name:\$name){character{id,episode{id,name,air_date,episode}}}}")
        override val kind = OperationKind.MUTATION
        override val plan: Plan by lazy { Plan(root = `TestAppendEpisodeNodes-plan`.selection0, transient = Types.transient) }

        override fun data(anchor: Anchor): Data = Data(anchor)
    }

    @Stable
    class Data(override val anchor: Anchor) : Lens {
        val rename: Rename? get() = anchor.linked(Slots.Mutation.rename)?.let(::Rename)
        override fun equals(other: Any?): Boolean = other is TestAppendEpisodeNodes.Data && other.anchor == anchor
        override fun hashCode(): Int = anchor.hashCode()

        @Stable
        class Rename(override val anchor: Anchor) : Lens {
            val character: Character? get() = anchor.linked(Slots.FavoritePayload.character)?.let(::Character)
            override fun equals(other: Any?): Boolean = other is TestAppendEpisodeNodes.Data.Rename && other.anchor == anchor
            override fun hashCode(): Int = anchor.hashCode()

            @Stable
            class Character(override val anchor: Anchor) : Lens {
                val id: String? get() = anchor.string(Slots.Character.id)
                val episode: List<Episode> get() = anchor.requiredList(Slots.Character.episode, ::Episode)
                override fun equals(other: Any?): Boolean = other is TestAppendEpisodeNodes.Data.Rename.Character && other.anchor == anchor
                override fun hashCode(): Int = anchor.hashCode()

                @Stable
                class Episode(override val anchor: Anchor) : Lens {
                    val id: String? get() = anchor.string(Slots.Episode.id)
                    val name: String? get() = anchor.string(Slots.Episode.name)
                    val air_date: String? get() = anchor.string(Slots.Episode.air_date)
                    val episode: String? get() = anchor.string(Slots.Episode.episode)
                    override fun equals(other: Any?): Boolean = other is TestAppendEpisodeNodes.Data.Rename.Character.Episode && other.anchor == anchor
                    override fun hashCode(): Int = anchor.hashCode()
                }
            }
        }
    }

    /** A partial response to show before the server answers; absent fields leave the store untouched. */
    class OptimisticResponse(val rename: Rename? = null) {
        /** The response's data as a variable, an absent field left out. */
        @Generated
        val variable: Variable
            get() = Variable.Object(Variables.of("rename" to this.rename?.variable).values)
        /** The response this builder describes, as the bytes the door takes. */
        val payload: Payload get() = Payload(data = variable)

        /** A partial response to show before the server answers; absent fields leave the store untouched. */
        class Rename(val character: Character? = null) {
            /** The response's data as a variable, an absent field left out. */
            @Generated
            val variable: Variable
                get() = Variable.Object(Variables.of("character" to this.character?.variable).values)

            /** A partial response to show before the server answers; absent fields leave the store untouched. */
            class Character(val id: String? = null, val episode: List<Episode>? = null) {
                /** The response's data as a variable, an absent field left out. */
                @Generated
                val variable: Variable
                    get() = Variable.Object(Variables.of("id" to this.id?.let { Variable.of(it) }, "episode" to this.episode?.let { Variable.List(it.map { element -> element.variable }) }).values)

                /** A partial response to show before the server answers; absent fields leave the store untouched. */
                class Episode(val id: String? = null, val name: String? = null, val air_date: String? = null, val episode: String? = null) {
                    /** The response's data as a variable, an absent field left out. */
                    @Generated
                    val variable: Variable
                        get() = Variable.Object(Variables.of("id" to this.id?.let { Variable.of(it) }, "name" to this.name?.let { Variable.of(it) }, "air_date" to this.air_date?.let { Variable.of(it) }, "episode" to this.episode?.let { Variable.of(it) }).values)
                }
            }
        }
    }
}

private object `TestAppendEpisodeNodes-plan` {
    val selection0: Selection by lazy {
        Selection(type = Types.Mutation, key = listOf(), isAbstract = false, fields = listOf(
            PlanField.linked("rename", key = StorageKey.Fixed(Slots.Mutation.rename), plural = false, selection = selection1),
        ))
    }
    val selection1: Selection by lazy {
        Selection(type = Types.FavoritePayload, key = listOf(), isAbstract = false, fields = listOf(
            PlanField.linked("character", key = StorageKey.Fixed(Slots.FavoritePayload.character), plural = false, selection = selection2),
        ))
    }
    val selection2: Selection by lazy {
        Selection(type = Types.Character, key = listOf("id"), isAbstract = false, fields = listOf(
            PlanField.scalar("id", key = StorageKey.Fixed(Slots.Character.id), kind = ScalarKind.STRING, list = false),
            PlanField.linked("episode", key = StorageKey.Fixed(Slots.Character.episode), plural = true, edit = Edit(kind = Edit.Kind.APPEND_NODE, connections = Edit.Connections.Variable("connections"), edgeType = Types.NoteEdge), selection = selection3),
        ))
    }
    val selection3: Selection by lazy {
        Selection(type = Types.Episode, key = listOf("id"), isAbstract = false, fields = listOf(
            PlanField.scalar("id", key = StorageKey.Fixed(Slots.Episode.id), kind = ScalarKind.STRING, list = false),
            PlanField.scalar("name", key = StorageKey.Fixed(Slots.Episode.name), kind = ScalarKind.STRING, list = false),
            PlanField.scalar("air_date", key = StorageKey.Fixed(Slots.Episode.air_date), kind = ScalarKind.STRING, list = false),
            PlanField.scalar("episode", key = StorageKey.Fixed(Slots.Episode.episode), kind = ScalarKind.STRING, list = false),
        ))
    }
}

/** Commits the mutation; the optimistic response, if any, shows at once and rebases until the server answers. */
suspend operator fun MutationAction<TestAppendEpisodeNodes, TestAppendEpisodeNodes.Data>.invoke(id: String, name: String, connections: List<String>, optimistic: TestAppendEpisodeNodes.OptimisticResponse? = null): TestAppendEpisodeNodes.Data = this.commit(TestAppendEpisodeNodes(id, name, connections), optimistic?.payload)
