// Generated by batonc. Do not edit.
@file:OptIn(baton.Generated::class)

package baton.goldens

import baton.Anchor
import baton.Document
import baton.Lens
import baton.OperationHandle
import baton.OperationKind
import baton.OperationType
import baton.Plan
import baton.PlanField
import baton.QueryOperation
import baton.Resolution
import baton.ScalarKind
import baton.Selection
import baton.StorageKey
import baton.Variable
import baton.Variables

/** Operation value for `query TestAssetPricesQuery`. */
class TestAssetPricesQuery : QueryOperation<TestAssetPricesQuery.Data> {
    override val variables: Variables
        get() = Variables.none
    override var resolution: Resolution<OperationHandle<Data>> = Resolution.Unresolved
    override val type: OperationType<Data> get() = Companion

    override fun equals(other: Any?): Boolean = other is TestAssetPricesQuery
    override fun hashCode(): Int = 0

    companion object : OperationType<Data> {
        override val name = "TestAssetPricesQuery"
        override val document: Document = Document.Text("query TestAssetPricesQuery{assets{uuid,price,listedAt,page,prices,id}}")
        override val kind = OperationKind.QUERY
        override val plan: Plan by lazy { Plan(root = selection0, transient = Types.transient) }
        private val selection0: Selection by lazy {
            Selection(type = Types.Query, key = listOf(), isAbstract = false, fields = listOf(
                PlanField.linked("assets", key = StorageKey.Fixed(Slots.Query.assets), plural = true, selection = selection1),
            ))
        }
        private val selection1: Selection by lazy {
            Selection(type = Types.Asset, key = listOf("uuid"), isAbstract = false, fields = listOf(
                PlanField.scalar("uuid", key = StorageKey.Fixed(Slots.Asset.uuid), kind = ScalarKind.STRING, list = false),
                PlanField.scalar("price", key = StorageKey.Fixed(Slots.Asset.price), kind = ScalarKind.CUSTOM, list = false),
                PlanField.scalar("listedAt", key = StorageKey.Fixed(Slots.Asset.listedAt), kind = ScalarKind.CUSTOM, list = false),
                PlanField.scalar("page", key = StorageKey.Fixed(Slots.Asset.page), kind = ScalarKind.CUSTOM, list = false),
                PlanField.scalar("prices", key = StorageKey.Fixed(Slots.Asset.prices), kind = ScalarKind.CUSTOM, list = true),
                PlanField.scalar("id", key = StorageKey.Fixed(Slots.Asset.id), kind = ScalarKind.STRING, list = false),
            ))
        }

        override fun data(anchor: Anchor): Data = Data(anchor)
    }

    class Data(override val anchor: Anchor) : Lens
}

/** Operation value for `query TestPricedAssetsQuery`. */
class TestPricedAssetsQuery(val price: java.math.BigDecimal, val among: List<java.math.BigDecimal>? = null) : QueryOperation<TestPricedAssetsQuery.Data> {
    override val variables: Variables
        get() = Variables(buildMap {
            put("price", Variable.of(price, baton.scalars.Decimals))
            if (among != null) put("among", Variable.List(among.map { Variable.of(it, baton.scalars.Decimals) }))
        })
    override var resolution: Resolution<OperationHandle<Data>> = Resolution.Unresolved
    override val type: OperationType<Data> get() = Companion

    override fun equals(other: Any?): Boolean = other is TestPricedAssetsQuery && other.price == price && other.among == among
    override fun hashCode(): Int = listOf(price, among).hashCode()

    companion object : OperationType<Data> {
        override val name = "TestPricedAssetsQuery"
        override val document: Document = Document.Text("query TestPricedAssetsQuery(\$price:Decimal!,\$among:[Decimal!]){assetsPricedAbove(price:\$price,among:\$among){uuid,...TestCaughtPrices_asset,...TestThrowingPrices_asset,...TestRequiredPrice_asset,id}}fragment TestCaughtPrices_asset on Asset{price,listedAt,page}fragment TestRequiredPrice_asset on Asset{price}fragment TestThrowingPrices_asset on Asset{price,prices}")
        override val kind = OperationKind.QUERY
        override val plan: Plan by lazy { Plan(root = selection0, transient = Types.transient) }
        private val selection0: Selection by lazy {
            Selection(type = Types.Query, key = listOf(), isAbstract = false, fields = listOf(
                PlanField.linked("assetsPricedAbove", key = StorageKey.Dynamic(Slots.Query.assetsPricedAbove_914469), plural = true, selection = selection1),
            ))
        }
        private val selection1: Selection by lazy {
            Selection(type = Types.Asset, key = listOf("uuid"), isAbstract = false, fields = listOf(
                PlanField.scalar("uuid", key = StorageKey.Fixed(Slots.Asset.uuid), kind = ScalarKind.STRING, list = false),
                PlanField.scalar("price", key = StorageKey.Fixed(Slots.Asset.price), kind = ScalarKind.CUSTOM, list = false, caught = true),
                PlanField.scalar("listedAt", key = StorageKey.Fixed(Slots.Asset.listedAt), kind = ScalarKind.CUSTOM, list = false, caught = true),
                PlanField.scalar("page", key = StorageKey.Fixed(Slots.Asset.page), kind = ScalarKind.CUSTOM, list = false, caught = true),
                PlanField.scalar("prices", key = StorageKey.Fixed(Slots.Asset.prices), kind = ScalarKind.CUSTOM, list = true),
                PlanField.scalar("id", key = StorageKey.Fixed(Slots.Asset.id), kind = ScalarKind.STRING, list = false),
            ))
        }

        override fun data(anchor: Anchor): Data = Data(anchor)
    }

    class Data(override val anchor: Anchor) : Lens
}
