// Generated by batonc. Do not edit.
@file:OptIn(baton.Generated::class)

package baton.goldens

import androidx.compose.runtime.Immutable
import androidx.compose.runtime.Stable
import baton.Anchor
import baton.Document
import baton.FieldError
import baton.FieldErrors
import baton.Lens
import baton.OperationKind
import baton.OperationType
import baton.Plan
import baton.PlanField
import baton.QueryOperation
import baton.QueryType
import baton.ScalarKind
import baton.Selection
import baton.StorageKey
import baton.Variable
import baton.Variables

/** Lens for `fragment TestCaughtPrices_asset on Asset`. */
@Stable
class TestCaughtPrices_asset(override val anchor: Anchor) : Lens {
    val price: Result<java.math.BigDecimal?> get() = anchor.caughtOptionalMapped(Slots.Asset.price, "price", baton.scalars.Decimals)
    val listedAt: Result<java.time.Instant> get() = anchor.caughtMapped(Slots.Asset.listedAt, "listedAt", baton.scalars.DateTimes)
    val page: java.net.URI? get() = anchor.mapped(Slots.Asset.page, baton.scalars.Urls)
    override fun equals(other: Any?): Boolean = other is TestCaughtPrices_asset && other.anchor == anchor
    override fun hashCode(): Int = anchor.hashCode()
}

/** Lens for `fragment TestRequiredPrice_asset on Asset`. */
@Stable
class TestRequiredPrice_asset(override val anchor: Anchor) : Lens {
    val price: java.math.BigDecimal get() = anchor.throwingMapped(Slots.Asset.price, "price", baton.scalars.Decimals)
    override fun equals(other: Any?): Boolean = other is TestRequiredPrice_asset && other.anchor == anchor
    override fun hashCode(): Int = anchor.hashCode()

    companion object {
        /** Whether every `@required` field is present; the lens is otherwise null to its parent, as Relay bubbles. */
        fun satisfied(anchor: Anchor): Boolean {
            if (!anchor.converts(Slots.Asset.price, baton.scalars.Decimals, "price", log = false)) return false
            return true
        }
    }
}

/** Lens for `fragment TestThrowingPrices_asset on Asset`. */
@Stable
class TestThrowingPrices_asset(override val anchor: Anchor) : Lens {
    val price: java.math.BigDecimal? get() = anchor.mapped(Slots.Asset.price, baton.scalars.Decimals)
    val prices: List<java.math.BigDecimal?>? get() = anchor.nullableMappedList(Slots.Asset.prices, baton.scalars.Decimals)
    override fun equals(other: Any?): Boolean = other is TestThrowingPrices_asset && other.anchor == anchor
    override fun hashCode(): Int = anchor.hashCode()

    companion object {
        /** The field errors in this selection, for `@catch` and `@throwOnFieldError`. */
        fun fieldErrors(anchor: Anchor): List<FieldError> {
            val errors = mutableListOf<FieldError>()
            anchor.collectError(Slots.Asset.price, errors)
            anchor.collectConversion(Slots.Asset.price, baton.scalars.Decimals, "price", errors)
            anchor.collectError(Slots.Asset.prices, errors)
            return errors
        }
        /** The lens, or the field errors in it as a thrown `FieldErrors`. */
        fun throwing(anchor: Anchor): TestThrowingPrices_asset = caught(anchor).getOrThrow()
        /** The lens, or the field errors in it as a `Result`. */
        fun caught(anchor: Anchor): Result<TestThrowingPrices_asset> {
            val errors = fieldErrors(anchor)
            return if (errors.isEmpty()) Result.success(TestThrowingPrices_asset(anchor)) else Result.failure(FieldErrors(errors))
        }
    }
}

/** Operation value for `query TestAssetPricesQuery`. */
@Immutable
class TestAssetPricesQuery : QueryOperation<TestAssetPricesQuery.Data> {
    override val variables: Variables
        get() = Variables.none
    override val type: OperationType<Data> get() = Companion

    override fun equals(other: Any?): Boolean = other is TestAssetPricesQuery
    override fun hashCode(): Int = 0

    companion object : QueryType<TestAssetPricesQuery, TestAssetPricesQuery.Data> {
        override val name = "TestAssetPricesQuery"
        override val document: Document = Document.Text("query TestAssetPricesQuery{assets{uuid,price,listedAt,page,prices,id}}")
        override val kind = OperationKind.QUERY
        override val plan: Plan by lazy { Plan(root = `TestAssetPricesQuery-plan`.selection0, transient = Types.transient) }

        override fun data(anchor: Anchor): Data = Data(anchor)
    }

    @Stable
    class Data(override val anchor: Anchor) : Lens {
        val assets: List<Assets>? get() = anchor.list(Slots.Query.assets, ::Assets)
        override fun equals(other: Any?): Boolean = other is TestAssetPricesQuery.Data && other.anchor == anchor
        override fun hashCode(): Int = anchor.hashCode()

        @Stable
        class Assets(override val anchor: Anchor) : Lens {
            val uuid: String get() = anchor.requiredString(Slots.Asset.uuid)
            val price: java.math.BigDecimal? get() = anchor.mapped(Slots.Asset.price, baton.scalars.Decimals)
            val listedAt: java.time.Instant? get() = anchor.mapped(Slots.Asset.listedAt, baton.scalars.DateTimes)
            val page: java.net.URI? get() = anchor.mapped(Slots.Asset.page, baton.scalars.Urls)
            val prices: List<java.math.BigDecimal?>? get() = anchor.nullableMappedList(Slots.Asset.prices, baton.scalars.Decimals)
            override fun equals(other: Any?): Boolean = other is TestAssetPricesQuery.Data.Assets && other.anchor == anchor
            override fun hashCode(): Int = anchor.hashCode()
        }
    }
}

private object `TestAssetPricesQuery-plan` {
    val selection0: Selection by lazy {
        Selection(type = Types.Query, key = listOf(), isAbstract = false, fields = listOf(
            PlanField.linked("assets", key = StorageKey.Fixed(Slots.Query.assets), plural = true, selection = selection1),
        ))
    }
    val selection1: Selection by lazy {
        Selection(type = Types.Asset, key = listOf("uuid"), isAbstract = false, fields = listOf(
            PlanField.scalar("uuid", key = StorageKey.Fixed(Slots.Asset.uuid), kind = ScalarKind.STRING, list = false),
            PlanField.scalar("price", key = StorageKey.Fixed(Slots.Asset.price), kind = ScalarKind.CUSTOM, list = false),
            PlanField.scalar("listedAt", key = StorageKey.Fixed(Slots.Asset.listedAt), kind = ScalarKind.CUSTOM, list = false),
            PlanField.scalar("page", key = StorageKey.Fixed(Slots.Asset.page), kind = ScalarKind.CUSTOM, list = false),
            PlanField.scalar("prices", key = StorageKey.Fixed(Slots.Asset.prices), kind = ScalarKind.CUSTOM, list = true),
            PlanField.scalar("id", key = StorageKey.Fixed(Slots.Asset.id), kind = ScalarKind.STRING, list = false),
        ))
    }
}

/** Operation value for `query TestPricedAssetsQuery`. */
@Immutable
class TestPricedAssetsQuery(val price: java.math.BigDecimal, val among: List<java.math.BigDecimal>? = null) : QueryOperation<TestPricedAssetsQuery.Data> {
    override val variables: Variables
        get() = Variables.of("price" to Variable.of(price, baton.scalars.Decimals), "among" to among?.let { Variable.List(it.map { Variable.of(it, baton.scalars.Decimals) }) })
    override val type: OperationType<Data> get() = Companion

    override fun equals(other: Any?): Boolean = other is TestPricedAssetsQuery && other.price == price && other.among == among
    override fun hashCode(): Int = listOf(price, among).hashCode()

    companion object : QueryType<TestPricedAssetsQuery, TestPricedAssetsQuery.Data> {
        override val name = "TestPricedAssetsQuery"
        override val document: Document = Document.Text("query TestPricedAssetsQuery(\$price:Decimal!,\$among:[Decimal!]){assetsPricedAbove(price:\$price,among:\$among){uuid,...TestCaughtPrices_asset,...TestThrowingPrices_asset,...TestRequiredPrice_asset,id}}fragment TestCaughtPrices_asset on Asset{price,listedAt,page}fragment TestRequiredPrice_asset on Asset{price}fragment TestThrowingPrices_asset on Asset{price,prices}")
        override val kind = OperationKind.QUERY
        override val plan: Plan by lazy { Plan(root = `TestPricedAssetsQuery-plan`.selection0, transient = Types.transient) }

        override fun data(anchor: Anchor): Data = Data(anchor)
    }

    @Stable
    class Data(override val anchor: Anchor) : Lens {
        val assetsPricedAbove: List<AssetsPricedAbove>? get() = anchor.list(anchor.owner.slot(Slots.Query.assetsPricedAbove_914469), ::AssetsPricedAbove)
        override fun equals(other: Any?): Boolean = other is TestPricedAssetsQuery.Data && other.anchor == anchor
        override fun hashCode(): Int = anchor.hashCode()

        @Stable
        class AssetsPricedAbove(override val anchor: Anchor) : Lens {
            val uuid: String get() = anchor.requiredString(Slots.Asset.uuid)
            val testCaughtPrices: TestCaughtPrices_asset get() = TestCaughtPrices_asset(anchor.entering())
            val testThrowingPrices: TestThrowingPrices_asset get() = TestThrowingPrices_asset.throwing(anchor.entering())
            val testRequiredPrice: TestRequiredPrice_asset?
                get() {
                    if (!TestRequiredPrice_asset.satisfied(anchor)) return null
                    return TestRequiredPrice_asset(anchor.entering())
                }
            override fun equals(other: Any?): Boolean = other is TestPricedAssetsQuery.Data.AssetsPricedAbove && other.anchor == anchor
            override fun hashCode(): Int = anchor.hashCode()
        }
    }
}

private object `TestPricedAssetsQuery-plan` {
    val selection0: Selection by lazy {
        Selection(type = Types.Query, key = listOf(), isAbstract = false, fields = listOf(
            PlanField.linked("assetsPricedAbove", key = StorageKey.Dynamic(Slots.Query.assetsPricedAbove_914469), plural = true, selection = selection1),
        ))
    }
    val selection1: Selection by lazy {
        Selection(type = Types.Asset, key = listOf("uuid"), isAbstract = false, fields = listOf(
            PlanField.scalar("uuid", key = StorageKey.Fixed(Slots.Asset.uuid), kind = ScalarKind.STRING, list = false),
            PlanField.scalar("price", key = StorageKey.Fixed(Slots.Asset.price), kind = ScalarKind.CUSTOM, list = false, caught = true),
            PlanField.scalar("listedAt", key = StorageKey.Fixed(Slots.Asset.listedAt), kind = ScalarKind.CUSTOM, list = false, caught = true),
            PlanField.scalar("page", key = StorageKey.Fixed(Slots.Asset.page), kind = ScalarKind.CUSTOM, list = false, caught = true),
            PlanField.scalar("prices", key = StorageKey.Fixed(Slots.Asset.prices), kind = ScalarKind.CUSTOM, list = true),
            PlanField.scalar("id", key = StorageKey.Fixed(Slots.Asset.id), kind = ScalarKind.STRING, list = false),
        ))
    }
}
