// Generated by batonc. Do not edit.
@file:OptIn(baton.Generated::class)

package baton.goldens

import androidx.compose.runtime.Stable
import baton.Anchor
import baton.Document
import baton.Lens
import baton.Lookup
import baton.OperationHandle
import baton.OperationKind
import baton.OperationType
import baton.Plan
import baton.PlanField
import baton.QueryOperation
import baton.Resolution
import baton.ScalarKind
import baton.Selection
import baton.StorageKey
import baton.Variable
import baton.Variables

/** Operation value for `query TestCharacterSecret`. */
class TestCharacterSecret : QueryOperation<TestCharacterSecret.Data> {
    override val variables: Variables
        get() = Variables.none
    override var resolution: Resolution<OperationHandle<Data>> = Resolution.Unresolved
    override val type: OperationType<Data> get() = Companion

    override fun equals(other: Any?): Boolean = other is TestCharacterSecret
    override fun hashCode(): Int = 0

    companion object : OperationType<Data> {
        override val name = "TestCharacterSecret"
        override val document: Document = Document.Text("query TestCharacterSecret{character(id:\"1\"){id,name,secret{id,body}}}")
        override val kind = OperationKind.QUERY
        override val plan: Plan by lazy { Plan(root = `TestCharacterSecret-plan`.selection0, transient = Types.transient) }

        override fun data(anchor: Anchor): Data = Data(anchor)
    }

    @Stable
    class Data(override val anchor: Anchor) : Lens {
        val character: Character? get() = anchor.linked(Slots.Query.character_9e6829)?.let(::Character)
        override fun equals(other: Any?): Boolean = other is TestCharacterSecret.Data && other.anchor == anchor
        override fun hashCode(): Int = anchor.hashCode()

        @Stable
        class Character(override val anchor: Anchor) : Lens {
            val id: String? get() = anchor.string(Slots.Character.id)
            val name: String? get() = anchor.string(Slots.Character.name)
            val secret: Secret? get() = anchor.linked(Slots.Character.secret)?.let(::Secret)
            override fun equals(other: Any?): Boolean = other is TestCharacterSecret.Data.Character && other.anchor == anchor
            override fun hashCode(): Int = anchor.hashCode()

            @Stable
            class Secret(override val anchor: Anchor) : Lens {
                val id: String? get() = anchor.string(Slots.Secret.id)
                val body: String? get() = anchor.string(Slots.Secret.body)
                override fun equals(other: Any?): Boolean = other is TestCharacterSecret.Data.Character.Secret && other.anchor == anchor
                override fun hashCode(): Int = anchor.hashCode()
            }
        }
    }
}

private object `TestCharacterSecret-plan` {
    val selection0: Selection by lazy {
        Selection(type = Types.Query, key = listOf(), isAbstract = false, fields = listOf(
            PlanField.linked("character", key = StorageKey.Fixed(Slots.Query.character_9e6829), plural = false, lookup = Lookup(type = Types.Character, key = listOf(Lookup.Key.Literal("1"))), selection = selection1),
        ))
    }
    val selection1: Selection by lazy {
        Selection(type = Types.Character, key = listOf("id"), isAbstract = false, fields = listOf(
            PlanField.scalar("id", key = StorageKey.Fixed(Slots.Character.id), kind = ScalarKind.STRING, list = false),
            PlanField.scalar("name", key = StorageKey.Fixed(Slots.Character.name), kind = ScalarKind.STRING, list = false),
            PlanField.linked("secret", key = StorageKey.Fixed(Slots.Character.secret), plural = false, selection = selection2),
        ))
    }
    val selection2: Selection by lazy {
        Selection(type = Types.Secret, key = listOf("id"), isAbstract = false, fields = listOf(
            PlanField.scalar("id", key = StorageKey.Fixed(Slots.Secret.id), kind = ScalarKind.STRING, list = false),
            PlanField.scalar("body", key = StorageKey.Fixed(Slots.Secret.body), kind = ScalarKind.STRING, list = false),
        ))
    }
}

/** Operation value for `query TestSecrets`. */
class TestSecrets(val code: String) : QueryOperation<TestSecrets.Data> {
    override val variables: Variables
        get() = Variables.of("code" to Variable.of(code))
    override var resolution: Resolution<OperationHandle<Data>> = Resolution.Unresolved
    override val type: OperationType<Data> get() = Companion

    override fun equals(other: Any?): Boolean = other is TestSecrets && other.code == code
    override fun hashCode(): Int = listOf(code).hashCode()

    companion object : OperationType<Data> {
        override val name = "TestSecrets"
        override val document: Document = Document.Text("query TestSecrets(\$code:String!){secrets(code:\$code){id,body},character(id:\"1\"){id,name}}")
        override val kind = OperationKind.QUERY
        override val plan: Plan by lazy { Plan(root = `TestSecrets-plan`.selection0, transient = Types.transient) }

        override fun data(anchor: Anchor): Data = Data(anchor)
    }

    @Stable
    class Data(override val anchor: Anchor) : Lens {
        val secrets: List<Secrets>? get() = anchor.list(anchor.owner.slot(Slots.Query.secrets_df579e), ::Secrets)
        val character: Character? get() = anchor.linked(Slots.Query.character_9e6829)?.let(::Character)
        override fun equals(other: Any?): Boolean = other is TestSecrets.Data && other.anchor == anchor
        override fun hashCode(): Int = anchor.hashCode()

        @Stable
        class Secrets(override val anchor: Anchor) : Lens {
            val id: String? get() = anchor.string(Slots.Secret.id)
            val body: String? get() = anchor.string(Slots.Secret.body)
            override fun equals(other: Any?): Boolean = other is TestSecrets.Data.Secrets && other.anchor == anchor
            override fun hashCode(): Int = anchor.hashCode()
        }

        @Stable
        class Character(override val anchor: Anchor) : Lens {
            val id: String? get() = anchor.string(Slots.Character.id)
            val name: String? get() = anchor.string(Slots.Character.name)
            override fun equals(other: Any?): Boolean = other is TestSecrets.Data.Character && other.anchor == anchor
            override fun hashCode(): Int = anchor.hashCode()
        }
    }
}

private object `TestSecrets-plan` {
    val selection0: Selection by lazy {
        Selection(type = Types.Query, key = listOf(), isAbstract = false, fields = listOf(
            PlanField.linked("secrets", key = StorageKey.Dynamic(Slots.Query.secrets_df579e), plural = true, transient = true, selection = selection2),
            PlanField.linked("character", key = StorageKey.Fixed(Slots.Query.character_9e6829), plural = false, lookup = Lookup(type = Types.Character, key = listOf(Lookup.Key.Literal("1"))), selection = selection1),
        ))
    }
    val selection1: Selection by lazy {
        Selection(type = Types.Character, key = listOf("id"), isAbstract = false, fields = listOf(
            PlanField.scalar("id", key = StorageKey.Fixed(Slots.Character.id), kind = ScalarKind.STRING, list = false),
            PlanField.scalar("name", key = StorageKey.Fixed(Slots.Character.name), kind = ScalarKind.STRING, list = false),
        ))
    }
    val selection2: Selection by lazy {
        Selection(type = Types.Secret, key = listOf("id"), isAbstract = false, fields = listOf(
            PlanField.scalar("id", key = StorageKey.Fixed(Slots.Secret.id), kind = ScalarKind.STRING, list = false),
            PlanField.scalar("body", key = StorageKey.Fixed(Slots.Secret.body), kind = ScalarKind.STRING, list = false),
        ))
    }
}
