// Generated by batonc. Do not edit.
@file:OptIn(baton.Generated::class)

package baton.goldens

import androidx.compose.runtime.Stable
import baton.Anchor
import baton.Document
import baton.Generated
import baton.Guard
import baton.Lens
import baton.Lookup
import baton.MutationAction
import baton.MutationOperation
import baton.OperationHandle
import baton.OperationKind
import baton.OperationType
import baton.Payload
import baton.Plan
import baton.PlanField
import baton.QueryOperation
import baton.Resolution
import baton.ScalarKind
import baton.Selection
import baton.StorageKey
import baton.Variable
import baton.Variables

/** Lens for `fragment TestFavorite_character on Character`. */
@Stable
class TestFavorite_character(override val anchor: Anchor) : Lens {
    val id: String? get() = anchor.string(Slots.Character.id)
    val name: String? get() = anchor.string(Slots.Character.name)
    val favorite: Boolean? get() = anchor.bool(Slots.Character.favorite)
    override fun equals(other: Any?): Boolean = other is TestFavorite_character && other.anchor == anchor
    override fun hashCode(): Int = anchor.hashCode()
}

/** Lens for `fragment TestRenamePayload_mutation on Mutation`. */
@Stable
class TestRenamePayload_mutation(override val anchor: Anchor) : Lens {
    val rename: Rename? get() = anchor.linked(Slots.Mutation.rename)?.let(::Rename)
    override fun equals(other: Any?): Boolean = other is TestRenamePayload_mutation && other.anchor == anchor
    override fun hashCode(): Int = anchor.hashCode()

    @Stable
    class Rename(override val anchor: Anchor) : Lens {
        val character: Character? get() = anchor.linked(Slots.FavoritePayload.character)?.let(::Character)
        override fun equals(other: Any?): Boolean = other is TestRenamePayload_mutation.Rename && other.anchor == anchor
        override fun hashCode(): Int = anchor.hashCode()

        @Stable
        class Character(override val anchor: Anchor) : Lens {
            val id: String? get() = anchor.string(Slots.Character.id)
            val name: String? get() = anchor.string(Slots.Character.name)
            override fun equals(other: Any?): Boolean = other is TestRenamePayload_mutation.Rename.Character && other.anchor == anchor
            override fun hashCode(): Int = anchor.hashCode()
        }
    }
}

/** Operation value for `query TestFavoriteQuery`. */
class TestFavoriteQuery(val id: String) : QueryOperation<TestFavoriteQuery.Data> {
    override val variables: Variables
        get() = Variables.of("id" to Variable.of(id))
    override var resolution: Resolution<OperationHandle<Data>> = Resolution.Unresolved
    override val type: OperationType<Data> get() = Companion

    override fun equals(other: Any?): Boolean = other is TestFavoriteQuery && other.id == id
    override fun hashCode(): Int = listOf(id).hashCode()

    companion object : OperationType<Data> {
        override val name = "TestFavoriteQuery"
        override val document: Document = Document.Text("query TestFavoriteQuery(\$id:ID!){character(id:\$id){id,...TestFavorite_character}}fragment TestFavorite_character on Character{id,name,favorite}")
        override val kind = OperationKind.QUERY
        override val plan: Plan by lazy { Plan(root = selection0, transient = Types.transient) }
        private val selection0: Selection by lazy {
            Selection(type = Types.Query, key = listOf(), isAbstract = false, fields = listOf(
                PlanField.linked("character", key = StorageKey.Dynamic(Slots.Query.character_bca4f9), plural = false, lookup = Lookup(type = Types.Character, key = listOf(Lookup.Key.Variable("id"))), selection = selection1),
            ))
        }
        private val selection1: Selection by lazy {
            Selection(type = Types.Character, key = listOf("id"), isAbstract = false, fields = listOf(
                PlanField.scalar("id", key = StorageKey.Fixed(Slots.Character.id), kind = ScalarKind.STRING, list = false),
                PlanField.scalar("name", key = StorageKey.Fixed(Slots.Character.name), kind = ScalarKind.STRING, list = false),
                PlanField.scalar("favorite", key = StorageKey.Fixed(Slots.Character.favorite), kind = ScalarKind.BOOL, list = false),
            ))
        }

        override fun data(anchor: Anchor): Data = Data(anchor)
    }

    @Stable
    class Data(override val anchor: Anchor) : Lens {
        val character: Character? get() = anchor.linked(anchor.owner.slot(Slots.Query.character_bca4f9))?.let(::Character)
        override fun equals(other: Any?): Boolean = other is TestFavoriteQuery.Data && other.anchor == anchor
        override fun hashCode(): Int = anchor.hashCode()

        @Stable
        class Character(override val anchor: Anchor) : Lens {
            val id: String? get() = anchor.string(Slots.Character.id)
            val testFavorite: TestFavorite_character get() = TestFavorite_character(anchor.entering())
            override fun equals(other: Any?): Boolean = other is TestFavoriteQuery.Data.Character && other.anchor == anchor
            override fun hashCode(): Int = anchor.hashCode()
        }
    }
}

/** Operation value for `query TestNode`. */
class TestNode(val id: String) : QueryOperation<TestNode.Data> {
    override val variables: Variables
        get() = Variables.of("id" to Variable.of(id))
    override var resolution: Resolution<OperationHandle<Data>> = Resolution.Unresolved
    override val type: OperationType<Data> get() = Companion

    override fun equals(other: Any?): Boolean = other is TestNode && other.id == id
    override fun hashCode(): Int = listOf(id).hashCode()

    companion object : OperationType<Data> {
        override val name = "TestNode"
        override val document: Document = Document.Text("query TestNode(\$id:ID!){node(id:\$id){__typename,...on Character{id,name},...on Episode{id,name},id}}")
        override val kind = OperationKind.QUERY
        override val plan: Plan by lazy { Plan(root = selection0, transient = Types.transient) }
        private val selection0: Selection by lazy {
            Selection(type = Types.Query, key = listOf(), isAbstract = false, fields = listOf(
                PlanField.linked("node", key = StorageKey.Dynamic(Slots.Query.node_8f7d08), plural = false, lookup = Lookup(type = null, possibleTypes = Types.Node_keyed, key = listOf(Lookup.Key.Variable("id"))), selection = selection1),
            ))
        }
        private val selection1: Selection by lazy {
            Selection(type = Types.Node, key = listOf("id"), isAbstract = true, variants = listOf(
                Selection.Variant(types = listOf(Types.Character, Types.Episode), key = listOf("id"), fields = listOf(
                    PlanField.scalar("__typename", key = StorageKey.Fixed(Slots.Node.__typename), kind = ScalarKind.STRING, list = false),
                    PlanField.scalar("id", key = StorageKey.Fixed(Slots.Node.id), kind = ScalarKind.STRING, list = false),
                    PlanField.scalar("name", key = StorageKey.Fixed(Slots.Node.name), kind = ScalarKind.STRING, list = false),
                )),
                Selection.Variant(types = null, fields = listOf(
                    PlanField.scalar("__typename", key = StorageKey.Fixed(Slots.Node.__typename), kind = ScalarKind.STRING, list = false),
                    PlanField.scalar("id", key = StorageKey.Fixed(Slots.Node.id), kind = ScalarKind.STRING, list = false),
                )),
            ))
        }

        override fun data(anchor: Anchor): Data = Data(anchor)
    }

    @Stable
    class Data(override val anchor: Anchor) : Lens {
        val node: Node? get() = anchor.linked(anchor.owner.slot(Slots.Query.node_8f7d08))?.let(::Node)
        override fun equals(other: Any?): Boolean = other is TestNode.Data && other.anchor == anchor
        override fun hashCode(): Int = anchor.hashCode()

        @Stable
        class Node(override val anchor: Anchor) : Lens {
            val asCharacter: AsCharacter? get() = if (anchor.record.type == Types.Character) AsCharacter(anchor) else null
            val asEpisode: AsEpisode? get() = if (anchor.record.type == Types.Episode) AsEpisode(anchor) else null
            override fun equals(other: Any?): Boolean = other is TestNode.Data.Node && other.anchor == anchor
            override fun hashCode(): Int = anchor.hashCode()

            @Stable
            class AsCharacter(override val anchor: Anchor) : Lens {
                val id: String? get() = anchor.string(Slots.Character.id)
                val name: String? get() = anchor.string(Slots.Character.name)
                override fun equals(other: Any?): Boolean = other is TestNode.Data.Node.AsCharacter && other.anchor == anchor
                override fun hashCode(): Int = anchor.hashCode()
            }

            @Stable
            class AsEpisode(override val anchor: Anchor) : Lens {
                val id: String? get() = anchor.string(Slots.Episode.id)
                val name: String? get() = anchor.string(Slots.Episode.name)
                override fun equals(other: Any?): Boolean = other is TestNode.Data.Node.AsEpisode && other.anchor == anchor
                override fun hashCode(): Int = anchor.hashCode()
            }
        }
    }
}

/** Operation value for `mutation TestRename`. */
class TestRename(val id: String, val name: String) : MutationOperation<TestRename.Data> {
    override val variables: Variables
        get() = Variables.of("id" to Variable.of(id), "name" to Variable.of(name))
    override val type: OperationType<Data> get() = Companion

    override fun equals(other: Any?): Boolean = other is TestRename && other.id == id && other.name == name
    override fun hashCode(): Int = listOf(id, name).hashCode()

    companion object : OperationType<Data> {
        override val name = "TestRename"
        override val document: Document = Document.Text("mutation TestRename(\$id:ID!,\$name:String!){rename(id:\$id,name:\$name){character{id,name}}}")
        override val kind = OperationKind.MUTATION
        override val plan: Plan by lazy { Plan(root = selection0, transient = Types.transient) }
        private val selection0: Selection by lazy {
            Selection(type = Types.Mutation, key = listOf(), isAbstract = false, fields = listOf(
                PlanField.linked("rename", key = StorageKey.Fixed(Slots.Mutation.rename), plural = false, selection = selection1),
            ))
        }
        private val selection1: Selection by lazy {
            Selection(type = Types.FavoritePayload, key = listOf(), isAbstract = false, fields = listOf(
                PlanField.linked("character", key = StorageKey.Fixed(Slots.FavoritePayload.character), plural = false, selection = selection2),
            ))
        }
        private val selection2: Selection by lazy {
            Selection(type = Types.Character, key = listOf("id"), isAbstract = false, fields = listOf(
                PlanField.scalar("id", key = StorageKey.Fixed(Slots.Character.id), kind = ScalarKind.STRING, list = false),
                PlanField.scalar("name", key = StorageKey.Fixed(Slots.Character.name), kind = ScalarKind.STRING, list = false),
            ))
        }

        override fun data(anchor: Anchor): Data = Data(anchor)
    }

    @Stable
    class Data(override val anchor: Anchor) : Lens {
        val rename: Rename? get() = anchor.linked(Slots.Mutation.rename)?.let(::Rename)
        override fun equals(other: Any?): Boolean = other is TestRename.Data && other.anchor == anchor
        override fun hashCode(): Int = anchor.hashCode()

        @Stable
        class Rename(override val anchor: Anchor) : Lens {
            val character: Character? get() = anchor.linked(Slots.FavoritePayload.character)?.let(::Character)
            override fun equals(other: Any?): Boolean = other is TestRename.Data.Rename && other.anchor == anchor
            override fun hashCode(): Int = anchor.hashCode()

            @Stable
            class Character(override val anchor: Anchor) : Lens {
                val id: String? get() = anchor.string(Slots.Character.id)
                val name: String? get() = anchor.string(Slots.Character.name)
                override fun equals(other: Any?): Boolean = other is TestRename.Data.Rename.Character && other.anchor == anchor
                override fun hashCode(): Int = anchor.hashCode()
            }
        }
    }

    /** A partial response to show before the server answers; absent fields leave the store untouched. */
    class OptimisticResponse(val rename: Rename? = null) {
        /** The response's data as a variable, an absent field left out. */
        @Generated
        val variable: Variable
            get() = Variable.Object(Variables.of("rename" to this.rename?.variable).values)
        /** The response this builder describes, as the bytes the door takes. */
        val payload: Payload get() = Payload(data = variable)

        /** A partial response to show before the server answers; absent fields leave the store untouched. */
        class Rename(val character: Character? = null) {
            /** The response's data as a variable, an absent field left out. */
            @Generated
            val variable: Variable
                get() = Variable.Object(Variables.of("character" to this.character?.variable).values)

            /** A partial response to show before the server answers; absent fields leave the store untouched. */
            class Character(val id: String? = null, val name: String? = null) {
                /** The response's data as a variable, an absent field left out. */
                @Generated
                val variable: Variable
                    get() = Variable.Object(Variables.of("id" to this.id?.let { Variable.of(it) }, "name" to this.name?.let { Variable.of(it) }).values)
            }
        }
    }
}

/** Commits the mutation; the optimistic response, if any, shows at once and rebases until the server answers. */
suspend operator fun MutationAction<TestRename, TestRename.Data>.invoke(id: String, name: String, optimistic: TestRename.OptimisticResponse? = null): TestRename.Data = this.commit(TestRename(id, name), optimistic?.payload)

/** Operation value for `mutation TestRenameThroughFragment`. */
class TestRenameThroughFragment(val id: String, val name: String) : MutationOperation<TestRenameThroughFragment.Data> {
    override val variables: Variables
        get() = Variables.of("id" to Variable.of(id), "name" to Variable.of(name))
    override val type: OperationType<Data> get() = Companion

    override fun equals(other: Any?): Boolean = other is TestRenameThroughFragment && other.id == id && other.name == name
    override fun hashCode(): Int = listOf(id, name).hashCode()

    companion object : OperationType<Data> {
        override val name = "TestRenameThroughFragment"
        override val document: Document = Document.Text("mutation TestRenameThroughFragment(\$id:ID!,\$name:String!){...TestRenamePayload_mutation}fragment TestRenamePayload_mutation on Mutation{rename(id:\$id,name:\$name){character{id,name}}}")
        override val kind = OperationKind.MUTATION
        override val plan: Plan by lazy { Plan(root = selection0, transient = Types.transient) }
        private val selection0: Selection by lazy {
            Selection(type = Types.Mutation, key = listOf(), isAbstract = false, fields = listOf(
                PlanField.linked("rename", key = StorageKey.Fixed(Slots.Mutation.rename), plural = false, selection = selection1),
            ))
        }
        private val selection1: Selection by lazy {
            Selection(type = Types.FavoritePayload, key = listOf(), isAbstract = false, fields = listOf(
                PlanField.linked("character", key = StorageKey.Fixed(Slots.FavoritePayload.character), plural = false, selection = selection2),
            ))
        }
        private val selection2: Selection by lazy {
            Selection(type = Types.Character, key = listOf("id"), isAbstract = false, fields = listOf(
                PlanField.scalar("id", key = StorageKey.Fixed(Slots.Character.id), kind = ScalarKind.STRING, list = false),
                PlanField.scalar("name", key = StorageKey.Fixed(Slots.Character.name), kind = ScalarKind.STRING, list = false),
            ))
        }

        override fun data(anchor: Anchor): Data = Data(anchor)
    }

    @Stable
    class Data(override val anchor: Anchor) : Lens {
        val testRenamePayload: TestRenamePayload_mutation get() = TestRenamePayload_mutation(anchor.entering())
        override fun equals(other: Any?): Boolean = other is TestRenameThroughFragment.Data && other.anchor == anchor
        override fun hashCode(): Int = anchor.hashCode()
    }

    /** A partial response to show before the server answers; absent fields leave the store untouched. */
    class OptimisticResponse(val rename: Rename? = null) {
        /** The response's data as a variable, an absent field left out. */
        @Generated
        val variable: Variable
            get() = Variable.Object(Variables.of("rename" to this.rename?.variable).values)
        /** The response this builder describes, as the bytes the door takes. */
        val payload: Payload get() = Payload(data = variable)

        /** A partial response to show before the server answers; absent fields leave the store untouched. */
        class Rename(val character: Character? = null) {
            /** The response's data as a variable, an absent field left out. */
            @Generated
            val variable: Variable
                get() = Variable.Object(Variables.of("character" to this.character?.variable).values)

            /** A partial response to show before the server answers; absent fields leave the store untouched. */
            class Character(val id: String? = null, val name: String? = null) {
                /** The response's data as a variable, an absent field left out. */
                @Generated
                val variable: Variable
                    get() = Variable.Object(Variables.of("id" to this.id?.let { Variable.of(it) }, "name" to this.name?.let { Variable.of(it) }).values)
            }
        }
    }
}

/** Commits the mutation; the optimistic response, if any, shows at once and rebases until the server answers. */
suspend operator fun MutationAction<TestRenameThroughFragment, TestRenameThroughFragment.Data>.invoke(id: String, name: String, optimistic: TestRenameThroughFragment.OptimisticResponse? = null): TestRenameThroughFragment.Data = this.commit(TestRenameThroughFragment(id, name), optimistic?.payload)

/** Operation value for `mutation TestRenameWithOrigin`. */
class TestRenameWithOrigin(val id: String, val name: String, val withOrigin: Boolean) : MutationOperation<TestRenameWithOrigin.Data> {
    override val variables: Variables
        get() = Variables.of("id" to Variable.of(id), "name" to Variable.of(name), "withOrigin" to Variable.of(withOrigin))
    override val type: OperationType<Data> get() = Companion

    override fun equals(other: Any?): Boolean = other is TestRenameWithOrigin && other.id == id && other.name == name && other.withOrigin == withOrigin
    override fun hashCode(): Int = listOf(id, name, withOrigin).hashCode()

    companion object : OperationType<Data> {
        override val name = "TestRenameWithOrigin"
        override val document: Document = Document.Text("mutation TestRenameWithOrigin(\$id:ID!,\$name:String!,\$withOrigin:Boolean!){rename(id:\$id,name:\$name){character{id,name,origin@include(if:\$withOrigin){id,name}}}}")
        override val kind = OperationKind.MUTATION
        override val plan: Plan by lazy { Plan(root = selection0, transient = Types.transient) }
        private val selection0: Selection by lazy {
            Selection(type = Types.Mutation, key = listOf(), isAbstract = false, fields = listOf(
                PlanField.linked("rename", key = StorageKey.Fixed(Slots.Mutation.rename), plural = false, selection = selection1),
            ))
        }
        private val selection1: Selection by lazy {
            Selection(type = Types.FavoritePayload, key = listOf(), isAbstract = false, fields = listOf(
                PlanField.linked("character", key = StorageKey.Fixed(Slots.FavoritePayload.character), plural = false, selection = selection2),
            ))
        }
        private val selection2: Selection by lazy {
            Selection(type = Types.Character, key = listOf("id"), isAbstract = false, fields = listOf(
                PlanField.scalar("id", key = StorageKey.Fixed(Slots.Character.id), kind = ScalarKind.STRING, list = false),
                PlanField.scalar("name", key = StorageKey.Fixed(Slots.Character.name), kind = ScalarKind.STRING, list = false),
                PlanField.linked("origin", key = StorageKey.Fixed(Slots.Character.origin), plural = false, guards = listOf(listOf(Guard("withOrigin", passing = true))), selection = selection3),
            ))
        }
        private val selection3: Selection by lazy {
            Selection(type = Types.Location, key = listOf("id"), isAbstract = false, fields = listOf(
                PlanField.scalar("id", key = StorageKey.Fixed(Slots.Location.id), kind = ScalarKind.STRING, list = false),
                PlanField.scalar("name", key = StorageKey.Fixed(Slots.Location.name), kind = ScalarKind.STRING, list = false),
            ))
        }

        override fun data(anchor: Anchor): Data = Data(anchor)
    }

    @Stable
    class Data(override val anchor: Anchor) : Lens {
        val rename: Rename? get() = anchor.linked(Slots.Mutation.rename)?.let(::Rename)
        override fun equals(other: Any?): Boolean = other is TestRenameWithOrigin.Data && other.anchor == anchor
        override fun hashCode(): Int = anchor.hashCode()

        @Stable
        class Rename(override val anchor: Anchor) : Lens {
            val character: Character? get() = anchor.linked(Slots.FavoritePayload.character)?.let(::Character)
            override fun equals(other: Any?): Boolean = other is TestRenameWithOrigin.Data.Rename && other.anchor == anchor
            override fun hashCode(): Int = anchor.hashCode()

            @Stable
            class Character(override val anchor: Anchor) : Lens {
                val id: String? get() = anchor.string(Slots.Character.id)
                val name: String? get() = anchor.string(Slots.Character.name)
                val origin: Origin? get() = if (anchor.owner.selects(Guards.withOrigin_true)) anchor.linked(Slots.Character.origin)?.let(::Origin) else null
                override fun equals(other: Any?): Boolean = other is TestRenameWithOrigin.Data.Rename.Character && other.anchor == anchor
                override fun hashCode(): Int = anchor.hashCode()

                @Stable
                class Origin(override val anchor: Anchor) : Lens {
                    val id: String? get() = anchor.string(Slots.Location.id)
                    val name: String? get() = anchor.string(Slots.Location.name)
                    override fun equals(other: Any?): Boolean = other is TestRenameWithOrigin.Data.Rename.Character.Origin && other.anchor == anchor
                    override fun hashCode(): Int = anchor.hashCode()
                }
            }
        }
    }

    /** A partial response to show before the server answers; absent fields leave the store untouched. */
    class OptimisticResponse(val rename: Rename? = null) {
        /** The response's data as a variable, an absent field left out. */
        @Generated
        val variable: Variable
            get() = Variable.Object(Variables.of("rename" to this.rename?.variable).values)
        /** The response this builder describes, as the bytes the door takes. */
        val payload: Payload get() = Payload(data = variable)

        /** A partial response to show before the server answers; absent fields leave the store untouched. */
        class Rename(val character: Character? = null) {
            /** The response's data as a variable, an absent field left out. */
            @Generated
            val variable: Variable
                get() = Variable.Object(Variables.of("character" to this.character?.variable).values)

            /** A partial response to show before the server answers; absent fields leave the store untouched. */
            class Character(val id: String? = null, val name: String? = null, val origin: Origin? = null) {
                /** The response's data as a variable, an absent field left out. */
                @Generated
                val variable: Variable
                    get() = Variable.Object(Variables.of("id" to this.id?.let { Variable.of(it) }, "name" to this.name?.let { Variable.of(it) }, "origin" to this.origin?.variable).values)

                /** A partial response to show before the server answers; absent fields leave the store untouched. */
                class Origin(val id: String? = null, val name: String? = null) {
                    /** The response's data as a variable, an absent field left out. */
                    @Generated
                    val variable: Variable
                        get() = Variable.Object(Variables.of("id" to this.id?.let { Variable.of(it) }, "name" to this.name?.let { Variable.of(it) }).values)
                }
            }
        }
    }
}

/** Commits the mutation; the optimistic response, if any, shows at once and rebases until the server answers. */
suspend operator fun MutationAction<TestRenameWithOrigin, TestRenameWithOrigin.Data>.invoke(id: String, name: String, withOrigin: Boolean, optimistic: TestRenameWithOrigin.OptimisticResponse? = null): TestRenameWithOrigin.Data = this.commit(TestRenameWithOrigin(id, name, withOrigin), optimistic?.payload)

/** Operation value for `query TestSearch`. */
class TestSearch(val name: String) : QueryOperation<TestSearch.Data> {
    override val variables: Variables
        get() = Variables.of("name" to Variable.of(name))
    override var resolution: Resolution<OperationHandle<Data>> = Resolution.Unresolved
    override val type: OperationType<Data> get() = Companion

    override fun equals(other: Any?): Boolean = other is TestSearch && other.name == name
    override fun hashCode(): Int = listOf(name).hashCode()

    companion object : OperationType<Data> {
        override val name = "TestSearch"
        override val document: Document = Document.Text("query TestSearch(\$name:String!){search(name:\$name){__typename,...on Character{id,name},...on Location{id,name,dimension},...on Node{__isNode:__typename,id}}}")
        override val kind = OperationKind.QUERY
        override val plan: Plan by lazy { Plan(root = selection0, transient = Types.transient) }
        private val selection0: Selection by lazy {
            Selection(type = Types.Query, key = listOf(), isAbstract = false, fields = listOf(
                PlanField.linked("search", key = StorageKey.Dynamic(Slots.Query.search_954c44), plural = true, selection = selection1),
            ))
        }
        private val selection1: Selection by lazy {
            Selection(type = Types.SearchResult, key = listOf("id"), isAbstract = true, memberships = listOf(Selection.MembershipAnswer("__isNode", Types.Node)), variants = listOf(
                Selection.Variant(types = listOf(Types.Character), key = listOf("id"), fields = listOf(
                    PlanField.scalar("__typename", key = StorageKey.Fixed(Slots.Character.__typename), kind = ScalarKind.STRING, list = false),
                    PlanField.scalar("id", key = StorageKey.Fixed(Slots.Character.id), kind = ScalarKind.STRING, list = false),
                    PlanField.scalar("name", key = StorageKey.Fixed(Slots.Character.name), kind = ScalarKind.STRING, list = false),
                )),
                Selection.Variant(types = listOf(Types.Episode), key = listOf("id"), fields = listOf(
                    PlanField.scalar("__typename", key = StorageKey.Fixed(Slots.Episode.__typename), kind = ScalarKind.STRING, list = false),
                    PlanField.scalar("id", key = StorageKey.Fixed(Slots.Episode.id), kind = ScalarKind.STRING, list = false),
                )),
                Selection.Variant(types = listOf(Types.Location), key = listOf("id"), fields = listOf(
                    PlanField.scalar("__typename", key = StorageKey.Fixed(Slots.Location.__typename), kind = ScalarKind.STRING, list = false),
                    PlanField.scalar("id", key = StorageKey.Fixed(Slots.Location.id), kind = ScalarKind.STRING, list = false),
                    PlanField.scalar("name", key = StorageKey.Fixed(Slots.Location.name), kind = ScalarKind.STRING, list = false),
                    PlanField.scalar("dimension", key = StorageKey.Fixed(Slots.Location.dimension), kind = ScalarKind.STRING, list = false),
                )),
                Selection.Variant(types = null, condition = Types.Node, fields = listOf(
                    PlanField.scalar("__typename", key = StorageKey.Fixed(Slots.SearchResult.__typename), kind = ScalarKind.STRING, list = false),
                    PlanField.scalar("id", key = StorageKey.Fixed(Slots.SearchResult.id), kind = ScalarKind.STRING, list = false),
                )),
                Selection.Variant(types = null, fields = listOf(
                    PlanField.scalar("__typename", key = StorageKey.Fixed(Slots.SearchResult.__typename), kind = ScalarKind.STRING, list = false),
                )),
            ))
        }

        override fun data(anchor: Anchor): Data = Data(anchor)
    }

    @Stable
    class Data(override val anchor: Anchor) : Lens {
        val search: List<Search>? get() = anchor.list(anchor.owner.slot(Slots.Query.search_954c44), ::Search)
        override fun equals(other: Any?): Boolean = other is TestSearch.Data && other.anchor == anchor
        override fun hashCode(): Int = anchor.hashCode()

        @Stable
        class Search(override val anchor: Anchor) : Lens {
            val asCharacter: AsCharacter? get() = if (anchor.record.type == Types.Character) AsCharacter(anchor) else null
            val asLocation: AsLocation? get() = if (anchor.record.type == Types.Location) AsLocation(anchor) else null
            override fun equals(other: Any?): Boolean = other is TestSearch.Data.Search && other.anchor == anchor
            override fun hashCode(): Int = anchor.hashCode()

            @Stable
            class AsCharacter(override val anchor: Anchor) : Lens {
                val id: String? get() = anchor.string(Slots.Character.id)
                val name: String? get() = anchor.string(Slots.Character.name)
                override fun equals(other: Any?): Boolean = other is TestSearch.Data.Search.AsCharacter && other.anchor == anchor
                override fun hashCode(): Int = anchor.hashCode()
            }

            @Stable
            class AsLocation(override val anchor: Anchor) : Lens {
                val id: String? get() = anchor.string(Slots.Location.id)
                val name: String? get() = anchor.string(Slots.Location.name)
                val dimension: String? get() = anchor.string(Slots.Location.dimension)
                override fun equals(other: Any?): Boolean = other is TestSearch.Data.Search.AsLocation && other.anchor == anchor
                override fun hashCode(): Int = anchor.hashCode()
            }
        }
    }
}

/** Operation value for `query TestSearchOrigins`. */
class TestSearchOrigins(val name: String) : QueryOperation<TestSearchOrigins.Data> {
    override val variables: Variables
        get() = Variables.of("name" to Variable.of(name))
    override var resolution: Resolution<OperationHandle<Data>> = Resolution.Unresolved
    override val type: OperationType<Data> get() = Companion

    override fun equals(other: Any?): Boolean = other is TestSearchOrigins && other.name == name
    override fun hashCode(): Int = listOf(name).hashCode()

    companion object : OperationType<Data> {
        override val name = "TestSearchOrigins"
        override val document: Document = Document.Text("query TestSearchOrigins(\$name:String!){search(name:\$name){__typename,...on Character{origin{name,id}},...on Node{__isNode:__typename,id}}}")
        override val kind = OperationKind.QUERY
        override val plan: Plan by lazy { Plan(root = selection0, transient = Types.transient) }
        private val selection0: Selection by lazy {
            Selection(type = Types.Query, key = listOf(), isAbstract = false, fields = listOf(
                PlanField.linked("search", key = StorageKey.Dynamic(Slots.Query.search_954c44), plural = true, selection = selection1),
            ))
        }
        private val selection1: Selection by lazy {
            Selection(type = Types.SearchResult, key = listOf("id"), isAbstract = true, memberships = listOf(Selection.MembershipAnswer("__isNode", Types.Node)), variants = listOf(
                Selection.Variant(types = listOf(Types.Character), key = listOf("id"), fields = listOf(
                    PlanField.scalar("__typename", key = StorageKey.Fixed(Slots.Character.__typename), kind = ScalarKind.STRING, list = false),
                    PlanField.linked("origin", key = StorageKey.Fixed(Slots.Character.origin), plural = false, selection = selection2),
                    PlanField.scalar("id", key = StorageKey.Fixed(Slots.Character.id), kind = ScalarKind.STRING, list = false),
                )),
                Selection.Variant(types = listOf(Types.Episode, Types.Location), key = listOf("id"), fields = listOf(
                    PlanField.scalar("__typename", key = StorageKey.Fixed(Slots.SearchResult.__typename), kind = ScalarKind.STRING, list = false),
                    PlanField.scalar("id", key = StorageKey.Fixed(Slots.SearchResult.id), kind = ScalarKind.STRING, list = false),
                )),
                Selection.Variant(types = null, condition = Types.Node, fields = listOf(
                    PlanField.scalar("__typename", key = StorageKey.Fixed(Slots.SearchResult.__typename), kind = ScalarKind.STRING, list = false),
                    PlanField.scalar("id", key = StorageKey.Fixed(Slots.SearchResult.id), kind = ScalarKind.STRING, list = false),
                )),
                Selection.Variant(types = null, fields = listOf(
                    PlanField.scalar("__typename", key = StorageKey.Fixed(Slots.SearchResult.__typename), kind = ScalarKind.STRING, list = false),
                )),
            ))
        }
        private val selection2: Selection by lazy {
            Selection(type = Types.Location, key = listOf("id"), isAbstract = false, fields = listOf(
                PlanField.scalar("name", key = StorageKey.Fixed(Slots.Location.name), kind = ScalarKind.STRING, list = false),
                PlanField.scalar("id", key = StorageKey.Fixed(Slots.Location.id), kind = ScalarKind.STRING, list = false),
            ))
        }

        override fun data(anchor: Anchor): Data = Data(anchor)
    }

    @Stable
    class Data(override val anchor: Anchor) : Lens {
        val search: List<Search>? get() = anchor.list(anchor.owner.slot(Slots.Query.search_954c44), ::Search)
        override fun equals(other: Any?): Boolean = other is TestSearchOrigins.Data && other.anchor == anchor
        override fun hashCode(): Int = anchor.hashCode()

        @Stable
        class Search(override val anchor: Anchor) : Lens {
            val asCharacter: AsCharacter? get() = if (anchor.record.type == Types.Character) AsCharacter(anchor) else null
            override fun equals(other: Any?): Boolean = other is TestSearchOrigins.Data.Search && other.anchor == anchor
            override fun hashCode(): Int = anchor.hashCode()

            @Stable
            class AsCharacter(override val anchor: Anchor) : Lens {
                val origin: Origin? get() = anchor.linked(Slots.Character.origin)?.let(::Origin)
                override fun equals(other: Any?): Boolean = other is TestSearchOrigins.Data.Search.AsCharacter && other.anchor == anchor
                override fun hashCode(): Int = anchor.hashCode()

                @Stable
                class Origin(override val anchor: Anchor) : Lens {
                    val name: String? get() = anchor.string(Slots.Location.name)
                    override fun equals(other: Any?): Boolean = other is TestSearchOrigins.Data.Search.AsCharacter.Origin && other.anchor == anchor
                    override fun hashCode(): Int = anchor.hashCode()
                }
            }
        }
    }
}

/** Operation value for `mutation TestSetFavorite`. */
class TestSetFavorite(val id: String, val favorite: Boolean) : MutationOperation<TestSetFavorite.Data> {
    override val variables: Variables
        get() = Variables.of("id" to Variable.of(id), "favorite" to Variable.of(favorite))
    override val type: OperationType<Data> get() = Companion

    override fun equals(other: Any?): Boolean = other is TestSetFavorite && other.id == id && other.favorite == favorite
    override fun hashCode(): Int = listOf(id, favorite).hashCode()

    companion object : OperationType<Data> {
        override val name = "TestSetFavorite"
        override val document: Document = Document.Text("mutation TestSetFavorite(\$id:ID!,\$favorite:Boolean!){setFavorite(id:\$id,favorite:\$favorite){character{id,name,favorite}}}")
        override val kind = OperationKind.MUTATION
        override val plan: Plan by lazy { Plan(root = selection0, transient = Types.transient) }
        private val selection0: Selection by lazy {
            Selection(type = Types.Mutation, key = listOf(), isAbstract = false, fields = listOf(
                PlanField.linked("setFavorite", key = StorageKey.Fixed(Slots.Mutation.setFavorite), plural = false, selection = selection1),
            ))
        }
        private val selection1: Selection by lazy {
            Selection(type = Types.FavoritePayload, key = listOf(), isAbstract = false, fields = listOf(
                PlanField.linked("character", key = StorageKey.Fixed(Slots.FavoritePayload.character), plural = false, selection = selection2),
            ))
        }
        private val selection2: Selection by lazy {
            Selection(type = Types.Character, key = listOf("id"), isAbstract = false, fields = listOf(
                PlanField.scalar("id", key = StorageKey.Fixed(Slots.Character.id), kind = ScalarKind.STRING, list = false),
                PlanField.scalar("name", key = StorageKey.Fixed(Slots.Character.name), kind = ScalarKind.STRING, list = false),
                PlanField.scalar("favorite", key = StorageKey.Fixed(Slots.Character.favorite), kind = ScalarKind.BOOL, list = false),
            ))
        }

        override fun data(anchor: Anchor): Data = Data(anchor)
    }

    @Stable
    class Data(override val anchor: Anchor) : Lens {
        val setFavorite: SetFavorite? get() = anchor.linked(Slots.Mutation.setFavorite)?.let(::SetFavorite)
        override fun equals(other: Any?): Boolean = other is TestSetFavorite.Data && other.anchor == anchor
        override fun hashCode(): Int = anchor.hashCode()

        @Stable
        class SetFavorite(override val anchor: Anchor) : Lens {
            val character: Character? get() = anchor.linked(Slots.FavoritePayload.character)?.let(::Character)
            override fun equals(other: Any?): Boolean = other is TestSetFavorite.Data.SetFavorite && other.anchor == anchor
            override fun hashCode(): Int = anchor.hashCode()

            @Stable
            class Character(override val anchor: Anchor) : Lens {
                val id: String? get() = anchor.string(Slots.Character.id)
                val name: String? get() = anchor.string(Slots.Character.name)
                val favorite: Boolean? get() = anchor.bool(Slots.Character.favorite)
                override fun equals(other: Any?): Boolean = other is TestSetFavorite.Data.SetFavorite.Character && other.anchor == anchor
                override fun hashCode(): Int = anchor.hashCode()
            }
        }
    }

    /** A partial response to show before the server answers; absent fields leave the store untouched. */
    class OptimisticResponse(val setFavorite: SetFavorite? = null) {
        /** The response's data as a variable, an absent field left out. */
        @Generated
        val variable: Variable
            get() = Variable.Object(Variables.of("setFavorite" to this.setFavorite?.variable).values)
        /** The response this builder describes, as the bytes the door takes. */
        val payload: Payload get() = Payload(data = variable)

        /** A partial response to show before the server answers; absent fields leave the store untouched. */
        class SetFavorite(val character: Character? = null) {
            /** The response's data as a variable, an absent field left out. */
            @Generated
            val variable: Variable
                get() = Variable.Object(Variables.of("character" to this.character?.variable).values)

            /** A partial response to show before the server answers; absent fields leave the store untouched. */
            class Character(val id: String? = null, val name: String? = null, val favorite: Boolean? = null) {
                /** The response's data as a variable, an absent field left out. */
                @Generated
                val variable: Variable
                    get() = Variable.Object(Variables.of("id" to this.id?.let { Variable.of(it) }, "name" to this.name?.let { Variable.of(it) }, "favorite" to this.favorite?.let { Variable.of(it) }).values)
            }
        }
    }
}

/** Commits the mutation; the optimistic response, if any, shows at once and rebases until the server answers. */
suspend operator fun MutationAction<TestSetFavorite, TestSetFavorite.Data>.invoke(id: String, favorite: Boolean, optimistic: TestSetFavorite.OptimisticResponse? = null): TestSetFavorite.Data = this.commit(TestSetFavorite(id, favorite), optimistic?.payload)
